// MIT License
//
// Copyright (c) 2025 Eigen
//
// Permission is hereby granted, free of charge, to any person obtaining a copy
// of this software and associated documentation files (the "Software"), to deal
// in the Software without restriction, including without limitation the rights
// to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
// copies of the Software, and to permit persons to whom the Software is
// furnished to do so, subject to the following conditions:
//
// The above copyright notice and this permission notice shall be included in all
// copies or substantial portions of the Software.
//
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
// IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
// FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
// AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
// LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
// OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
// SOFTWARE.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        (unknown)
// source: oppb/v1/authorization_parameters.proto

package oppb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AuthorizationParameters struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// https://openid.net/specs/openid-connect-core-1_0.html#AuthRequest
	Scopes       []string `protobuf:"bytes,1,rep,name=scopes,proto3" json:"scopes,omitempty"`
	ResponseType string   `protobuf:"bytes,2,opt,name=response_type,proto3" json:"response_type,omitempty"`
	ClientId     string   `protobuf:"bytes,3,opt,name=client_id,proto3" json:"client_id,omitempty"`
	RedirectUri  string   `protobuf:"bytes,4,opt,name=redirect_uri,proto3" json:"redirect_uri,omitempty"`
	State        string   `protobuf:"bytes,5,opt,name=state,proto3" json:"state,omitempty"`
	ResponseMode string   `protobuf:"bytes,6,opt,name=response_mode,proto3" json:"response_mode,omitempty"`
	Nonce        string   `protobuf:"bytes,7,opt,name=nonce,proto3" json:"nonce,omitempty"`
	Display      string   `protobuf:"bytes,8,opt,name=display,proto3" json:"display,omitempty"`
	Prompts      []string `protobuf:"bytes,9,rep,name=prompts,proto3" json:"prompts,omitempty"`
	MaxAge       string   `protobuf:"bytes,10,opt,name=max_age,proto3" json:"max_age,omitempty"`
	UiLocales    []string `protobuf:"bytes,11,rep,name=ui_locales,proto3" json:"ui_locales,omitempty"`
	IdTokenHint  string   `protobuf:"bytes,12,opt,name=id_token_hint,proto3" json:"id_token_hint,omitempty"`
	LoginHint    string   `protobuf:"bytes,13,opt,name=login_hint,proto3" json:"login_hint,omitempty"`
	AcrValues    []string `protobuf:"bytes,14,rep,name=acr_values,proto3" json:"acr_values,omitempty"`
	// https://openid.net/specs/openid-connect-core-1_0.html#ClaimsLanguagesAndScripts
	ClaimsLocales []string `protobuf:"bytes,15,rep,name=claims_locales,proto3" json:"claims_locales,omitempty"`
	// https://openid.net/specs/openid-connect-core-1_0.html#ClaimsParameter
	Claims string `protobuf:"bytes,16,opt,name=claims,proto3" json:"claims,omitempty"`
	// https://datatracker.ietf.org/doc/html/rfc7636#section-4.3
	CodeChallenge       string `protobuf:"bytes,19,opt,name=code_challenge,proto3" json:"code_challenge,omitempty"`
	CodeChallengeMethod string `protobuf:"bytes,20,opt,name=code_challenge_method,proto3" json:"code_challenge_method,omitempty"`
	// https://openid.net/specs/openid-connect-core-1_0.html#JWTRequests
	Request    string `protobuf:"bytes,21,opt,name=request,proto3" json:"request,omitempty"`
	RequestUri string `protobuf:"bytes,22,opt,name=request_uri,proto3" json:"request_uri,omitempty"`
	// custom parameter
	IsPar         bool   `protobuf:"varint,50,opt,name=is_par,json=isPar,proto3" json:"is_par,omitempty"`
	ParKey        string `protobuf:"bytes,51,opt,name=par_key,json=parKey,proto3" json:"par_key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AuthorizationParameters) Reset() {
	*x = AuthorizationParameters{}
	mi := &file_oppb_v1_authorization_parameters_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuthorizationParameters) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuthorizationParameters) ProtoMessage() {}

func (x *AuthorizationParameters) ProtoReflect() protoreflect.Message {
	mi := &file_oppb_v1_authorization_parameters_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuthorizationParameters.ProtoReflect.Descriptor instead.
func (*AuthorizationParameters) Descriptor() ([]byte, []int) {
	return file_oppb_v1_authorization_parameters_proto_rawDescGZIP(), []int{0}
}

func (x *AuthorizationParameters) GetScopes() []string {
	if x != nil {
		return x.Scopes
	}
	return nil
}

func (x *AuthorizationParameters) GetResponseType() string {
	if x != nil {
		return x.ResponseType
	}
	return ""
}

func (x *AuthorizationParameters) GetClientId() string {
	if x != nil {
		return x.ClientId
	}
	return ""
}

func (x *AuthorizationParameters) GetRedirectUri() string {
	if x != nil {
		return x.RedirectUri
	}
	return ""
}

func (x *AuthorizationParameters) GetState() string {
	if x != nil {
		return x.State
	}
	return ""
}

func (x *AuthorizationParameters) GetResponseMode() string {
	if x != nil {
		return x.ResponseMode
	}
	return ""
}

func (x *AuthorizationParameters) GetNonce() string {
	if x != nil {
		return x.Nonce
	}
	return ""
}

func (x *AuthorizationParameters) GetDisplay() string {
	if x != nil {
		return x.Display
	}
	return ""
}

func (x *AuthorizationParameters) GetPrompts() []string {
	if x != nil {
		return x.Prompts
	}
	return nil
}

func (x *AuthorizationParameters) GetMaxAge() string {
	if x != nil {
		return x.MaxAge
	}
	return ""
}

func (x *AuthorizationParameters) GetUiLocales() []string {
	if x != nil {
		return x.UiLocales
	}
	return nil
}

func (x *AuthorizationParameters) GetIdTokenHint() string {
	if x != nil {
		return x.IdTokenHint
	}
	return ""
}

func (x *AuthorizationParameters) GetLoginHint() string {
	if x != nil {
		return x.LoginHint
	}
	return ""
}

func (x *AuthorizationParameters) GetAcrValues() []string {
	if x != nil {
		return x.AcrValues
	}
	return nil
}

func (x *AuthorizationParameters) GetClaimsLocales() []string {
	if x != nil {
		return x.ClaimsLocales
	}
	return nil
}

func (x *AuthorizationParameters) GetClaims() string {
	if x != nil {
		return x.Claims
	}
	return ""
}

func (x *AuthorizationParameters) GetCodeChallenge() string {
	if x != nil {
		return x.CodeChallenge
	}
	return ""
}

func (x *AuthorizationParameters) GetCodeChallengeMethod() string {
	if x != nil {
		return x.CodeChallengeMethod
	}
	return ""
}

func (x *AuthorizationParameters) GetRequest() string {
	if x != nil {
		return x.Request
	}
	return ""
}

func (x *AuthorizationParameters) GetRequestUri() string {
	if x != nil {
		return x.RequestUri
	}
	return ""
}

func (x *AuthorizationParameters) GetIsPar() bool {
	if x != nil {
		return x.IsPar
	}
	return false
}

func (x *AuthorizationParameters) GetParKey() string {
	if x != nil {
		return x.ParKey
	}
	return ""
}

var File_oppb_v1_authorization_parameters_proto protoreflect.FileDescriptor

const file_oppb_v1_authorization_parameters_proto_rawDesc = "" +
	"\n" +
	"&oppb/v1/authorization_parameters.proto\x12\aoppb.v1\"\xc9\x05\n" +
	"\x17AuthorizationParameters\x12\x16\n" +
	"\x06scopes\x18\x01 \x03(\tR\x06scopes\x12$\n" +
	"\rresponse_type\x18\x02 \x01(\tR\rresponse_type\x12\x1c\n" +
	"\tclient_id\x18\x03 \x01(\tR\tclient_id\x12\"\n" +
	"\fredirect_uri\x18\x04 \x01(\tR\fredirect_uri\x12\x14\n" +
	"\x05state\x18\x05 \x01(\tR\x05state\x12$\n" +
	"\rresponse_mode\x18\x06 \x01(\tR\rresponse_mode\x12\x14\n" +
	"\x05nonce\x18\a \x01(\tR\x05nonce\x12\x18\n" +
	"\adisplay\x18\b \x01(\tR\adisplay\x12\x18\n" +
	"\aprompts\x18\t \x03(\tR\aprompts\x12\x18\n" +
	"\amax_age\x18\n" +
	" \x01(\tR\amax_age\x12\x1e\n" +
	"\n" +
	"ui_locales\x18\v \x03(\tR\n" +
	"ui_locales\x12$\n" +
	"\rid_token_hint\x18\f \x01(\tR\rid_token_hint\x12\x1e\n" +
	"\n" +
	"login_hint\x18\r \x01(\tR\n" +
	"login_hint\x12\x1e\n" +
	"\n" +
	"acr_values\x18\x0e \x03(\tR\n" +
	"acr_values\x12&\n" +
	"\x0eclaims_locales\x18\x0f \x03(\tR\x0eclaims_locales\x12\x16\n" +
	"\x06claims\x18\x10 \x01(\tR\x06claims\x12&\n" +
	"\x0ecode_challenge\x18\x13 \x01(\tR\x0ecode_challenge\x124\n" +
	"\x15code_challenge_method\x18\x14 \x01(\tR\x15code_challenge_method\x12\x18\n" +
	"\arequest\x18\x15 \x01(\tR\arequest\x12 \n" +
	"\vrequest_uri\x18\x16 \x01(\tR\vrequest_uri\x12\x15\n" +
	"\x06is_par\x182 \x01(\bR\x05isPar\x12\x17\n" +
	"\apar_key\x183 \x01(\tR\x06parKeyB\xa2\x01\n" +
	"\vcom.oppb.v1B\x1cAuthorizationParametersProtoP\x01Z8github.com/Eigen438/opgo/pkg/auto-generated/oppb/v1;oppb\xa2\x02\x03OXX\xaa\x02\aOppb.V1\xca\x02\aOppb\\V1\xe2\x02\x13Oppb\\V1\\GPBMetadata\xea\x02\bOppb::V1b\x06proto3"

var (
	file_oppb_v1_authorization_parameters_proto_rawDescOnce sync.Once
	file_oppb_v1_authorization_parameters_proto_rawDescData []byte
)

func file_oppb_v1_authorization_parameters_proto_rawDescGZIP() []byte {
	file_oppb_v1_authorization_parameters_proto_rawDescOnce.Do(func() {
		file_oppb_v1_authorization_parameters_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_oppb_v1_authorization_parameters_proto_rawDesc), len(file_oppb_v1_authorization_parameters_proto_rawDesc)))
	})
	return file_oppb_v1_authorization_parameters_proto_rawDescData
}

var file_oppb_v1_authorization_parameters_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_oppb_v1_authorization_parameters_proto_goTypes = []any{
	(*AuthorizationParameters)(nil), // 0: oppb.v1.AuthorizationParameters
}
var file_oppb_v1_authorization_parameters_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_oppb_v1_authorization_parameters_proto_init() }
func file_oppb_v1_authorization_parameters_proto_init() {
	if File_oppb_v1_authorization_parameters_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_oppb_v1_authorization_parameters_proto_rawDesc), len(file_oppb_v1_authorization_parameters_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_oppb_v1_authorization_parameters_proto_goTypes,
		DependencyIndexes: file_oppb_v1_authorization_parameters_proto_depIdxs,
		MessageInfos:      file_oppb_v1_authorization_parameters_proto_msgTypes,
	}.Build()
	File_oppb_v1_authorization_parameters_proto = out.File
	file_oppb_v1_authorization_parameters_proto_goTypes = nil
	file_oppb_v1_authorization_parameters_proto_depIdxs = nil
}
