// MIT License
//
// Copyright (c) 2025 Eigen
//
// Permission is hereby granted, free of charge, to any person obtaining a copy
// of this software and associated documentation files (the "Software"), to deal
// in the Software without restriction, including without limitation the rights
// to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
// copies of the Software, and to permit persons to whom the Software is
// furnished to do so, subject to the following conditions:
//
// The above copyright notice and this permission notice shall be included in all
// copies or substantial portions of the Software.
//
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
// IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
// FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
// AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
// LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
// OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
// SOFTWARE.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        (unknown)
// source: oppb/v1/client.proto

package oppb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type EnumClientProfile int32

const (
	EnumClientProfile_ENUM_CLIENT_PROFILE_UNSPECIFIED EnumClientProfile = 0
	EnumClientProfile_ENUM_CLIENT_PROFILE_FAPI_1_0    EnumClientProfile = 1
	EnumClientProfile_ENUM_CLIENT_PROFILE_FAPI_2_0    EnumClientProfile = 2
)

// Enum value maps for EnumClientProfile.
var (
	EnumClientProfile_name = map[int32]string{
		0: "ENUM_CLIENT_PROFILE_UNSPECIFIED",
		1: "ENUM_CLIENT_PROFILE_FAPI_1_0",
		2: "ENUM_CLIENT_PROFILE_FAPI_2_0",
	}
	EnumClientProfile_value = map[string]int32{
		"ENUM_CLIENT_PROFILE_UNSPECIFIED": 0,
		"ENUM_CLIENT_PROFILE_FAPI_1_0":    1,
		"ENUM_CLIENT_PROFILE_FAPI_2_0":    2,
	}
)

func (x EnumClientProfile) Enum() *EnumClientProfile {
	p := new(EnumClientProfile)
	*p = x
	return p
}

func (x EnumClientProfile) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (EnumClientProfile) Descriptor() protoreflect.EnumDescriptor {
	return file_oppb_v1_client_proto_enumTypes[0].Descriptor()
}

func (EnumClientProfile) Type() protoreflect.EnumType {
	return &file_oppb_v1_client_proto_enumTypes[0]
}

func (x EnumClientProfile) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use EnumClientProfile.Descriptor instead.
func (EnumClientProfile) EnumDescriptor() ([]byte, []int) {
	return file_oppb_v1_client_proto_rawDescGZIP(), []int{0}
}

type ClientAttribute struct {
	state                            protoimpl.MessageState `protogen:"open.v1"`
	AccessTokenLifetimeSeconds       int32                  `protobuf:"varint,1,opt,name=access_token_lifetime_seconds,proto3" json:"access_token_lifetime_seconds,omitempty"`
	AuthorizationCodeLifetimeSeconds int32                  `protobuf:"varint,2,opt,name=authorization_code_lifetime_seconds,proto3" json:"authorization_code_lifetime_seconds,omitempty"`
	IdTokenLifetimeSeconds           int32                  `protobuf:"varint,3,opt,name=id_token_lifetime_seconds,proto3" json:"id_token_lifetime_seconds,omitempty"`
	RefreshTokenLifetimeSeconds      int32                  `protobuf:"varint,4,opt,name=refresh_token_lifetime_seconds,proto3" json:"refresh_token_lifetime_seconds,omitempty"`
	RequestLifetimeSeconds           int32                  `protobuf:"varint,5,opt,name=request_lifetime_seconds,proto3" json:"request_lifetime_seconds,omitempty"`
	JwtResponseLifetimeSeconds       int32                  `protobuf:"varint,6,opt,name=jwt_response_lifetime_seconds,proto3" json:"jwt_response_lifetime_seconds,omitempty"`
	SessionGroupId                   string                 `protobuf:"bytes,10,opt,name=session_group_id,proto3" json:"session_group_id,omitempty"`
	unknownFields                    protoimpl.UnknownFields
	sizeCache                        protoimpl.SizeCache
}

func (x *ClientAttribute) Reset() {
	*x = ClientAttribute{}
	mi := &file_oppb_v1_client_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClientAttribute) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClientAttribute) ProtoMessage() {}

func (x *ClientAttribute) ProtoReflect() protoreflect.Message {
	mi := &file_oppb_v1_client_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClientAttribute.ProtoReflect.Descriptor instead.
func (*ClientAttribute) Descriptor() ([]byte, []int) {
	return file_oppb_v1_client_proto_rawDescGZIP(), []int{0}
}

func (x *ClientAttribute) GetAccessTokenLifetimeSeconds() int32 {
	if x != nil {
		return x.AccessTokenLifetimeSeconds
	}
	return 0
}

func (x *ClientAttribute) GetAuthorizationCodeLifetimeSeconds() int32 {
	if x != nil {
		return x.AuthorizationCodeLifetimeSeconds
	}
	return 0
}

func (x *ClientAttribute) GetIdTokenLifetimeSeconds() int32 {
	if x != nil {
		return x.IdTokenLifetimeSeconds
	}
	return 0
}

func (x *ClientAttribute) GetRefreshTokenLifetimeSeconds() int32 {
	if x != nil {
		return x.RefreshTokenLifetimeSeconds
	}
	return 0
}

func (x *ClientAttribute) GetRequestLifetimeSeconds() int32 {
	if x != nil {
		return x.RequestLifetimeSeconds
	}
	return 0
}

func (x *ClientAttribute) GetJwtResponseLifetimeSeconds() int32 {
	if x != nil {
		return x.JwtResponseLifetimeSeconds
	}
	return 0
}

func (x *ClientAttribute) GetSessionGroupId() string {
	if x != nil {
		return x.SessionGroupId
	}
	return ""
}

type ClientExtensions struct {
	state                 protoimpl.MessageState `protogen:"open.v1"`
	Profile               EnumClientProfile      `protobuf:"varint,1,opt,name=profile,proto3,enum=oppb.v1.EnumClientProfile" json:"profile,omitempty"`
	TlsClientCertificates []string               `protobuf:"bytes,2,rep,name=tls_client_certificates,proto3" json:"tls_client_certificates,omitempty"`
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *ClientExtensions) Reset() {
	*x = ClientExtensions{}
	mi := &file_oppb_v1_client_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClientExtensions) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClientExtensions) ProtoMessage() {}

func (x *ClientExtensions) ProtoReflect() protoreflect.Message {
	mi := &file_oppb_v1_client_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClientExtensions.ProtoReflect.Descriptor instead.
func (*ClientExtensions) Descriptor() ([]byte, []int) {
	return file_oppb_v1_client_proto_rawDescGZIP(), []int{1}
}

func (x *ClientExtensions) GetProfile() EnumClientProfile {
	if x != nil {
		return x.Profile
	}
	return EnumClientProfile_ENUM_CLIENT_PROFILE_UNSPECIFIED
}

func (x *ClientExtensions) GetTlsClientCertificates() []string {
	if x != nil {
		return x.TlsClientCertificates
	}
	return nil
}

type Client struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Identity      *ClientIdentity        `protobuf:"bytes,1,opt,name=identity,proto3" json:"identity,omitempty"`
	Issuer        *CommonKey             `protobuf:"bytes,2,opt,name=issuer,proto3" json:"issuer,omitempty"`
	Meta          *ClientMeta            `protobuf:"bytes,3,opt,name=meta,proto3" json:"meta,omitempty"`
	Attribute     *ClientAttribute       `protobuf:"bytes,4,opt,name=attribute,proto3" json:"attribute,omitempty"`
	Extensions    *ClientExtensions      `protobuf:"bytes,5,opt,name=extensions,proto3" json:"extensions,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Client) Reset() {
	*x = Client{}
	mi := &file_oppb_v1_client_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Client) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Client) ProtoMessage() {}

func (x *Client) ProtoReflect() protoreflect.Message {
	mi := &file_oppb_v1_client_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Client.ProtoReflect.Descriptor instead.
func (*Client) Descriptor() ([]byte, []int) {
	return file_oppb_v1_client_proto_rawDescGZIP(), []int{2}
}

func (x *Client) GetIdentity() *ClientIdentity {
	if x != nil {
		return x.Identity
	}
	return nil
}

func (x *Client) GetIssuer() *CommonKey {
	if x != nil {
		return x.Issuer
	}
	return nil
}

func (x *Client) GetMeta() *ClientMeta {
	if x != nil {
		return x.Meta
	}
	return nil
}

func (x *Client) GetAttribute() *ClientAttribute {
	if x != nil {
		return x.Attribute
	}
	return nil
}

func (x *Client) GetExtensions() *ClientExtensions {
	if x != nil {
		return x.Extensions
	}
	return nil
}

var File_oppb_v1_client_proto protoreflect.FileDescriptor

const file_oppb_v1_client_proto_rawDesc = "" +
	"\n" +
	"\x14oppb/v1/client.proto\x12\aoppb.v1\x1a\x19oppb/v1/client_meta.proto\x1a\x14oppb/v1/common.proto\"\xdd\x03\n" +
	"\x0fClientAttribute\x12D\n" +
	"\x1daccess_token_lifetime_seconds\x18\x01 \x01(\x05R\x1daccess_token_lifetime_seconds\x12P\n" +
	"#authorization_code_lifetime_seconds\x18\x02 \x01(\x05R#authorization_code_lifetime_seconds\x12<\n" +
	"\x19id_token_lifetime_seconds\x18\x03 \x01(\x05R\x19id_token_lifetime_seconds\x12F\n" +
	"\x1erefresh_token_lifetime_seconds\x18\x04 \x01(\x05R\x1erefresh_token_lifetime_seconds\x12:\n" +
	"\x18request_lifetime_seconds\x18\x05 \x01(\x05R\x18request_lifetime_seconds\x12D\n" +
	"\x1djwt_response_lifetime_seconds\x18\x06 \x01(\x05R\x1djwt_response_lifetime_seconds\x12*\n" +
	"\x10session_group_id\x18\n" +
	" \x01(\tR\x10session_group_id\"\x82\x01\n" +
	"\x10ClientExtensions\x124\n" +
	"\aprofile\x18\x01 \x01(\x0e2\x1a.oppb.v1.EnumClientProfileR\aprofile\x128\n" +
	"\x17tls_client_certificates\x18\x02 \x03(\tR\x17tls_client_certificates\"\x85\x02\n" +
	"\x06Client\x123\n" +
	"\bidentity\x18\x01 \x01(\v2\x17.oppb.v1.ClientIdentityR\bidentity\x12*\n" +
	"\x06issuer\x18\x02 \x01(\v2\x12.oppb.v1.CommonKeyR\x06issuer\x12'\n" +
	"\x04meta\x18\x03 \x01(\v2\x13.oppb.v1.ClientMetaR\x04meta\x126\n" +
	"\tattribute\x18\x04 \x01(\v2\x18.oppb.v1.ClientAttributeR\tattribute\x129\n" +
	"\n" +
	"extensions\x18\x05 \x01(\v2\x19.oppb.v1.ClientExtensionsR\n" +
	"extensions*|\n" +
	"\x11EnumClientProfile\x12#\n" +
	"\x1fENUM_CLIENT_PROFILE_UNSPECIFIED\x10\x00\x12 \n" +
	"\x1cENUM_CLIENT_PROFILE_FAPI_1_0\x10\x01\x12 \n" +
	"\x1cENUM_CLIENT_PROFILE_FAPI_2_0\x10\x02B\x91\x01\n" +
	"\vcom.oppb.v1B\vClientProtoP\x01Z8github.com/Eigen438/opgo/pkg/auto-generated/oppb/v1;oppb\xa2\x02\x03OXX\xaa\x02\aOppb.V1\xca\x02\aOppb\\V1\xe2\x02\x13Oppb\\V1\\GPBMetadata\xea\x02\bOppb::V1b\x06proto3"

var (
	file_oppb_v1_client_proto_rawDescOnce sync.Once
	file_oppb_v1_client_proto_rawDescData []byte
)

func file_oppb_v1_client_proto_rawDescGZIP() []byte {
	file_oppb_v1_client_proto_rawDescOnce.Do(func() {
		file_oppb_v1_client_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_oppb_v1_client_proto_rawDesc), len(file_oppb_v1_client_proto_rawDesc)))
	})
	return file_oppb_v1_client_proto_rawDescData
}

var file_oppb_v1_client_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_oppb_v1_client_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_oppb_v1_client_proto_goTypes = []any{
	(EnumClientProfile)(0),   // 0: oppb.v1.EnumClientProfile
	(*ClientAttribute)(nil),  // 1: oppb.v1.ClientAttribute
	(*ClientExtensions)(nil), // 2: oppb.v1.ClientExtensions
	(*Client)(nil),           // 3: oppb.v1.Client
	(*ClientIdentity)(nil),   // 4: oppb.v1.ClientIdentity
	(*CommonKey)(nil),        // 5: oppb.v1.CommonKey
	(*ClientMeta)(nil),       // 6: oppb.v1.ClientMeta
}
var file_oppb_v1_client_proto_depIdxs = []int32{
	0, // 0: oppb.v1.ClientExtensions.profile:type_name -> oppb.v1.EnumClientProfile
	4, // 1: oppb.v1.Client.identity:type_name -> oppb.v1.ClientIdentity
	5, // 2: oppb.v1.Client.issuer:type_name -> oppb.v1.CommonKey
	6, // 3: oppb.v1.Client.meta:type_name -> oppb.v1.ClientMeta
	1, // 4: oppb.v1.Client.attribute:type_name -> oppb.v1.ClientAttribute
	2, // 5: oppb.v1.Client.extensions:type_name -> oppb.v1.ClientExtensions
	6, // [6:6] is the sub-list for method output_type
	6, // [6:6] is the sub-list for method input_type
	6, // [6:6] is the sub-list for extension type_name
	6, // [6:6] is the sub-list for extension extendee
	0, // [0:6] is the sub-list for field type_name
}

func init() { file_oppb_v1_client_proto_init() }
func file_oppb_v1_client_proto_init() {
	if File_oppb_v1_client_proto != nil {
		return
	}
	file_oppb_v1_client_meta_proto_init()
	file_oppb_v1_common_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_oppb_v1_client_proto_rawDesc), len(file_oppb_v1_client_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_oppb_v1_client_proto_goTypes,
		DependencyIndexes: file_oppb_v1_client_proto_depIdxs,
		EnumInfos:         file_oppb_v1_client_proto_enumTypes,
		MessageInfos:      file_oppb_v1_client_proto_msgTypes,
	}.Build()
	File_oppb_v1_client_proto = out.File
	file_oppb_v1_client_proto_goTypes = nil
	file_oppb_v1_client_proto_depIdxs = nil
}
