// MIT License
//
// Copyright (c) 2025 Eigen
//
// Permission is hereby granted, free of charge, to any person obtaining a copy
// of this software and associated documentation files (the "Software"), to deal
// in the Software without restriction, including without limitation the rights
// to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
// copies of the Software, and to permit persons to whom the Software is
// furnished to do so, subject to the following conditions:
//
// The above copyright notice and this permission notice shall be included in all
// copies or substantial portions of the Software.
//
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
// IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
// FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
// AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
// LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
// OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
// SOFTWARE.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        (unknown)
// source: oppb/v1/client_meta.proto

package oppb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ClientMeta struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// ClientMeta
	// https://openid.net/specs/openid-connect-registration-1_0.html#ClientMetadata
	RedirectUris                 []string `protobuf:"bytes,101,rep,name=redirect_uris,proto3" json:"redirect_uris,omitempty"`
	ResponseTypes                []string `protobuf:"bytes,102,rep,name=response_types,proto3" json:"response_types,omitempty"`
	GrantTypes                   []string `protobuf:"bytes,103,rep,name=grant_types,proto3" json:"grant_types,omitempty"`
	ApplicationType              string   `protobuf:"bytes,104,opt,name=application_type,proto3" json:"application_type,omitempty"`
	Contacts                     []string `protobuf:"bytes,105,rep,name=contacts,proto3" json:"contacts,omitempty"`
	ClientName                   string   `protobuf:"bytes,106,opt,name=client_name,proto3" json:"client_name,omitempty"`
	LogoUri                      string   `protobuf:"bytes,107,opt,name=logo_uri,proto3" json:"logo_uri,omitempty"`
	ClientUri                    string   `protobuf:"bytes,108,opt,name=client_uri,proto3" json:"client_uri,omitempty"`
	PolicyUri                    string   `protobuf:"bytes,109,opt,name=policy_uri,proto3" json:"policy_uri,omitempty"`
	TosUri                       string   `protobuf:"bytes,110,opt,name=tos_uri,proto3" json:"tos_uri,omitempty"`
	JwksUri                      string   `protobuf:"bytes,111,opt,name=jwks_uri,proto3" json:"jwks_uri,omitempty"`
	Jwks                         *Jwks    `protobuf:"bytes,112,opt,name=jwks,proto3" json:"jwks,omitempty"`
	SectorIdentifierUri          string   `protobuf:"bytes,113,opt,name=sector_identifier_uri,proto3" json:"sector_identifier_uri,omitempty"`
	SubjectType                  string   `protobuf:"bytes,114,opt,name=subject_type,proto3" json:"subject_type,omitempty"`
	IdTokenSignedResponseAlg     string   `protobuf:"bytes,115,opt,name=id_token_signed_response_alg,proto3" json:"id_token_signed_response_alg,omitempty"`
	IdTokenEncryptedResponseAlg  string   `protobuf:"bytes,116,opt,name=id_token_encrypted_response_alg,proto3" json:"id_token_encrypted_response_alg,omitempty"`
	IdTokenEncryptedResponseEnc  string   `protobuf:"bytes,117,opt,name=id_token_encrypted_response_enc,proto3" json:"id_token_encrypted_response_enc,omitempty"`
	UserinfoSignedResponseAlg    string   `protobuf:"bytes,118,opt,name=userinfo_signed_response_alg,proto3" json:"userinfo_signed_response_alg,omitempty"`
	UserinfoEncryptedResponseAlg string   `protobuf:"bytes,119,opt,name=userinfo_encrypted_response_alg,proto3" json:"userinfo_encrypted_response_alg,omitempty"`
	UserinfoEncryptedResponseEnc string   `protobuf:"bytes,120,opt,name=userinfo_encrypted_response_enc,proto3" json:"userinfo_encrypted_response_enc,omitempty"`
	RequestObjectSigningAlg      string   `protobuf:"bytes,121,opt,name=request_object_signing_alg,proto3" json:"request_object_signing_alg,omitempty"`
	RequestObjectEncryptionAlg   string   `protobuf:"bytes,122,opt,name=request_object_encryption_alg,proto3" json:"request_object_encryption_alg,omitempty"`
	RequestObjectEncryptionEnc   string   `protobuf:"bytes,123,opt,name=request_object_encryption_enc,proto3" json:"request_object_encryption_enc,omitempty"`
	TokenEndpointAuthMethod      string   `protobuf:"bytes,124,opt,name=token_endpoint_auth_method,proto3" json:"token_endpoint_auth_method,omitempty"`
	TokenEndpointAuthSigningAlg  string   `protobuf:"bytes,125,opt,name=token_endpoint_auth_signing_alg,proto3" json:"token_endpoint_auth_signing_alg,omitempty"`
	DefaultMaxAge                string   `protobuf:"bytes,126,opt,name=default_max_age,proto3" json:"default_max_age,omitempty"`
	RequireAuthTime              bool     `protobuf:"varint,127,opt,name=require_auth_time,proto3" json:"require_auth_time,omitempty"`
	DefaultAcrValues             []string `protobuf:"bytes,128,rep,name=default_acr_values,proto3" json:"default_acr_values,omitempty"`
	InitiateLoginUri             string   `protobuf:"bytes,129,opt,name=initiate_login_uri,proto3" json:"initiate_login_uri,omitempty"`
	RequestUris                  []string `protobuf:"bytes,130,rep,name=request_uris,proto3" json:"request_uris,omitempty"`
	// https://openid.net/specs/openid-connect-rpinitiated-1_0.html#ClientMetadata
	PostLogoutRedirectUris []string `protobuf:"bytes,131,rep,name=post_logout_redirect_uris,proto3" json:"post_logout_redirect_uris,omitempty"`
	// https://www.rfc-editor.org/rfc/rfc9126.html#section-6
	RequirePushedAuthorizationRequests bool `protobuf:"varint,132,opt,name=require_pushed_authorization_requests,proto3" json:"require_pushed_authorization_requests,omitempty"`
	// https://openid.net/specs/openid-financial-api-jarm.html#client-metadata
	AuthorizationSignedResponseAlg    string `protobuf:"bytes,133,opt,name=authorization_signed_response_alg,proto3" json:"authorization_signed_response_alg,omitempty"`
	AuthorizationEncryptedResponseAlg string `protobuf:"bytes,134,opt,name=authorization_encrypted_response_alg,proto3" json:"authorization_encrypted_response_alg,omitempty"`
	AuthorizationEncryptedResponseEnc string `protobuf:"bytes,135,opt,name=authorization_encrypted_response_enc,proto3" json:"authorization_encrypted_response_enc,omitempty"`
	// https://datatracker.ietf.org/doc/html/rfc8705#section-3.4
	TlsClientCertificateBoundAccessTokens bool `protobuf:"varint,136,opt,name=tls_client_certificate_bound_access_tokens,proto3" json:"tls_client_certificate_bound_access_tokens,omitempty"`
	unknownFields                         protoimpl.UnknownFields
	sizeCache                             protoimpl.SizeCache
}

func (x *ClientMeta) Reset() {
	*x = ClientMeta{}
	mi := &file_oppb_v1_client_meta_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClientMeta) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClientMeta) ProtoMessage() {}

func (x *ClientMeta) ProtoReflect() protoreflect.Message {
	mi := &file_oppb_v1_client_meta_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClientMeta.ProtoReflect.Descriptor instead.
func (*ClientMeta) Descriptor() ([]byte, []int) {
	return file_oppb_v1_client_meta_proto_rawDescGZIP(), []int{0}
}

func (x *ClientMeta) GetRedirectUris() []string {
	if x != nil {
		return x.RedirectUris
	}
	return nil
}

func (x *ClientMeta) GetResponseTypes() []string {
	if x != nil {
		return x.ResponseTypes
	}
	return nil
}

func (x *ClientMeta) GetGrantTypes() []string {
	if x != nil {
		return x.GrantTypes
	}
	return nil
}

func (x *ClientMeta) GetApplicationType() string {
	if x != nil {
		return x.ApplicationType
	}
	return ""
}

func (x *ClientMeta) GetContacts() []string {
	if x != nil {
		return x.Contacts
	}
	return nil
}

func (x *ClientMeta) GetClientName() string {
	if x != nil {
		return x.ClientName
	}
	return ""
}

func (x *ClientMeta) GetLogoUri() string {
	if x != nil {
		return x.LogoUri
	}
	return ""
}

func (x *ClientMeta) GetClientUri() string {
	if x != nil {
		return x.ClientUri
	}
	return ""
}

func (x *ClientMeta) GetPolicyUri() string {
	if x != nil {
		return x.PolicyUri
	}
	return ""
}

func (x *ClientMeta) GetTosUri() string {
	if x != nil {
		return x.TosUri
	}
	return ""
}

func (x *ClientMeta) GetJwksUri() string {
	if x != nil {
		return x.JwksUri
	}
	return ""
}

func (x *ClientMeta) GetJwks() *Jwks {
	if x != nil {
		return x.Jwks
	}
	return nil
}

func (x *ClientMeta) GetSectorIdentifierUri() string {
	if x != nil {
		return x.SectorIdentifierUri
	}
	return ""
}

func (x *ClientMeta) GetSubjectType() string {
	if x != nil {
		return x.SubjectType
	}
	return ""
}

func (x *ClientMeta) GetIdTokenSignedResponseAlg() string {
	if x != nil {
		return x.IdTokenSignedResponseAlg
	}
	return ""
}

func (x *ClientMeta) GetIdTokenEncryptedResponseAlg() string {
	if x != nil {
		return x.IdTokenEncryptedResponseAlg
	}
	return ""
}

func (x *ClientMeta) GetIdTokenEncryptedResponseEnc() string {
	if x != nil {
		return x.IdTokenEncryptedResponseEnc
	}
	return ""
}

func (x *ClientMeta) GetUserinfoSignedResponseAlg() string {
	if x != nil {
		return x.UserinfoSignedResponseAlg
	}
	return ""
}

func (x *ClientMeta) GetUserinfoEncryptedResponseAlg() string {
	if x != nil {
		return x.UserinfoEncryptedResponseAlg
	}
	return ""
}

func (x *ClientMeta) GetUserinfoEncryptedResponseEnc() string {
	if x != nil {
		return x.UserinfoEncryptedResponseEnc
	}
	return ""
}

func (x *ClientMeta) GetRequestObjectSigningAlg() string {
	if x != nil {
		return x.RequestObjectSigningAlg
	}
	return ""
}

func (x *ClientMeta) GetRequestObjectEncryptionAlg() string {
	if x != nil {
		return x.RequestObjectEncryptionAlg
	}
	return ""
}

func (x *ClientMeta) GetRequestObjectEncryptionEnc() string {
	if x != nil {
		return x.RequestObjectEncryptionEnc
	}
	return ""
}

func (x *ClientMeta) GetTokenEndpointAuthMethod() string {
	if x != nil {
		return x.TokenEndpointAuthMethod
	}
	return ""
}

func (x *ClientMeta) GetTokenEndpointAuthSigningAlg() string {
	if x != nil {
		return x.TokenEndpointAuthSigningAlg
	}
	return ""
}

func (x *ClientMeta) GetDefaultMaxAge() string {
	if x != nil {
		return x.DefaultMaxAge
	}
	return ""
}

func (x *ClientMeta) GetRequireAuthTime() bool {
	if x != nil {
		return x.RequireAuthTime
	}
	return false
}

func (x *ClientMeta) GetDefaultAcrValues() []string {
	if x != nil {
		return x.DefaultAcrValues
	}
	return nil
}

func (x *ClientMeta) GetInitiateLoginUri() string {
	if x != nil {
		return x.InitiateLoginUri
	}
	return ""
}

func (x *ClientMeta) GetRequestUris() []string {
	if x != nil {
		return x.RequestUris
	}
	return nil
}

func (x *ClientMeta) GetPostLogoutRedirectUris() []string {
	if x != nil {
		return x.PostLogoutRedirectUris
	}
	return nil
}

func (x *ClientMeta) GetRequirePushedAuthorizationRequests() bool {
	if x != nil {
		return x.RequirePushedAuthorizationRequests
	}
	return false
}

func (x *ClientMeta) GetAuthorizationSignedResponseAlg() string {
	if x != nil {
		return x.AuthorizationSignedResponseAlg
	}
	return ""
}

func (x *ClientMeta) GetAuthorizationEncryptedResponseAlg() string {
	if x != nil {
		return x.AuthorizationEncryptedResponseAlg
	}
	return ""
}

func (x *ClientMeta) GetAuthorizationEncryptedResponseEnc() string {
	if x != nil {
		return x.AuthorizationEncryptedResponseEnc
	}
	return ""
}

func (x *ClientMeta) GetTlsClientCertificateBoundAccessTokens() bool {
	if x != nil {
		return x.TlsClientCertificateBoundAccessTokens
	}
	return false
}

type ClientIdentity struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// https://openid.net/specs/openid-connect-registration-1_0.html#RegistrationResponse
	ClientId                string `protobuf:"bytes,1,opt,name=client_id,proto3" json:"client_id,omitempty"`
	ClientSecret            string `protobuf:"bytes,2,opt,name=client_secret,proto3" json:"client_secret,omitempty"`
	RegistrationAccessToken string `protobuf:"bytes,3,opt,name=registration_access_token,proto3" json:"registration_access_token,omitempty"`
	RegistrationClientUri   string `protobuf:"bytes,4,opt,name=registration_client_uri,proto3" json:"registration_client_uri,omitempty"`
	ClientIdIssuedAt        int32  `protobuf:"varint,5,opt,name=client_id_issued_at,proto3" json:"client_id_issued_at,omitempty"`
	ClientSecretExpiresAt   int32  `protobuf:"varint,6,opt,name=client_secret_expires_at,proto3" json:"client_secret_expires_at,omitempty"`
	unknownFields           protoimpl.UnknownFields
	sizeCache               protoimpl.SizeCache
}

func (x *ClientIdentity) Reset() {
	*x = ClientIdentity{}
	mi := &file_oppb_v1_client_meta_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClientIdentity) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClientIdentity) ProtoMessage() {}

func (x *ClientIdentity) ProtoReflect() protoreflect.Message {
	mi := &file_oppb_v1_client_meta_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClientIdentity.ProtoReflect.Descriptor instead.
func (*ClientIdentity) Descriptor() ([]byte, []int) {
	return file_oppb_v1_client_meta_proto_rawDescGZIP(), []int{1}
}

func (x *ClientIdentity) GetClientId() string {
	if x != nil {
		return x.ClientId
	}
	return ""
}

func (x *ClientIdentity) GetClientSecret() string {
	if x != nil {
		return x.ClientSecret
	}
	return ""
}

func (x *ClientIdentity) GetRegistrationAccessToken() string {
	if x != nil {
		return x.RegistrationAccessToken
	}
	return ""
}

func (x *ClientIdentity) GetRegistrationClientUri() string {
	if x != nil {
		return x.RegistrationClientUri
	}
	return ""
}

func (x *ClientIdentity) GetClientIdIssuedAt() int32 {
	if x != nil {
		return x.ClientIdIssuedAt
	}
	return 0
}

func (x *ClientIdentity) GetClientSecretExpiresAt() int32 {
	if x != nil {
		return x.ClientSecretExpiresAt
	}
	return 0
}

var File_oppb_v1_client_meta_proto protoreflect.FileDescriptor

const file_oppb_v1_client_meta_proto_rawDesc = "" +
	"\n" +
	"\x19oppb/v1/client_meta.proto\x12\aoppb.v1\x1a\x12oppb/v1/jwks.proto\"\xca\x0f\n" +
	"\n" +
	"ClientMeta\x12$\n" +
	"\rredirect_uris\x18e \x03(\tR\rredirect_uris\x12&\n" +
	"\x0eresponse_types\x18f \x03(\tR\x0eresponse_types\x12 \n" +
	"\vgrant_types\x18g \x03(\tR\vgrant_types\x12*\n" +
	"\x10application_type\x18h \x01(\tR\x10application_type\x12\x1a\n" +
	"\bcontacts\x18i \x03(\tR\bcontacts\x12 \n" +
	"\vclient_name\x18j \x01(\tR\vclient_name\x12\x1a\n" +
	"\blogo_uri\x18k \x01(\tR\blogo_uri\x12\x1e\n" +
	"\n" +
	"client_uri\x18l \x01(\tR\n" +
	"client_uri\x12\x1e\n" +
	"\n" +
	"policy_uri\x18m \x01(\tR\n" +
	"policy_uri\x12\x18\n" +
	"\atos_uri\x18n \x01(\tR\atos_uri\x12\x1a\n" +
	"\bjwks_uri\x18o \x01(\tR\bjwks_uri\x12!\n" +
	"\x04jwks\x18p \x01(\v2\r.oppb.v1.JwksR\x04jwks\x124\n" +
	"\x15sector_identifier_uri\x18q \x01(\tR\x15sector_identifier_uri\x12\"\n" +
	"\fsubject_type\x18r \x01(\tR\fsubject_type\x12B\n" +
	"\x1cid_token_signed_response_alg\x18s \x01(\tR\x1cid_token_signed_response_alg\x12H\n" +
	"\x1fid_token_encrypted_response_alg\x18t \x01(\tR\x1fid_token_encrypted_response_alg\x12H\n" +
	"\x1fid_token_encrypted_response_enc\x18u \x01(\tR\x1fid_token_encrypted_response_enc\x12B\n" +
	"\x1cuserinfo_signed_response_alg\x18v \x01(\tR\x1cuserinfo_signed_response_alg\x12H\n" +
	"\x1fuserinfo_encrypted_response_alg\x18w \x01(\tR\x1fuserinfo_encrypted_response_alg\x12H\n" +
	"\x1fuserinfo_encrypted_response_enc\x18x \x01(\tR\x1fuserinfo_encrypted_response_enc\x12>\n" +
	"\x1arequest_object_signing_alg\x18y \x01(\tR\x1arequest_object_signing_alg\x12D\n" +
	"\x1drequest_object_encryption_alg\x18z \x01(\tR\x1drequest_object_encryption_alg\x12D\n" +
	"\x1drequest_object_encryption_enc\x18{ \x01(\tR\x1drequest_object_encryption_enc\x12>\n" +
	"\x1atoken_endpoint_auth_method\x18| \x01(\tR\x1atoken_endpoint_auth_method\x12H\n" +
	"\x1ftoken_endpoint_auth_signing_alg\x18} \x01(\tR\x1ftoken_endpoint_auth_signing_alg\x12(\n" +
	"\x0fdefault_max_age\x18~ \x01(\tR\x0fdefault_max_age\x12,\n" +
	"\x11require_auth_time\x18\x7f \x01(\bR\x11require_auth_time\x12/\n" +
	"\x12default_acr_values\x18\x80\x01 \x03(\tR\x12default_acr_values\x12/\n" +
	"\x12initiate_login_uri\x18\x81\x01 \x01(\tR\x12initiate_login_uri\x12#\n" +
	"\frequest_uris\x18\x82\x01 \x03(\tR\frequest_uris\x12=\n" +
	"\x19post_logout_redirect_uris\x18\x83\x01 \x03(\tR\x19post_logout_redirect_uris\x12U\n" +
	"%require_pushed_authorization_requests\x18\x84\x01 \x01(\bR%require_pushed_authorization_requests\x12M\n" +
	"!authorization_signed_response_alg\x18\x85\x01 \x01(\tR!authorization_signed_response_alg\x12S\n" +
	"$authorization_encrypted_response_alg\x18\x86\x01 \x01(\tR$authorization_encrypted_response_alg\x12S\n" +
	"$authorization_encrypted_response_enc\x18\x87\x01 \x01(\tR$authorization_encrypted_response_enc\x12_\n" +
	"*tls_client_certificate_bound_access_tokens\x18\x88\x01 \x01(\bR*tls_client_certificate_bound_access_tokens\"\xba\x02\n" +
	"\x0eClientIdentity\x12\x1c\n" +
	"\tclient_id\x18\x01 \x01(\tR\tclient_id\x12$\n" +
	"\rclient_secret\x18\x02 \x01(\tR\rclient_secret\x12<\n" +
	"\x19registration_access_token\x18\x03 \x01(\tR\x19registration_access_token\x128\n" +
	"\x17registration_client_uri\x18\x04 \x01(\tR\x17registration_client_uri\x120\n" +
	"\x13client_id_issued_at\x18\x05 \x01(\x05R\x13client_id_issued_at\x12:\n" +
	"\x18client_secret_expires_at\x18\x06 \x01(\x05R\x18client_secret_expires_atB\x95\x01\n" +
	"\vcom.oppb.v1B\x0fClientMetaProtoP\x01Z8github.com/Eigen438/opgo/pkg/auto-generated/oppb/v1;oppb\xa2\x02\x03OXX\xaa\x02\aOppb.V1\xca\x02\aOppb\\V1\xe2\x02\x13Oppb\\V1\\GPBMetadata\xea\x02\bOppb::V1b\x06proto3"

var (
	file_oppb_v1_client_meta_proto_rawDescOnce sync.Once
	file_oppb_v1_client_meta_proto_rawDescData []byte
)

func file_oppb_v1_client_meta_proto_rawDescGZIP() []byte {
	file_oppb_v1_client_meta_proto_rawDescOnce.Do(func() {
		file_oppb_v1_client_meta_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_oppb_v1_client_meta_proto_rawDesc), len(file_oppb_v1_client_meta_proto_rawDesc)))
	})
	return file_oppb_v1_client_meta_proto_rawDescData
}

var file_oppb_v1_client_meta_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_oppb_v1_client_meta_proto_goTypes = []any{
	(*ClientMeta)(nil),     // 0: oppb.v1.ClientMeta
	(*ClientIdentity)(nil), // 1: oppb.v1.ClientIdentity
	(*Jwks)(nil),           // 2: oppb.v1.Jwks
}
var file_oppb_v1_client_meta_proto_depIdxs = []int32{
	2, // 0: oppb.v1.ClientMeta.jwks:type_name -> oppb.v1.Jwks
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_oppb_v1_client_meta_proto_init() }
func file_oppb_v1_client_meta_proto_init() {
	if File_oppb_v1_client_meta_proto != nil {
		return
	}
	file_oppb_v1_jwks_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_oppb_v1_client_meta_proto_rawDesc), len(file_oppb_v1_client_meta_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_oppb_v1_client_meta_proto_goTypes,
		DependencyIndexes: file_oppb_v1_client_meta_proto_depIdxs,
		MessageInfos:      file_oppb_v1_client_meta_proto_msgTypes,
	}.Build()
	File_oppb_v1_client_meta_proto = out.File
	file_oppb_v1_client_meta_proto_goTypes = nil
	file_oppb_v1_client_meta_proto_depIdxs = nil
}
