// MIT License
//
// Copyright (c) 2025 Eigen
//
// Permission is hereby granted, free of charge, to any person obtaining a copy
// of this software and associated documentation files (the "Software"), to deal
// in the Software without restriction, including without limitation the rights
// to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
// copies of the Software, and to permit persons to whom the Software is
// furnished to do so, subject to the following conditions:
//
// The above copyright notice and this permission notice shall be included in all
// copies or substantial portions of the Software.
//
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
// IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
// FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
// AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
// LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
// OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
// SOFTWARE.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        (unknown)
// source: oppb/v1/jwks.proto

package oppb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Jwks struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Keys          []*Jwk                 `protobuf:"bytes,1,rep,name=keys,proto3" json:"keys,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Jwks) Reset() {
	*x = Jwks{}
	mi := &file_oppb_v1_jwks_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Jwks) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Jwks) ProtoMessage() {}

func (x *Jwks) ProtoReflect() protoreflect.Message {
	mi := &file_oppb_v1_jwks_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Jwks.ProtoReflect.Descriptor instead.
func (*Jwks) Descriptor() ([]byte, []int) {
	return file_oppb_v1_jwks_proto_rawDescGZIP(), []int{0}
}

func (x *Jwks) GetKeys() []*Jwk {
	if x != nil {
		return x.Keys
	}
	return nil
}

type Jwk struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Kty           string                 `protobuf:"bytes,1,opt,name=kty,proto3" json:"kty,omitempty"`                        // https://www.rfc-editor.org/rfc/rfc7517#section-4.1 and https://www.rfc-editor.org/rfc/rfc7518#section-6.1 and https://www.rfc-editor.org/rfc/rfc8037.html#section-2
	Use           string                 `protobuf:"bytes,2,opt,name=use,proto3" json:"use,omitempty"`                        // https://www.rfc-editor.org/rfc/rfc7517#section-4.2
	KeyOps        []string               `protobuf:"bytes,3,rep,name=key_ops,proto3" json:"key_ops,omitempty"`                // https://www.rfc-editor.org/rfc/rfc7517#section-4.3
	Alg           string                 `protobuf:"bytes,4,opt,name=alg,proto3" json:"alg,omitempty"`                        // https://www.rfc-editor.org/rfc/rfc7517#section-4.4 and https://www.rfc-editor.org/rfc/rfc7518#section-4.1
	Kid           string                 `protobuf:"bytes,5,opt,name=kid,proto3" json:"kid,omitempty"`                        // https://www.rfc-editor.org/rfc/rfc7517#section-4.5
	X5U           string                 `protobuf:"bytes,6,opt,name=x5u,proto3" json:"x5u,omitempty"`                        // https://www.rfc-editor.org/rfc/rfc7517#section-4.6
	X5C           []string               `protobuf:"bytes,7,rep,name=x5c,proto3" json:"x5c,omitempty"`                        // https://www.rfc-editor.org/rfc/rfc7517#section-4.7
	X5T           string                 `protobuf:"bytes,8,opt,name=x5t,proto3" json:"x5t,omitempty"`                        // https://www.rfc-editor.org/rfc/rfc7517#section-4.8
	X5TS256       string                 `protobuf:"bytes,9,opt,name=x5t_s256,json=x5t#256,proto3" json:"x5t_s256,omitempty"` // https://www.rfc-editor.org/rfc/rfc7517#section-4.9
	Crv           string                 `protobuf:"bytes,10,opt,name=crv,proto3" json:"crv,omitempty"`                       // https://www.rfc-editor.org/rfc/rfc7518#section-6.2.1.1 and https://www.rfc-editor.org/rfc/rfc8037.html#section-2
	X             string                 `protobuf:"bytes,11,opt,name=x,proto3" json:"x,omitempty"`                           // https://www.rfc-editor.org/rfc/rfc7518#section-6.2.1.2 and https://www.rfc-editor.org/rfc/rfc8037.html#section-2
	Y             string                 `protobuf:"bytes,12,opt,name=y,proto3" json:"y,omitempty"`                           // https://www.rfc-editor.org/rfc/rfc7518#section-6.2.1.3
	D             string                 `protobuf:"bytes,13,opt,name=d,proto3" json:"d,omitempty"`                           // https://www.rfc-editor.org/rfc/rfc7518#section-6.2.2.1 and https://www.rfc-editor.org/rfc/rfc7518#section-6.3.2.1 and https://www.rfc-editor.org/rfc/rfc8037.html#section-2
	N             string                 `protobuf:"bytes,14,opt,name=n,proto3" json:"n,omitempty"`                           // https://www.rfc-editor.org/rfc/rfc7518#section-6.3.1.1
	E             string                 `protobuf:"bytes,15,opt,name=e,proto3" json:"e,omitempty"`                           // https://www.rfc-editor.org/rfc/rfc7518#section-6.3.1.2
	P             string                 `protobuf:"bytes,16,opt,name=p,proto3" json:"p,omitempty"`                           // https://www.rfc-editor.org/rfc/rfc7518#section-6.3.2.2
	Q             string                 `protobuf:"bytes,17,opt,name=q,proto3" json:"q,omitempty"`                           // https://www.rfc-editor.org/rfc/rfc7518#section-6.3.2.3
	Dp            string                 `protobuf:"bytes,18,opt,name=dp,proto3" json:"dp,omitempty"`                         // https://www.rfc-editor.org/rfc/rfc7518#section-6.3.2.4
	Dq            string                 `protobuf:"bytes,19,opt,name=dq,proto3" json:"dq,omitempty"`                         // https://www.rfc-editor.org/rfc/rfc7518#section-6.3.2.5
	Qi            string                 `protobuf:"bytes,20,opt,name=qi,proto3" json:"qi,omitempty"`                         // https://www.rfc-editor.org/rfc/rfc7518#section-6.3.2.6
	Oth           []*JwkOtherPrime       `protobuf:"bytes,21,rep,name=oth,proto3" json:"oth,omitempty"`                       // https://www.rfc-editor.org/rfc/rfc7518#section-6.3.2.7
	K             string                 `protobuf:"bytes,22,opt,name=k,proto3" json:"k,omitempty"`                           // https://www.rfc-editor.org/rfc/rfc7518#section-6.4.1
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Jwk) Reset() {
	*x = Jwk{}
	mi := &file_oppb_v1_jwks_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Jwk) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Jwk) ProtoMessage() {}

func (x *Jwk) ProtoReflect() protoreflect.Message {
	mi := &file_oppb_v1_jwks_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Jwk.ProtoReflect.Descriptor instead.
func (*Jwk) Descriptor() ([]byte, []int) {
	return file_oppb_v1_jwks_proto_rawDescGZIP(), []int{1}
}

func (x *Jwk) GetKty() string {
	if x != nil {
		return x.Kty
	}
	return ""
}

func (x *Jwk) GetUse() string {
	if x != nil {
		return x.Use
	}
	return ""
}

func (x *Jwk) GetKeyOps() []string {
	if x != nil {
		return x.KeyOps
	}
	return nil
}

func (x *Jwk) GetAlg() string {
	if x != nil {
		return x.Alg
	}
	return ""
}

func (x *Jwk) GetKid() string {
	if x != nil {
		return x.Kid
	}
	return ""
}

func (x *Jwk) GetX5U() string {
	if x != nil {
		return x.X5U
	}
	return ""
}

func (x *Jwk) GetX5C() []string {
	if x != nil {
		return x.X5C
	}
	return nil
}

func (x *Jwk) GetX5T() string {
	if x != nil {
		return x.X5T
	}
	return ""
}

func (x *Jwk) GetX5TS256() string {
	if x != nil {
		return x.X5TS256
	}
	return ""
}

func (x *Jwk) GetCrv() string {
	if x != nil {
		return x.Crv
	}
	return ""
}

func (x *Jwk) GetX() string {
	if x != nil {
		return x.X
	}
	return ""
}

func (x *Jwk) GetY() string {
	if x != nil {
		return x.Y
	}
	return ""
}

func (x *Jwk) GetD() string {
	if x != nil {
		return x.D
	}
	return ""
}

func (x *Jwk) GetN() string {
	if x != nil {
		return x.N
	}
	return ""
}

func (x *Jwk) GetE() string {
	if x != nil {
		return x.E
	}
	return ""
}

func (x *Jwk) GetP() string {
	if x != nil {
		return x.P
	}
	return ""
}

func (x *Jwk) GetQ() string {
	if x != nil {
		return x.Q
	}
	return ""
}

func (x *Jwk) GetDp() string {
	if x != nil {
		return x.Dp
	}
	return ""
}

func (x *Jwk) GetDq() string {
	if x != nil {
		return x.Dq
	}
	return ""
}

func (x *Jwk) GetQi() string {
	if x != nil {
		return x.Qi
	}
	return ""
}

func (x *Jwk) GetOth() []*JwkOtherPrime {
	if x != nil {
		return x.Oth
	}
	return nil
}

func (x *Jwk) GetK() string {
	if x != nil {
		return x.K
	}
	return ""
}

type JwkOtherPrime struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	R             string                 `protobuf:"bytes,1,opt,name=r,proto3" json:"r,omitempty"` // https://www.rfc-editor.org/rfc/rfc7518#section-6.3.2.7.1
	D             string                 `protobuf:"bytes,2,opt,name=d,proto3" json:"d,omitempty"` // https://www.rfc-editor.org/rfc/rfc7518#section-6.3.2.7.2
	T             string                 `protobuf:"bytes,3,opt,name=t,proto3" json:"t,omitempty"` // https://www.rfc-editor.org/rfc/rfc7518#section-6.3.2.7.3
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *JwkOtherPrime) Reset() {
	*x = JwkOtherPrime{}
	mi := &file_oppb_v1_jwks_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JwkOtherPrime) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JwkOtherPrime) ProtoMessage() {}

func (x *JwkOtherPrime) ProtoReflect() protoreflect.Message {
	mi := &file_oppb_v1_jwks_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JwkOtherPrime.ProtoReflect.Descriptor instead.
func (*JwkOtherPrime) Descriptor() ([]byte, []int) {
	return file_oppb_v1_jwks_proto_rawDescGZIP(), []int{2}
}

func (x *JwkOtherPrime) GetR() string {
	if x != nil {
		return x.R
	}
	return ""
}

func (x *JwkOtherPrime) GetD() string {
	if x != nil {
		return x.D
	}
	return ""
}

func (x *JwkOtherPrime) GetT() string {
	if x != nil {
		return x.T
	}
	return ""
}

var File_oppb_v1_jwks_proto protoreflect.FileDescriptor

const file_oppb_v1_jwks_proto_rawDesc = "" +
	"\n" +
	"\x12oppb/v1/jwks.proto\x12\aoppb.v1\"(\n" +
	"\x04Jwks\x12 \n" +
	"\x04keys\x18\x01 \x03(\v2\f.oppb.v1.JwkR\x04keys\"\x94\x03\n" +
	"\x03Jwk\x12\x10\n" +
	"\x03kty\x18\x01 \x01(\tR\x03kty\x12\x10\n" +
	"\x03use\x18\x02 \x01(\tR\x03use\x12\x18\n" +
	"\akey_ops\x18\x03 \x03(\tR\akey_ops\x12\x10\n" +
	"\x03alg\x18\x04 \x01(\tR\x03alg\x12\x10\n" +
	"\x03kid\x18\x05 \x01(\tR\x03kid\x12\x10\n" +
	"\x03x5u\x18\x06 \x01(\tR\x03x5u\x12\x10\n" +
	"\x03x5c\x18\a \x03(\tR\x03x5c\x12\x10\n" +
	"\x03x5t\x18\b \x01(\tR\x03x5t\x12\x19\n" +
	"\bx5t_s256\x18\t \x01(\tR\ax5t#256\x12\x10\n" +
	"\x03crv\x18\n" +
	" \x01(\tR\x03crv\x12\f\n" +
	"\x01x\x18\v \x01(\tR\x01x\x12\f\n" +
	"\x01y\x18\f \x01(\tR\x01y\x12\f\n" +
	"\x01d\x18\r \x01(\tR\x01d\x12\f\n" +
	"\x01n\x18\x0e \x01(\tR\x01n\x12\f\n" +
	"\x01e\x18\x0f \x01(\tR\x01e\x12\f\n" +
	"\x01p\x18\x10 \x01(\tR\x01p\x12\f\n" +
	"\x01q\x18\x11 \x01(\tR\x01q\x12\x0e\n" +
	"\x02dp\x18\x12 \x01(\tR\x02dp\x12\x0e\n" +
	"\x02dq\x18\x13 \x01(\tR\x02dq\x12\x0e\n" +
	"\x02qi\x18\x14 \x01(\tR\x02qi\x12(\n" +
	"\x03oth\x18\x15 \x03(\v2\x16.oppb.v1.JwkOtherPrimeR\x03oth\x12\f\n" +
	"\x01k\x18\x16 \x01(\tR\x01k\"9\n" +
	"\rJwkOtherPrime\x12\f\n" +
	"\x01r\x18\x01 \x01(\tR\x01r\x12\f\n" +
	"\x01d\x18\x02 \x01(\tR\x01d\x12\f\n" +
	"\x01t\x18\x03 \x01(\tR\x01tB\x8f\x01\n" +
	"\vcom.oppb.v1B\tJwksProtoP\x01Z8github.com/Eigen438/opgo/pkg/auto-generated/oppb/v1;oppb\xa2\x02\x03OXX\xaa\x02\aOppb.V1\xca\x02\aOppb\\V1\xe2\x02\x13Oppb\\V1\\GPBMetadata\xea\x02\bOppb::V1b\x06proto3"

var (
	file_oppb_v1_jwks_proto_rawDescOnce sync.Once
	file_oppb_v1_jwks_proto_rawDescData []byte
)

func file_oppb_v1_jwks_proto_rawDescGZIP() []byte {
	file_oppb_v1_jwks_proto_rawDescOnce.Do(func() {
		file_oppb_v1_jwks_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_oppb_v1_jwks_proto_rawDesc), len(file_oppb_v1_jwks_proto_rawDesc)))
	})
	return file_oppb_v1_jwks_proto_rawDescData
}

var file_oppb_v1_jwks_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_oppb_v1_jwks_proto_goTypes = []any{
	(*Jwks)(nil),          // 0: oppb.v1.Jwks
	(*Jwk)(nil),           // 1: oppb.v1.Jwk
	(*JwkOtherPrime)(nil), // 2: oppb.v1.JwkOtherPrime
}
var file_oppb_v1_jwks_proto_depIdxs = []int32{
	1, // 0: oppb.v1.Jwks.keys:type_name -> oppb.v1.Jwk
	2, // 1: oppb.v1.Jwk.oth:type_name -> oppb.v1.JwkOtherPrime
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_oppb_v1_jwks_proto_init() }
func file_oppb_v1_jwks_proto_init() {
	if File_oppb_v1_jwks_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_oppb_v1_jwks_proto_rawDesc), len(file_oppb_v1_jwks_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_oppb_v1_jwks_proto_goTypes,
		DependencyIndexes: file_oppb_v1_jwks_proto_depIdxs,
		MessageInfos:      file_oppb_v1_jwks_proto_msgTypes,
	}.Build()
	File_oppb_v1_jwks_proto = out.File
	file_oppb_v1_jwks_proto_goTypes = nil
	file_oppb_v1_jwks_proto_depIdxs = nil
}
