// MIT License
//
// Copyright (c) 2025 Eigen
//
// Permission is hereby granted, free of charge, to any person obtaining a copy
// of this software and associated documentation files (the "Software"), to deal
// in the Software without restriction, including without limitation the rights
// to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
// copies of the Software, and to permit persons to whom the Software is
// furnished to do so, subject to the following conditions:
//
// The above copyright notice and this permission notice shall be included in all
// copies or substantial portions of the Software.
//
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
// IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
// FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
// AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
// LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
// OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
// SOFTWARE.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        (unknown)
// source: oppb/v1/provider_service.proto

package oppb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type DiscoveryRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DiscoveryRequest) Reset() {
	*x = DiscoveryRequest{}
	mi := &file_oppb_v1_provider_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DiscoveryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DiscoveryRequest) ProtoMessage() {}

func (x *DiscoveryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_oppb_v1_provider_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DiscoveryRequest.ProtoReflect.Descriptor instead.
func (*DiscoveryRequest) Descriptor() ([]byte, []int) {
	return file_oppb_v1_provider_service_proto_rawDescGZIP(), []int{0}
}

type DiscoveryResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Meta          *IssuerMeta            `protobuf:"bytes,1,opt,name=meta,proto3" json:"meta,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DiscoveryResponse) Reset() {
	*x = DiscoveryResponse{}
	mi := &file_oppb_v1_provider_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DiscoveryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DiscoveryResponse) ProtoMessage() {}

func (x *DiscoveryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_oppb_v1_provider_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DiscoveryResponse.ProtoReflect.Descriptor instead.
func (*DiscoveryResponse) Descriptor() ([]byte, []int) {
	return file_oppb_v1_provider_service_proto_rawDescGZIP(), []int{1}
}

func (x *DiscoveryResponse) GetMeta() *IssuerMeta {
	if x != nil {
		return x.Meta
	}
	return nil
}

type JwksRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *JwksRequest) Reset() {
	*x = JwksRequest{}
	mi := &file_oppb_v1_provider_service_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JwksRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JwksRequest) ProtoMessage() {}

func (x *JwksRequest) ProtoReflect() protoreflect.Message {
	mi := &file_oppb_v1_provider_service_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JwksRequest.ProtoReflect.Descriptor instead.
func (*JwksRequest) Descriptor() ([]byte, []int) {
	return file_oppb_v1_provider_service_proto_rawDescGZIP(), []int{2}
}

type JwksResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Keys          []*Jwk                 `protobuf:"bytes,1,rep,name=keys,proto3" json:"keys,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *JwksResponse) Reset() {
	*x = JwksResponse{}
	mi := &file_oppb_v1_provider_service_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JwksResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JwksResponse) ProtoMessage() {}

func (x *JwksResponse) ProtoReflect() protoreflect.Message {
	mi := &file_oppb_v1_provider_service_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JwksResponse.ProtoReflect.Descriptor instead.
func (*JwksResponse) Descriptor() ([]byte, []int) {
	return file_oppb_v1_provider_service_proto_rawDescGZIP(), []int{3}
}

func (x *JwksResponse) GetKeys() []*Jwk {
	if x != nil {
		return x.Keys
	}
	return nil
}

type AuthorizationRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Sessions      map[string]string      `protobuf:"bytes,1,rep,name=sessions,proto3" json:"sessions,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	ContentType   string                 `protobuf:"bytes,2,opt,name=content_type,json=contentType,proto3" json:"content_type,omitempty"`
	Method        string                 `protobuf:"bytes,3,opt,name=method,proto3" json:"method,omitempty"`
	Url           string                 `protobuf:"bytes,4,opt,name=url,proto3" json:"url,omitempty"`
	Form          string                 `protobuf:"bytes,5,opt,name=form,proto3" json:"form,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AuthorizationRequest) Reset() {
	*x = AuthorizationRequest{}
	mi := &file_oppb_v1_provider_service_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuthorizationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuthorizationRequest) ProtoMessage() {}

func (x *AuthorizationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_oppb_v1_provider_service_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuthorizationRequest.ProtoReflect.Descriptor instead.
func (*AuthorizationRequest) Descriptor() ([]byte, []int) {
	return file_oppb_v1_provider_service_proto_rawDescGZIP(), []int{4}
}

func (x *AuthorizationRequest) GetSessions() map[string]string {
	if x != nil {
		return x.Sessions
	}
	return nil
}

func (x *AuthorizationRequest) GetContentType() string {
	if x != nil {
		return x.ContentType
	}
	return ""
}

func (x *AuthorizationRequest) GetMethod() string {
	if x != nil {
		return x.Method
	}
	return ""
}

func (x *AuthorizationRequest) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *AuthorizationRequest) GetForm() string {
	if x != nil {
		return x.Form
	}
	return ""
}

type AuthorizationResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to AuthorizationResponseOneof:
	//
	//	*AuthorizationResponse_Fail
	//	*AuthorizationResponse_Login
	//	*AuthorizationResponse_Issue
	//	*AuthorizationResponse_Redirect
	//	*AuthorizationResponse_Html
	AuthorizationResponseOneof isAuthorizationResponse_AuthorizationResponseOneof `protobuf_oneof:"authorization_response_oneof"`
	Params                     *AuthorizationParameters                           `protobuf:"bytes,10,opt,name=params,proto3" json:"params,omitempty"`
	Client                     *ClientMeta                                        `protobuf:"bytes,11,opt,name=client,proto3" json:"client,omitempty"`
	ClientAttribute            *ClientAttribute                                   `protobuf:"bytes,12,opt,name=client_attribute,json=clientAttribute,proto3" json:"client_attribute,omitempty"`
	unknownFields              protoimpl.UnknownFields
	sizeCache                  protoimpl.SizeCache
}

func (x *AuthorizationResponse) Reset() {
	*x = AuthorizationResponse{}
	mi := &file_oppb_v1_provider_service_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuthorizationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuthorizationResponse) ProtoMessage() {}

func (x *AuthorizationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_oppb_v1_provider_service_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuthorizationResponse.ProtoReflect.Descriptor instead.
func (*AuthorizationResponse) Descriptor() ([]byte, []int) {
	return file_oppb_v1_provider_service_proto_rawDescGZIP(), []int{5}
}

func (x *AuthorizationResponse) GetAuthorizationResponseOneof() isAuthorizationResponse_AuthorizationResponseOneof {
	if x != nil {
		return x.AuthorizationResponseOneof
	}
	return nil
}

func (x *AuthorizationResponse) GetFail() *AuthorizationFailResponse {
	if x != nil {
		if x, ok := x.AuthorizationResponseOneof.(*AuthorizationResponse_Fail); ok {
			return x.Fail
		}
	}
	return nil
}

func (x *AuthorizationResponse) GetLogin() *AuthorizationNextActionLogin {
	if x != nil {
		if x, ok := x.AuthorizationResponseOneof.(*AuthorizationResponse_Login); ok {
			return x.Login
		}
	}
	return nil
}

func (x *AuthorizationResponse) GetIssue() *AuthorizationNextActionIssue {
	if x != nil {
		if x, ok := x.AuthorizationResponseOneof.(*AuthorizationResponse_Issue); ok {
			return x.Issue
		}
	}
	return nil
}

func (x *AuthorizationResponse) GetRedirect() *AuthorizationRedirectResponse {
	if x != nil {
		if x, ok := x.AuthorizationResponseOneof.(*AuthorizationResponse_Redirect); ok {
			return x.Redirect
		}
	}
	return nil
}

func (x *AuthorizationResponse) GetHtml() *AuthorizationHtmlResponse {
	if x != nil {
		if x, ok := x.AuthorizationResponseOneof.(*AuthorizationResponse_Html); ok {
			return x.Html
		}
	}
	return nil
}

func (x *AuthorizationResponse) GetParams() *AuthorizationParameters {
	if x != nil {
		return x.Params
	}
	return nil
}

func (x *AuthorizationResponse) GetClient() *ClientMeta {
	if x != nil {
		return x.Client
	}
	return nil
}

func (x *AuthorizationResponse) GetClientAttribute() *ClientAttribute {
	if x != nil {
		return x.ClientAttribute
	}
	return nil
}

type isAuthorizationResponse_AuthorizationResponseOneof interface {
	isAuthorizationResponse_AuthorizationResponseOneof()
}

type AuthorizationResponse_Fail struct {
	Fail *AuthorizationFailResponse `protobuf:"bytes,1,opt,name=fail,proto3,oneof"`
}

type AuthorizationResponse_Login struct {
	Login *AuthorizationNextActionLogin `protobuf:"bytes,2,opt,name=login,proto3,oneof"`
}

type AuthorizationResponse_Issue struct {
	Issue *AuthorizationNextActionIssue `protobuf:"bytes,3,opt,name=issue,proto3,oneof"`
}

type AuthorizationResponse_Redirect struct {
	Redirect *AuthorizationRedirectResponse `protobuf:"bytes,4,opt,name=redirect,proto3,oneof"`
}

type AuthorizationResponse_Html struct {
	Html *AuthorizationHtmlResponse `protobuf:"bytes,5,opt,name=html,proto3,oneof"`
}

func (*AuthorizationResponse_Fail) isAuthorizationResponse_AuthorizationResponseOneof() {}

func (*AuthorizationResponse_Login) isAuthorizationResponse_AuthorizationResponseOneof() {}

func (*AuthorizationResponse_Issue) isAuthorizationResponse_AuthorizationResponseOneof() {}

func (*AuthorizationResponse_Redirect) isAuthorizationResponse_AuthorizationResponseOneof() {}

func (*AuthorizationResponse_Html) isAuthorizationResponse_AuthorizationResponseOneof() {}

type AuthorizationIssueRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RequestId     string                 `protobuf:"bytes,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	SessionId     string                 `protobuf:"bytes,2,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	Subject       string                 `protobuf:"bytes,3,opt,name=subject,proto3" json:"subject,omitempty"`
	Claims        string                 `protobuf:"bytes,4,opt,name=claims,proto3" json:"claims,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AuthorizationIssueRequest) Reset() {
	*x = AuthorizationIssueRequest{}
	mi := &file_oppb_v1_provider_service_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuthorizationIssueRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuthorizationIssueRequest) ProtoMessage() {}

func (x *AuthorizationIssueRequest) ProtoReflect() protoreflect.Message {
	mi := &file_oppb_v1_provider_service_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuthorizationIssueRequest.ProtoReflect.Descriptor instead.
func (*AuthorizationIssueRequest) Descriptor() ([]byte, []int) {
	return file_oppb_v1_provider_service_proto_rawDescGZIP(), []int{6}
}

func (x *AuthorizationIssueRequest) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *AuthorizationIssueRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *AuthorizationIssueRequest) GetSubject() string {
	if x != nil {
		return x.Subject
	}
	return ""
}

func (x *AuthorizationIssueRequest) GetClaims() string {
	if x != nil {
		return x.Claims
	}
	return ""
}

type AuthorizationIssueResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to AuthorizationIssueResponseOneof:
	//
	//	*AuthorizationIssueResponse_Redirect
	//	*AuthorizationIssueResponse_Html
	AuthorizationIssueResponseOneof isAuthorizationIssueResponse_AuthorizationIssueResponseOneof `protobuf_oneof:"authorization_issue_response_oneof"`
	unknownFields                   protoimpl.UnknownFields
	sizeCache                       protoimpl.SizeCache
}

func (x *AuthorizationIssueResponse) Reset() {
	*x = AuthorizationIssueResponse{}
	mi := &file_oppb_v1_provider_service_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuthorizationIssueResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuthorizationIssueResponse) ProtoMessage() {}

func (x *AuthorizationIssueResponse) ProtoReflect() protoreflect.Message {
	mi := &file_oppb_v1_provider_service_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuthorizationIssueResponse.ProtoReflect.Descriptor instead.
func (*AuthorizationIssueResponse) Descriptor() ([]byte, []int) {
	return file_oppb_v1_provider_service_proto_rawDescGZIP(), []int{7}
}

func (x *AuthorizationIssueResponse) GetAuthorizationIssueResponseOneof() isAuthorizationIssueResponse_AuthorizationIssueResponseOneof {
	if x != nil {
		return x.AuthorizationIssueResponseOneof
	}
	return nil
}

func (x *AuthorizationIssueResponse) GetRedirect() *AuthorizationRedirectResponse {
	if x != nil {
		if x, ok := x.AuthorizationIssueResponseOneof.(*AuthorizationIssueResponse_Redirect); ok {
			return x.Redirect
		}
	}
	return nil
}

func (x *AuthorizationIssueResponse) GetHtml() *AuthorizationHtmlResponse {
	if x != nil {
		if x, ok := x.AuthorizationIssueResponseOneof.(*AuthorizationIssueResponse_Html); ok {
			return x.Html
		}
	}
	return nil
}

type isAuthorizationIssueResponse_AuthorizationIssueResponseOneof interface {
	isAuthorizationIssueResponse_AuthorizationIssueResponseOneof()
}

type AuthorizationIssueResponse_Redirect struct {
	Redirect *AuthorizationRedirectResponse `protobuf:"bytes,1,opt,name=redirect,proto3,oneof"`
}

type AuthorizationIssueResponse_Html struct {
	Html *AuthorizationHtmlResponse `protobuf:"bytes,2,opt,name=html,proto3,oneof"`
}

func (*AuthorizationIssueResponse_Redirect) isAuthorizationIssueResponse_AuthorizationIssueResponseOneof() {
}

func (*AuthorizationIssueResponse_Html) isAuthorizationIssueResponse_AuthorizationIssueResponseOneof() {
}

type AuthorizationCancelRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RequestId     string                 `protobuf:"bytes,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AuthorizationCancelRequest) Reset() {
	*x = AuthorizationCancelRequest{}
	mi := &file_oppb_v1_provider_service_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuthorizationCancelRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuthorizationCancelRequest) ProtoMessage() {}

func (x *AuthorizationCancelRequest) ProtoReflect() protoreflect.Message {
	mi := &file_oppb_v1_provider_service_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuthorizationCancelRequest.ProtoReflect.Descriptor instead.
func (*AuthorizationCancelRequest) Descriptor() ([]byte, []int) {
	return file_oppb_v1_provider_service_proto_rawDescGZIP(), []int{8}
}

func (x *AuthorizationCancelRequest) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

type AuthorizationCancelResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to AuthorizationCancelResponseOneof:
	//
	//	*AuthorizationCancelResponse_Redirect
	//	*AuthorizationCancelResponse_Html
	AuthorizationCancelResponseOneof isAuthorizationCancelResponse_AuthorizationCancelResponseOneof `protobuf_oneof:"authorization_cancel_response_oneof"`
	unknownFields                    protoimpl.UnknownFields
	sizeCache                        protoimpl.SizeCache
}

func (x *AuthorizationCancelResponse) Reset() {
	*x = AuthorizationCancelResponse{}
	mi := &file_oppb_v1_provider_service_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuthorizationCancelResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuthorizationCancelResponse) ProtoMessage() {}

func (x *AuthorizationCancelResponse) ProtoReflect() protoreflect.Message {
	mi := &file_oppb_v1_provider_service_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuthorizationCancelResponse.ProtoReflect.Descriptor instead.
func (*AuthorizationCancelResponse) Descriptor() ([]byte, []int) {
	return file_oppb_v1_provider_service_proto_rawDescGZIP(), []int{9}
}

func (x *AuthorizationCancelResponse) GetAuthorizationCancelResponseOneof() isAuthorizationCancelResponse_AuthorizationCancelResponseOneof {
	if x != nil {
		return x.AuthorizationCancelResponseOneof
	}
	return nil
}

func (x *AuthorizationCancelResponse) GetRedirect() *AuthorizationRedirectResponse {
	if x != nil {
		if x, ok := x.AuthorizationCancelResponseOneof.(*AuthorizationCancelResponse_Redirect); ok {
			return x.Redirect
		}
	}
	return nil
}

func (x *AuthorizationCancelResponse) GetHtml() *AuthorizationHtmlResponse {
	if x != nil {
		if x, ok := x.AuthorizationCancelResponseOneof.(*AuthorizationCancelResponse_Html); ok {
			return x.Html
		}
	}
	return nil
}

type isAuthorizationCancelResponse_AuthorizationCancelResponseOneof interface {
	isAuthorizationCancelResponse_AuthorizationCancelResponseOneof()
}

type AuthorizationCancelResponse_Redirect struct {
	Redirect *AuthorizationRedirectResponse `protobuf:"bytes,1,opt,name=redirect,proto3,oneof"`
}

type AuthorizationCancelResponse_Html struct {
	Html *AuthorizationHtmlResponse `protobuf:"bytes,2,opt,name=html,proto3,oneof"`
}

func (*AuthorizationCancelResponse_Redirect) isAuthorizationCancelResponse_AuthorizationCancelResponseOneof() {
}

func (*AuthorizationCancelResponse_Html) isAuthorizationCancelResponse_AuthorizationCancelResponseOneof() {
}

type StartSessionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Subject       string                 `protobuf:"bytes,1,opt,name=subject,proto3" json:"subject,omitempty"`
	RequestId     string                 `protobuf:"bytes,2,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StartSessionRequest) Reset() {
	*x = StartSessionRequest{}
	mi := &file_oppb_v1_provider_service_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StartSessionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartSessionRequest) ProtoMessage() {}

func (x *StartSessionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_oppb_v1_provider_service_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartSessionRequest.ProtoReflect.Descriptor instead.
func (*StartSessionRequest) Descriptor() ([]byte, []int) {
	return file_oppb_v1_provider_service_proto_rawDescGZIP(), []int{10}
}

func (x *StartSessionRequest) GetSubject() string {
	if x != nil {
		return x.Subject
	}
	return ""
}

func (x *StartSessionRequest) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

type StartSessionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Value         string                 `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StartSessionResponse) Reset() {
	*x = StartSessionResponse{}
	mi := &file_oppb_v1_provider_service_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StartSessionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartSessionResponse) ProtoMessage() {}

func (x *StartSessionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_oppb_v1_provider_service_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartSessionResponse.ProtoReflect.Descriptor instead.
func (*StartSessionResponse) Descriptor() ([]byte, []int) {
	return file_oppb_v1_provider_service_proto_rawDescGZIP(), []int{11}
}

func (x *StartSessionResponse) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *StartSessionResponse) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

type TokenRequest struct {
	state                protoimpl.MessageState `protogen:"open.v1"`
	BasicAuth            *BasicAuth             `protobuf:"bytes,1,opt,name=basic_auth,json=basicAuth,proto3" json:"basic_auth,omitempty"`
	ContentType          string                 `protobuf:"bytes,2,opt,name=content_type,json=contentType,proto3" json:"content_type,omitempty"`
	Method               string                 `protobuf:"bytes,3,opt,name=method,proto3" json:"method,omitempty"`
	Form                 string                 `protobuf:"bytes,4,opt,name=form,proto3" json:"form,omitempty"`
	TlsClientCertificate string                 `protobuf:"bytes,5,opt,name=tls_client_certificate,json=tlsClientCertificate,proto3" json:"tls_client_certificate,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *TokenRequest) Reset() {
	*x = TokenRequest{}
	mi := &file_oppb_v1_provider_service_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TokenRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TokenRequest) ProtoMessage() {}

func (x *TokenRequest) ProtoReflect() protoreflect.Message {
	mi := &file_oppb_v1_provider_service_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TokenRequest.ProtoReflect.Descriptor instead.
func (*TokenRequest) Descriptor() ([]byte, []int) {
	return file_oppb_v1_provider_service_proto_rawDescGZIP(), []int{12}
}

func (x *TokenRequest) GetBasicAuth() *BasicAuth {
	if x != nil {
		return x.BasicAuth
	}
	return nil
}

func (x *TokenRequest) GetContentType() string {
	if x != nil {
		return x.ContentType
	}
	return ""
}

func (x *TokenRequest) GetMethod() string {
	if x != nil {
		return x.Method
	}
	return ""
}

func (x *TokenRequest) GetForm() string {
	if x != nil {
		return x.Form
	}
	return ""
}

func (x *TokenRequest) GetTlsClientCertificate() string {
	if x != nil {
		return x.TlsClientCertificate
	}
	return ""
}

type TokenResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to TokenResponseOneof:
	//
	//	*TokenResponse_Success
	//	*TokenResponse_Fail
	TokenResponseOneof isTokenResponse_TokenResponseOneof `protobuf_oneof:"token_response_oneof"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *TokenResponse) Reset() {
	*x = TokenResponse{}
	mi := &file_oppb_v1_provider_service_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TokenResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TokenResponse) ProtoMessage() {}

func (x *TokenResponse) ProtoReflect() protoreflect.Message {
	mi := &file_oppb_v1_provider_service_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TokenResponse.ProtoReflect.Descriptor instead.
func (*TokenResponse) Descriptor() ([]byte, []int) {
	return file_oppb_v1_provider_service_proto_rawDescGZIP(), []int{13}
}

func (x *TokenResponse) GetTokenResponseOneof() isTokenResponse_TokenResponseOneof {
	if x != nil {
		return x.TokenResponseOneof
	}
	return nil
}

func (x *TokenResponse) GetSuccess() *TokenSuccessResponse {
	if x != nil {
		if x, ok := x.TokenResponseOneof.(*TokenResponse_Success); ok {
			return x.Success
		}
	}
	return nil
}

func (x *TokenResponse) GetFail() *TokenFailResponse {
	if x != nil {
		if x, ok := x.TokenResponseOneof.(*TokenResponse_Fail); ok {
			return x.Fail
		}
	}
	return nil
}

type isTokenResponse_TokenResponseOneof interface {
	isTokenResponse_TokenResponseOneof()
}

type TokenResponse_Success struct {
	Success *TokenSuccessResponse `protobuf:"bytes,1,opt,name=success,proto3,oneof"`
}

type TokenResponse_Fail struct {
	Fail *TokenFailResponse `protobuf:"bytes,2,opt,name=fail,proto3,oneof"`
}

func (*TokenResponse_Success) isTokenResponse_TokenResponseOneof() {}

func (*TokenResponse_Fail) isTokenResponse_TokenResponseOneof() {}

type UserinfoRequest struct {
	state                protoimpl.MessageState `protogen:"open.v1"`
	Authorization        string                 `protobuf:"bytes,1,opt,name=authorization,proto3" json:"authorization,omitempty"`
	ContentType          string                 `protobuf:"bytes,2,opt,name=content_type,json=contentType,proto3" json:"content_type,omitempty"`
	Method               string                 `protobuf:"bytes,3,opt,name=method,proto3" json:"method,omitempty"`
	Form                 string                 `protobuf:"bytes,4,opt,name=form,proto3" json:"form,omitempty"`
	TlsClientCertificate string                 `protobuf:"bytes,5,opt,name=tls_client_certificate,json=tlsClientCertificate,proto3" json:"tls_client_certificate,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *UserinfoRequest) Reset() {
	*x = UserinfoRequest{}
	mi := &file_oppb_v1_provider_service_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserinfoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserinfoRequest) ProtoMessage() {}

func (x *UserinfoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_oppb_v1_provider_service_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserinfoRequest.ProtoReflect.Descriptor instead.
func (*UserinfoRequest) Descriptor() ([]byte, []int) {
	return file_oppb_v1_provider_service_proto_rawDescGZIP(), []int{14}
}

func (x *UserinfoRequest) GetAuthorization() string {
	if x != nil {
		return x.Authorization
	}
	return ""
}

func (x *UserinfoRequest) GetContentType() string {
	if x != nil {
		return x.ContentType
	}
	return ""
}

func (x *UserinfoRequest) GetMethod() string {
	if x != nil {
		return x.Method
	}
	return ""
}

func (x *UserinfoRequest) GetForm() string {
	if x != nil {
		return x.Form
	}
	return ""
}

func (x *UserinfoRequest) GetTlsClientCertificate() string {
	if x != nil {
		return x.TlsClientCertificate
	}
	return ""
}

type UserinfoResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Headers       map[string]string      `protobuf:"bytes,1,rep,name=headers,proto3" json:"headers,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	StatusCode    int32                  `protobuf:"varint,2,opt,name=status_code,json=statusCode,proto3" json:"status_code,omitempty"`
	Body          string                 `protobuf:"bytes,3,opt,name=body,proto3" json:"body,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserinfoResponse) Reset() {
	*x = UserinfoResponse{}
	mi := &file_oppb_v1_provider_service_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserinfoResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserinfoResponse) ProtoMessage() {}

func (x *UserinfoResponse) ProtoReflect() protoreflect.Message {
	mi := &file_oppb_v1_provider_service_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserinfoResponse.ProtoReflect.Descriptor instead.
func (*UserinfoResponse) Descriptor() ([]byte, []int) {
	return file_oppb_v1_provider_service_proto_rawDescGZIP(), []int{15}
}

func (x *UserinfoResponse) GetHeaders() map[string]string {
	if x != nil {
		return x.Headers
	}
	return nil
}

func (x *UserinfoResponse) GetStatusCode() int32 {
	if x != nil {
		return x.StatusCode
	}
	return 0
}

func (x *UserinfoResponse) GetBody() string {
	if x != nil {
		return x.Body
	}
	return ""
}

type PushedAuthorizationRequest struct {
	state                protoimpl.MessageState `protogen:"open.v1"`
	BasicAuth            *BasicAuth             `protobuf:"bytes,1,opt,name=basic_auth,json=basicAuth,proto3" json:"basic_auth,omitempty"`
	ContentType          string                 `protobuf:"bytes,2,opt,name=content_type,json=contentType,proto3" json:"content_type,omitempty"`
	Method               string                 `protobuf:"bytes,3,opt,name=method,proto3" json:"method,omitempty"`
	Form                 string                 `protobuf:"bytes,4,opt,name=form,proto3" json:"form,omitempty"`
	TlsClientCertificate string                 `protobuf:"bytes,5,opt,name=tls_client_certificate,json=tlsClientCertificate,proto3" json:"tls_client_certificate,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *PushedAuthorizationRequest) Reset() {
	*x = PushedAuthorizationRequest{}
	mi := &file_oppb_v1_provider_service_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PushedAuthorizationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PushedAuthorizationRequest) ProtoMessage() {}

func (x *PushedAuthorizationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_oppb_v1_provider_service_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PushedAuthorizationRequest.ProtoReflect.Descriptor instead.
func (*PushedAuthorizationRequest) Descriptor() ([]byte, []int) {
	return file_oppb_v1_provider_service_proto_rawDescGZIP(), []int{16}
}

func (x *PushedAuthorizationRequest) GetBasicAuth() *BasicAuth {
	if x != nil {
		return x.BasicAuth
	}
	return nil
}

func (x *PushedAuthorizationRequest) GetContentType() string {
	if x != nil {
		return x.ContentType
	}
	return ""
}

func (x *PushedAuthorizationRequest) GetMethod() string {
	if x != nil {
		return x.Method
	}
	return ""
}

func (x *PushedAuthorizationRequest) GetForm() string {
	if x != nil {
		return x.Form
	}
	return ""
}

func (x *PushedAuthorizationRequest) GetTlsClientCertificate() string {
	if x != nil {
		return x.TlsClientCertificate
	}
	return ""
}

type PushedAuthorizationResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to PushedAuthorizationResponseOneof:
	//
	//	*PushedAuthorizationResponse_Success
	//	*PushedAuthorizationResponse_Fail
	PushedAuthorizationResponseOneof isPushedAuthorizationResponse_PushedAuthorizationResponseOneof `protobuf_oneof:"pushed_authorization_response_oneof"`
	unknownFields                    protoimpl.UnknownFields
	sizeCache                        protoimpl.SizeCache
}

func (x *PushedAuthorizationResponse) Reset() {
	*x = PushedAuthorizationResponse{}
	mi := &file_oppb_v1_provider_service_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PushedAuthorizationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PushedAuthorizationResponse) ProtoMessage() {}

func (x *PushedAuthorizationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_oppb_v1_provider_service_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PushedAuthorizationResponse.ProtoReflect.Descriptor instead.
func (*PushedAuthorizationResponse) Descriptor() ([]byte, []int) {
	return file_oppb_v1_provider_service_proto_rawDescGZIP(), []int{17}
}

func (x *PushedAuthorizationResponse) GetPushedAuthorizationResponseOneof() isPushedAuthorizationResponse_PushedAuthorizationResponseOneof {
	if x != nil {
		return x.PushedAuthorizationResponseOneof
	}
	return nil
}

func (x *PushedAuthorizationResponse) GetSuccess() *PushedAuthorizationSuccessResponse {
	if x != nil {
		if x, ok := x.PushedAuthorizationResponseOneof.(*PushedAuthorizationResponse_Success); ok {
			return x.Success
		}
	}
	return nil
}

func (x *PushedAuthorizationResponse) GetFail() *PushedAuthorizationFailResponse {
	if x != nil {
		if x, ok := x.PushedAuthorizationResponseOneof.(*PushedAuthorizationResponse_Fail); ok {
			return x.Fail
		}
	}
	return nil
}

type isPushedAuthorizationResponse_PushedAuthorizationResponseOneof interface {
	isPushedAuthorizationResponse_PushedAuthorizationResponseOneof()
}

type PushedAuthorizationResponse_Success struct {
	Success *PushedAuthorizationSuccessResponse `protobuf:"bytes,1,opt,name=success,proto3,oneof"`
}

type PushedAuthorizationResponse_Fail struct {
	Fail *PushedAuthorizationFailResponse `protobuf:"bytes,2,opt,name=fail,proto3,oneof"`
}

func (*PushedAuthorizationResponse_Success) isPushedAuthorizationResponse_PushedAuthorizationResponseOneof() {
}

func (*PushedAuthorizationResponse_Fail) isPushedAuthorizationResponse_PushedAuthorizationResponseOneof() {
}

type RequestRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RequestId     string                 `protobuf:"bytes,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RequestRequest) Reset() {
	*x = RequestRequest{}
	mi := &file_oppb_v1_provider_service_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RequestRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RequestRequest) ProtoMessage() {}

func (x *RequestRequest) ProtoReflect() protoreflect.Message {
	mi := &file_oppb_v1_provider_service_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RequestRequest.ProtoReflect.Descriptor instead.
func (*RequestRequest) Descriptor() ([]byte, []int) {
	return file_oppb_v1_provider_service_proto_rawDescGZIP(), []int{18}
}

func (x *RequestRequest) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

type RequestResponse struct {
	state         protoimpl.MessageState   `protogen:"open.v1"`
	Client        *ClientMeta              `protobuf:"bytes,1,opt,name=client,proto3" json:"client,omitempty"`
	AuthParams    *AuthorizationParameters `protobuf:"bytes,2,opt,name=auth_params,json=authParams,proto3" json:"auth_params,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RequestResponse) Reset() {
	*x = RequestResponse{}
	mi := &file_oppb_v1_provider_service_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RequestResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RequestResponse) ProtoMessage() {}

func (x *RequestResponse) ProtoReflect() protoreflect.Message {
	mi := &file_oppb_v1_provider_service_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RequestResponse.ProtoReflect.Descriptor instead.
func (*RequestResponse) Descriptor() ([]byte, []int) {
	return file_oppb_v1_provider_service_proto_rawDescGZIP(), []int{19}
}

func (x *RequestResponse) GetClient() *ClientMeta {
	if x != nil {
		return x.Client
	}
	return nil
}

func (x *RequestResponse) GetAuthParams() *AuthorizationParameters {
	if x != nil {
		return x.AuthParams
	}
	return nil
}

type AuthorizationFailResponse struct {
	state         protoimpl.MessageState      `protogen:"open.v1"`
	StatusCode    int32                       `protobuf:"varint,1,opt,name=status_code,json=statusCode,proto3" json:"status_code,omitempty"`
	Error         *AuthorizationErrorResponse `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AuthorizationFailResponse) Reset() {
	*x = AuthorizationFailResponse{}
	mi := &file_oppb_v1_provider_service_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuthorizationFailResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuthorizationFailResponse) ProtoMessage() {}

func (x *AuthorizationFailResponse) ProtoReflect() protoreflect.Message {
	mi := &file_oppb_v1_provider_service_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuthorizationFailResponse.ProtoReflect.Descriptor instead.
func (*AuthorizationFailResponse) Descriptor() ([]byte, []int) {
	return file_oppb_v1_provider_service_proto_rawDescGZIP(), []int{20}
}

func (x *AuthorizationFailResponse) GetStatusCode() int32 {
	if x != nil {
		return x.StatusCode
	}
	return 0
}

func (x *AuthorizationFailResponse) GetError() *AuthorizationErrorResponse {
	if x != nil {
		return x.Error
	}
	return nil
}

// https://openid.net/specs/openid-connect-core-1_0.html#AuthError
type AuthorizationErrorResponse struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Error            string                 `protobuf:"bytes,1,opt,name=error,proto3" json:"error,omitempty"`
	ErrorDescription string                 `protobuf:"bytes,2,opt,name=error_description,json=errorDescription,proto3" json:"error_description,omitempty"`
	ErrorUri         string                 `protobuf:"bytes,3,opt,name=error_uri,json=errorUri,proto3" json:"error_uri,omitempty"`
	State            string                 `protobuf:"bytes,4,opt,name=state,proto3" json:"state,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *AuthorizationErrorResponse) Reset() {
	*x = AuthorizationErrorResponse{}
	mi := &file_oppb_v1_provider_service_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuthorizationErrorResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuthorizationErrorResponse) ProtoMessage() {}

func (x *AuthorizationErrorResponse) ProtoReflect() protoreflect.Message {
	mi := &file_oppb_v1_provider_service_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuthorizationErrorResponse.ProtoReflect.Descriptor instead.
func (*AuthorizationErrorResponse) Descriptor() ([]byte, []int) {
	return file_oppb_v1_provider_service_proto_rawDescGZIP(), []int{21}
}

func (x *AuthorizationErrorResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *AuthorizationErrorResponse) GetErrorDescription() string {
	if x != nil {
		return x.ErrorDescription
	}
	return ""
}

func (x *AuthorizationErrorResponse) GetErrorUri() string {
	if x != nil {
		return x.ErrorUri
	}
	return ""
}

func (x *AuthorizationErrorResponse) GetState() string {
	if x != nil {
		return x.State
	}
	return ""
}

type AuthorizationNextActionLogin struct {
	state         protoimpl.MessageState   `protogen:"open.v1"`
	RequestId     string                   `protobuf:"bytes,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	Client        *ClientMeta              `protobuf:"bytes,2,opt,name=client,proto3" json:"client,omitempty"`
	AuthParams    *AuthorizationParameters `protobuf:"bytes,3,opt,name=auth_params,json=authParams,proto3" json:"auth_params,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AuthorizationNextActionLogin) Reset() {
	*x = AuthorizationNextActionLogin{}
	mi := &file_oppb_v1_provider_service_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuthorizationNextActionLogin) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuthorizationNextActionLogin) ProtoMessage() {}

func (x *AuthorizationNextActionLogin) ProtoReflect() protoreflect.Message {
	mi := &file_oppb_v1_provider_service_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuthorizationNextActionLogin.ProtoReflect.Descriptor instead.
func (*AuthorizationNextActionLogin) Descriptor() ([]byte, []int) {
	return file_oppb_v1_provider_service_proto_rawDescGZIP(), []int{22}
}

func (x *AuthorizationNextActionLogin) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *AuthorizationNextActionLogin) GetClient() *ClientMeta {
	if x != nil {
		return x.Client
	}
	return nil
}

func (x *AuthorizationNextActionLogin) GetAuthParams() *AuthorizationParameters {
	if x != nil {
		return x.AuthParams
	}
	return nil
}

type AuthorizationNextActionIssue struct {
	state         protoimpl.MessageState   `protogen:"open.v1"`
	RequestId     string                   `protobuf:"bytes,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	SessionId     string                   `protobuf:"bytes,2,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	Subject       string                   `protobuf:"bytes,3,opt,name=subject,proto3" json:"subject,omitempty"`
	Client        *ClientMeta              `protobuf:"bytes,4,opt,name=client,proto3" json:"client,omitempty"`
	AuthParams    *AuthorizationParameters `protobuf:"bytes,5,opt,name=auth_params,json=authParams,proto3" json:"auth_params,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AuthorizationNextActionIssue) Reset() {
	*x = AuthorizationNextActionIssue{}
	mi := &file_oppb_v1_provider_service_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuthorizationNextActionIssue) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuthorizationNextActionIssue) ProtoMessage() {}

func (x *AuthorizationNextActionIssue) ProtoReflect() protoreflect.Message {
	mi := &file_oppb_v1_provider_service_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuthorizationNextActionIssue.ProtoReflect.Descriptor instead.
func (*AuthorizationNextActionIssue) Descriptor() ([]byte, []int) {
	return file_oppb_v1_provider_service_proto_rawDescGZIP(), []int{23}
}

func (x *AuthorizationNextActionIssue) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *AuthorizationNextActionIssue) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *AuthorizationNextActionIssue) GetSubject() string {
	if x != nil {
		return x.Subject
	}
	return ""
}

func (x *AuthorizationNextActionIssue) GetClient() *ClientMeta {
	if x != nil {
		return x.Client
	}
	return nil
}

func (x *AuthorizationNextActionIssue) GetAuthParams() *AuthorizationParameters {
	if x != nil {
		return x.AuthParams
	}
	return nil
}

type AuthorizationRedirectResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Url           string                 `protobuf:"bytes,1,opt,name=url,proto3" json:"url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AuthorizationRedirectResponse) Reset() {
	*x = AuthorizationRedirectResponse{}
	mi := &file_oppb_v1_provider_service_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuthorizationRedirectResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuthorizationRedirectResponse) ProtoMessage() {}

func (x *AuthorizationRedirectResponse) ProtoReflect() protoreflect.Message {
	mi := &file_oppb_v1_provider_service_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuthorizationRedirectResponse.ProtoReflect.Descriptor instead.
func (*AuthorizationRedirectResponse) Descriptor() ([]byte, []int) {
	return file_oppb_v1_provider_service_proto_rawDescGZIP(), []int{24}
}

func (x *AuthorizationRedirectResponse) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

type AuthorizationHtmlResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Content       string                 `protobuf:"bytes,1,opt,name=content,proto3" json:"content,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AuthorizationHtmlResponse) Reset() {
	*x = AuthorizationHtmlResponse{}
	mi := &file_oppb_v1_provider_service_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuthorizationHtmlResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuthorizationHtmlResponse) ProtoMessage() {}

func (x *AuthorizationHtmlResponse) ProtoReflect() protoreflect.Message {
	mi := &file_oppb_v1_provider_service_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuthorizationHtmlResponse.ProtoReflect.Descriptor instead.
func (*AuthorizationHtmlResponse) Descriptor() ([]byte, []int) {
	return file_oppb_v1_provider_service_proto_rawDescGZIP(), []int{25}
}

func (x *AuthorizationHtmlResponse) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

type TokenSuccessResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// https://www.rfc-editor.org/rfc/rfc6749.html#section-5.1
	AccessToken  string `protobuf:"bytes,1,opt,name=access_token,proto3" json:"access_token,omitempty"`
	TokenType    string `protobuf:"bytes,2,opt,name=token_type,proto3" json:"token_type,omitempty"`
	ExpiresIn    int32  `protobuf:"varint,3,opt,name=expires_in,proto3" json:"expires_in,omitempty"`
	RefreshToken string `protobuf:"bytes,4,opt,name=refresh_token,proto3" json:"refresh_token,omitempty"`
	Scope        string `protobuf:"bytes,5,opt,name=scope,proto3" json:"scope,omitempty"`
	// https://openid.net/specs/openid-connect-core-1_0.html#TokenResponse
	IdToken       string `protobuf:"bytes,6,opt,name=id_token,proto3" json:"id_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TokenSuccessResponse) Reset() {
	*x = TokenSuccessResponse{}
	mi := &file_oppb_v1_provider_service_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TokenSuccessResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TokenSuccessResponse) ProtoMessage() {}

func (x *TokenSuccessResponse) ProtoReflect() protoreflect.Message {
	mi := &file_oppb_v1_provider_service_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TokenSuccessResponse.ProtoReflect.Descriptor instead.
func (*TokenSuccessResponse) Descriptor() ([]byte, []int) {
	return file_oppb_v1_provider_service_proto_rawDescGZIP(), []int{26}
}

func (x *TokenSuccessResponse) GetAccessToken() string {
	if x != nil {
		return x.AccessToken
	}
	return ""
}

func (x *TokenSuccessResponse) GetTokenType() string {
	if x != nil {
		return x.TokenType
	}
	return ""
}

func (x *TokenSuccessResponse) GetExpiresIn() int32 {
	if x != nil {
		return x.ExpiresIn
	}
	return 0
}

func (x *TokenSuccessResponse) GetRefreshToken() string {
	if x != nil {
		return x.RefreshToken
	}
	return ""
}

func (x *TokenSuccessResponse) GetScope() string {
	if x != nil {
		return x.Scope
	}
	return ""
}

func (x *TokenSuccessResponse) GetIdToken() string {
	if x != nil {
		return x.IdToken
	}
	return ""
}

type TokenFailResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StatusCode    int32                  `protobuf:"varint,1,opt,name=status_code,json=statusCode,proto3" json:"status_code,omitempty"`
	Error         *OauthError            `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TokenFailResponse) Reset() {
	*x = TokenFailResponse{}
	mi := &file_oppb_v1_provider_service_proto_msgTypes[27]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TokenFailResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TokenFailResponse) ProtoMessage() {}

func (x *TokenFailResponse) ProtoReflect() protoreflect.Message {
	mi := &file_oppb_v1_provider_service_proto_msgTypes[27]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TokenFailResponse.ProtoReflect.Descriptor instead.
func (*TokenFailResponse) Descriptor() ([]byte, []int) {
	return file_oppb_v1_provider_service_proto_rawDescGZIP(), []int{27}
}

func (x *TokenFailResponse) GetStatusCode() int32 {
	if x != nil {
		return x.StatusCode
	}
	return 0
}

func (x *TokenFailResponse) GetError() *OauthError {
	if x != nil {
		return x.Error
	}
	return nil
}

type PushedAuthorizationSuccessResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StatusCode    int32                  `protobuf:"varint,1,opt,name=status_code,json=statusCode,proto3" json:"status_code,omitempty"`
	RequestUri    string                 `protobuf:"bytes,2,opt,name=request_uri,json=requestUri,proto3" json:"request_uri,omitempty"`
	ExpiresIn     int32                  `protobuf:"varint,3,opt,name=expires_in,json=expiresIn,proto3" json:"expires_in,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PushedAuthorizationSuccessResponse) Reset() {
	*x = PushedAuthorizationSuccessResponse{}
	mi := &file_oppb_v1_provider_service_proto_msgTypes[28]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PushedAuthorizationSuccessResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PushedAuthorizationSuccessResponse) ProtoMessage() {}

func (x *PushedAuthorizationSuccessResponse) ProtoReflect() protoreflect.Message {
	mi := &file_oppb_v1_provider_service_proto_msgTypes[28]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PushedAuthorizationSuccessResponse.ProtoReflect.Descriptor instead.
func (*PushedAuthorizationSuccessResponse) Descriptor() ([]byte, []int) {
	return file_oppb_v1_provider_service_proto_rawDescGZIP(), []int{28}
}

func (x *PushedAuthorizationSuccessResponse) GetStatusCode() int32 {
	if x != nil {
		return x.StatusCode
	}
	return 0
}

func (x *PushedAuthorizationSuccessResponse) GetRequestUri() string {
	if x != nil {
		return x.RequestUri
	}
	return ""
}

func (x *PushedAuthorizationSuccessResponse) GetExpiresIn() int32 {
	if x != nil {
		return x.ExpiresIn
	}
	return 0
}

type PushedAuthorizationFailResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StatusCode    int32                  `protobuf:"varint,1,opt,name=status_code,json=statusCode,proto3" json:"status_code,omitempty"`
	Error         *OauthError            `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PushedAuthorizationFailResponse) Reset() {
	*x = PushedAuthorizationFailResponse{}
	mi := &file_oppb_v1_provider_service_proto_msgTypes[29]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PushedAuthorizationFailResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PushedAuthorizationFailResponse) ProtoMessage() {}

func (x *PushedAuthorizationFailResponse) ProtoReflect() protoreflect.Message {
	mi := &file_oppb_v1_provider_service_proto_msgTypes[29]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PushedAuthorizationFailResponse.ProtoReflect.Descriptor instead.
func (*PushedAuthorizationFailResponse) Descriptor() ([]byte, []int) {
	return file_oppb_v1_provider_service_proto_rawDescGZIP(), []int{29}
}

func (x *PushedAuthorizationFailResponse) GetStatusCode() int32 {
	if x != nil {
		return x.StatusCode
	}
	return 0
}

func (x *PushedAuthorizationFailResponse) GetError() *OauthError {
	if x != nil {
		return x.Error
	}
	return nil
}

type OauthError struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// https://www.rfc-editor.org/rfc/rfc6749.html#section-5.2
	Error            string `protobuf:"bytes,1,opt,name=error,proto3" json:"error,omitempty"`
	ErrorDescription string `protobuf:"bytes,2,opt,name=error_description,proto3" json:"error_description,omitempty"`
	ErrorUri         string `protobuf:"bytes,3,opt,name=error_uri,proto3" json:"error_uri,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *OauthError) Reset() {
	*x = OauthError{}
	mi := &file_oppb_v1_provider_service_proto_msgTypes[30]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OauthError) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OauthError) ProtoMessage() {}

func (x *OauthError) ProtoReflect() protoreflect.Message {
	mi := &file_oppb_v1_provider_service_proto_msgTypes[30]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OauthError.ProtoReflect.Descriptor instead.
func (*OauthError) Descriptor() ([]byte, []int) {
	return file_oppb_v1_provider_service_proto_rawDescGZIP(), []int{30}
}

func (x *OauthError) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *OauthError) GetErrorDescription() string {
	if x != nil {
		return x.ErrorDescription
	}
	return ""
}

func (x *OauthError) GetErrorUri() string {
	if x != nil {
		return x.ErrorUri
	}
	return ""
}

type BasicAuth struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Username      string                 `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	Password      string                 `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BasicAuth) Reset() {
	*x = BasicAuth{}
	mi := &file_oppb_v1_provider_service_proto_msgTypes[31]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BasicAuth) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BasicAuth) ProtoMessage() {}

func (x *BasicAuth) ProtoReflect() protoreflect.Message {
	mi := &file_oppb_v1_provider_service_proto_msgTypes[31]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BasicAuth.ProtoReflect.Descriptor instead.
func (*BasicAuth) Descriptor() ([]byte, []int) {
	return file_oppb_v1_provider_service_proto_rawDescGZIP(), []int{31}
}

func (x *BasicAuth) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *BasicAuth) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

var File_oppb_v1_provider_service_proto protoreflect.FileDescriptor

const file_oppb_v1_provider_service_proto_rawDesc = "" +
	"\n" +
	"\x1eoppb/v1/provider_service.proto\x12\aoppb.v1\x1a&oppb/v1/authorization_parameters.proto\x1a\x14oppb/v1/client.proto\x1a\x19oppb/v1/client_meta.proto\x1a\x19oppb/v1/issuer_meta.proto\x1a\x12oppb/v1/jwks.proto\x1a\x1aoppb/v1/registration.proto\"\x12\n" +
	"\x10DiscoveryRequest\"<\n" +
	"\x11DiscoveryResponse\x12'\n" +
	"\x04meta\x18\x01 \x01(\v2\x13.oppb.v1.IssuerMetaR\x04meta\"\r\n" +
	"\vJwksRequest\"0\n" +
	"\fJwksResponse\x12 \n" +
	"\x04keys\x18\x01 \x03(\v2\f.oppb.v1.JwkR\x04keys\"\xfd\x01\n" +
	"\x14AuthorizationRequest\x12G\n" +
	"\bsessions\x18\x01 \x03(\v2+.oppb.v1.AuthorizationRequest.SessionsEntryR\bsessions\x12!\n" +
	"\fcontent_type\x18\x02 \x01(\tR\vcontentType\x12\x16\n" +
	"\x06method\x18\x03 \x01(\tR\x06method\x12\x10\n" +
	"\x03url\x18\x04 \x01(\tR\x03url\x12\x12\n" +
	"\x04form\x18\x05 \x01(\tR\x04form\x1a;\n" +
	"\rSessionsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\x9b\x04\n" +
	"\x15AuthorizationResponse\x128\n" +
	"\x04fail\x18\x01 \x01(\v2\".oppb.v1.AuthorizationFailResponseH\x00R\x04fail\x12=\n" +
	"\x05login\x18\x02 \x01(\v2%.oppb.v1.AuthorizationNextActionLoginH\x00R\x05login\x12=\n" +
	"\x05issue\x18\x03 \x01(\v2%.oppb.v1.AuthorizationNextActionIssueH\x00R\x05issue\x12D\n" +
	"\bredirect\x18\x04 \x01(\v2&.oppb.v1.AuthorizationRedirectResponseH\x00R\bredirect\x128\n" +
	"\x04html\x18\x05 \x01(\v2\".oppb.v1.AuthorizationHtmlResponseH\x00R\x04html\x128\n" +
	"\x06params\x18\n" +
	" \x01(\v2 .oppb.v1.AuthorizationParametersR\x06params\x12+\n" +
	"\x06client\x18\v \x01(\v2\x13.oppb.v1.ClientMetaR\x06client\x12C\n" +
	"\x10client_attribute\x18\f \x01(\v2\x18.oppb.v1.ClientAttributeR\x0fclientAttributeB\x1e\n" +
	"\x1cauthorization_response_oneof\"\x8b\x01\n" +
	"\x19AuthorizationIssueRequest\x12\x1d\n" +
	"\n" +
	"request_id\x18\x01 \x01(\tR\trequestId\x12\x1d\n" +
	"\n" +
	"session_id\x18\x02 \x01(\tR\tsessionId\x12\x18\n" +
	"\asubject\x18\x03 \x01(\tR\asubject\x12\x16\n" +
	"\x06claims\x18\x04 \x01(\tR\x06claims\"\xc2\x01\n" +
	"\x1aAuthorizationIssueResponse\x12D\n" +
	"\bredirect\x18\x01 \x01(\v2&.oppb.v1.AuthorizationRedirectResponseH\x00R\bredirect\x128\n" +
	"\x04html\x18\x02 \x01(\v2\".oppb.v1.AuthorizationHtmlResponseH\x00R\x04htmlB$\n" +
	"\"authorization_issue_response_oneof\";\n" +
	"\x1aAuthorizationCancelRequest\x12\x1d\n" +
	"\n" +
	"request_id\x18\x01 \x01(\tR\trequestId\"\xc4\x01\n" +
	"\x1bAuthorizationCancelResponse\x12D\n" +
	"\bredirect\x18\x01 \x01(\v2&.oppb.v1.AuthorizationRedirectResponseH\x00R\bredirect\x128\n" +
	"\x04html\x18\x02 \x01(\v2\".oppb.v1.AuthorizationHtmlResponseH\x00R\x04htmlB%\n" +
	"#authorization_cancel_response_oneof\"N\n" +
	"\x13StartSessionRequest\x12\x18\n" +
	"\asubject\x18\x01 \x01(\tR\asubject\x12\x1d\n" +
	"\n" +
	"request_id\x18\x02 \x01(\tR\trequestId\"@\n" +
	"\x14StartSessionResponse\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value\"\xc6\x01\n" +
	"\fTokenRequest\x121\n" +
	"\n" +
	"basic_auth\x18\x01 \x01(\v2\x12.oppb.v1.BasicAuthR\tbasicAuth\x12!\n" +
	"\fcontent_type\x18\x02 \x01(\tR\vcontentType\x12\x16\n" +
	"\x06method\x18\x03 \x01(\tR\x06method\x12\x12\n" +
	"\x04form\x18\x04 \x01(\tR\x04form\x124\n" +
	"\x16tls_client_certificate\x18\x05 \x01(\tR\x14tlsClientCertificate\"\x94\x01\n" +
	"\rTokenResponse\x129\n" +
	"\asuccess\x18\x01 \x01(\v2\x1d.oppb.v1.TokenSuccessResponseH\x00R\asuccess\x120\n" +
	"\x04fail\x18\x02 \x01(\v2\x1a.oppb.v1.TokenFailResponseH\x00R\x04failB\x16\n" +
	"\x14token_response_oneof\"\xbc\x01\n" +
	"\x0fUserinfoRequest\x12$\n" +
	"\rauthorization\x18\x01 \x01(\tR\rauthorization\x12!\n" +
	"\fcontent_type\x18\x02 \x01(\tR\vcontentType\x12\x16\n" +
	"\x06method\x18\x03 \x01(\tR\x06method\x12\x12\n" +
	"\x04form\x18\x04 \x01(\tR\x04form\x124\n" +
	"\x16tls_client_certificate\x18\x05 \x01(\tR\x14tlsClientCertificate\"\xc5\x01\n" +
	"\x10UserinfoResponse\x12@\n" +
	"\aheaders\x18\x01 \x03(\v2&.oppb.v1.UserinfoResponse.HeadersEntryR\aheaders\x12\x1f\n" +
	"\vstatus_code\x18\x02 \x01(\x05R\n" +
	"statusCode\x12\x12\n" +
	"\x04body\x18\x03 \x01(\tR\x04body\x1a:\n" +
	"\fHeadersEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xd4\x01\n" +
	"\x1aPushedAuthorizationRequest\x121\n" +
	"\n" +
	"basic_auth\x18\x01 \x01(\v2\x12.oppb.v1.BasicAuthR\tbasicAuth\x12!\n" +
	"\fcontent_type\x18\x02 \x01(\tR\vcontentType\x12\x16\n" +
	"\x06method\x18\x03 \x01(\tR\x06method\x12\x12\n" +
	"\x04form\x18\x04 \x01(\tR\x04form\x124\n" +
	"\x16tls_client_certificate\x18\x05 \x01(\tR\x14tlsClientCertificate\"\xcd\x01\n" +
	"\x1bPushedAuthorizationResponse\x12G\n" +
	"\asuccess\x18\x01 \x01(\v2+.oppb.v1.PushedAuthorizationSuccessResponseH\x00R\asuccess\x12>\n" +
	"\x04fail\x18\x02 \x01(\v2(.oppb.v1.PushedAuthorizationFailResponseH\x00R\x04failB%\n" +
	"#pushed_authorization_response_oneof\"/\n" +
	"\x0eRequestRequest\x12\x1d\n" +
	"\n" +
	"request_id\x18\x01 \x01(\tR\trequestId\"\x81\x01\n" +
	"\x0fRequestResponse\x12+\n" +
	"\x06client\x18\x01 \x01(\v2\x13.oppb.v1.ClientMetaR\x06client\x12A\n" +
	"\vauth_params\x18\x02 \x01(\v2 .oppb.v1.AuthorizationParametersR\n" +
	"authParams\"w\n" +
	"\x19AuthorizationFailResponse\x12\x1f\n" +
	"\vstatus_code\x18\x01 \x01(\x05R\n" +
	"statusCode\x129\n" +
	"\x05error\x18\x02 \x01(\v2#.oppb.v1.AuthorizationErrorResponseR\x05error\"\x92\x01\n" +
	"\x1aAuthorizationErrorResponse\x12\x14\n" +
	"\x05error\x18\x01 \x01(\tR\x05error\x12+\n" +
	"\x11error_description\x18\x02 \x01(\tR\x10errorDescription\x12\x1b\n" +
	"\terror_uri\x18\x03 \x01(\tR\berrorUri\x12\x14\n" +
	"\x05state\x18\x04 \x01(\tR\x05state\"\xad\x01\n" +
	"\x1cAuthorizationNextActionLogin\x12\x1d\n" +
	"\n" +
	"request_id\x18\x01 \x01(\tR\trequestId\x12+\n" +
	"\x06client\x18\x02 \x01(\v2\x13.oppb.v1.ClientMetaR\x06client\x12A\n" +
	"\vauth_params\x18\x03 \x01(\v2 .oppb.v1.AuthorizationParametersR\n" +
	"authParams\"\xe6\x01\n" +
	"\x1cAuthorizationNextActionIssue\x12\x1d\n" +
	"\n" +
	"request_id\x18\x01 \x01(\tR\trequestId\x12\x1d\n" +
	"\n" +
	"session_id\x18\x02 \x01(\tR\tsessionId\x12\x18\n" +
	"\asubject\x18\x03 \x01(\tR\asubject\x12+\n" +
	"\x06client\x18\x04 \x01(\v2\x13.oppb.v1.ClientMetaR\x06client\x12A\n" +
	"\vauth_params\x18\x05 \x01(\v2 .oppb.v1.AuthorizationParametersR\n" +
	"authParams\"1\n" +
	"\x1dAuthorizationRedirectResponse\x12\x10\n" +
	"\x03url\x18\x01 \x01(\tR\x03url\"5\n" +
	"\x19AuthorizationHtmlResponse\x12\x18\n" +
	"\acontent\x18\x01 \x01(\tR\acontent\"\xd2\x01\n" +
	"\x14TokenSuccessResponse\x12\"\n" +
	"\faccess_token\x18\x01 \x01(\tR\faccess_token\x12\x1e\n" +
	"\n" +
	"token_type\x18\x02 \x01(\tR\n" +
	"token_type\x12\x1e\n" +
	"\n" +
	"expires_in\x18\x03 \x01(\x05R\n" +
	"expires_in\x12$\n" +
	"\rrefresh_token\x18\x04 \x01(\tR\rrefresh_token\x12\x14\n" +
	"\x05scope\x18\x05 \x01(\tR\x05scope\x12\x1a\n" +
	"\bid_token\x18\x06 \x01(\tR\bid_token\"_\n" +
	"\x11TokenFailResponse\x12\x1f\n" +
	"\vstatus_code\x18\x01 \x01(\x05R\n" +
	"statusCode\x12)\n" +
	"\x05error\x18\x02 \x01(\v2\x13.oppb.v1.OauthErrorR\x05error\"\x85\x01\n" +
	"\"PushedAuthorizationSuccessResponse\x12\x1f\n" +
	"\vstatus_code\x18\x01 \x01(\x05R\n" +
	"statusCode\x12\x1f\n" +
	"\vrequest_uri\x18\x02 \x01(\tR\n" +
	"requestUri\x12\x1d\n" +
	"\n" +
	"expires_in\x18\x03 \x01(\x05R\texpiresIn\"m\n" +
	"\x1fPushedAuthorizationFailResponse\x12\x1f\n" +
	"\vstatus_code\x18\x01 \x01(\x05R\n" +
	"statusCode\x12)\n" +
	"\x05error\x18\x02 \x01(\v2\x13.oppb.v1.OauthErrorR\x05error\"n\n" +
	"\n" +
	"OauthError\x12\x14\n" +
	"\x05error\x18\x01 \x01(\tR\x05error\x12,\n" +
	"\x11error_description\x18\x02 \x01(\tR\x11error_description\x12\x1c\n" +
	"\terror_uri\x18\x03 \x01(\tR\terror_uri\"C\n" +
	"\tBasicAuth\x12\x1a\n" +
	"\busername\x18\x01 \x01(\tR\busername\x12\x1a\n" +
	"\bpassword\x18\x02 \x01(\tR\bpassword2\x95\b\n" +
	"\x0fProviderService\x12B\n" +
	"\tDiscovery\x12\x19.oppb.v1.DiscoveryRequest\x1a\x1a.oppb.v1.DiscoveryResponse\x123\n" +
	"\x04Jwks\x12\x14.oppb.v1.JwksRequest\x1a\x15.oppb.v1.JwksResponse\x12N\n" +
	"\rAuthorization\x12\x1d.oppb.v1.AuthorizationRequest\x1a\x1e.oppb.v1.AuthorizationResponse\x12]\n" +
	"\x12AuthorizationIssue\x12\".oppb.v1.AuthorizationIssueRequest\x1a#.oppb.v1.AuthorizationIssueResponse\x12`\n" +
	"\x13AuthorizationCancel\x12#.oppb.v1.AuthorizationCancelRequest\x1a$.oppb.v1.AuthorizationCancelResponse\x12K\n" +
	"\fStartSession\x12\x1c.oppb.v1.StartSessionRequest\x1a\x1d.oppb.v1.StartSessionResponse\x126\n" +
	"\x05Token\x12\x15.oppb.v1.TokenRequest\x1a\x16.oppb.v1.TokenResponse\x12?\n" +
	"\bUserinfo\x12\x18.oppb.v1.UserinfoRequest\x1a\x19.oppb.v1.UserinfoResponse\x12`\n" +
	"\x13PushedAuthorization\x12#.oppb.v1.PushedAuthorizationRequest\x1a$.oppb.v1.PushedAuthorizationResponse\x12<\n" +
	"\aRequest\x12\x17.oppb.v1.RequestRequest\x1a\x18.oppb.v1.RequestResponse\x12]\n" +
	"\x12RegistrationCreate\x12\".oppb.v1.RegistrationCreateRequest\x1a#.oppb.v1.RegistrationCreateResponse\x12]\n" +
	"\x12RegistrationDelete\x12\".oppb.v1.RegistrationDeleteRequest\x1a#.oppb.v1.RegistrationDeleteResponse\x12T\n" +
	"\x0fRegistrationGet\x12\x1f.oppb.v1.RegistrationGetRequest\x1a .oppb.v1.RegistrationGetResponseB\x9a\x01\n" +
	"\vcom.oppb.v1B\x14ProviderServiceProtoP\x01Z8github.com/Eigen438/opgo/pkg/auto-generated/oppb/v1;oppb\xa2\x02\x03OXX\xaa\x02\aOppb.V1\xca\x02\aOppb\\V1\xe2\x02\x13Oppb\\V1\\GPBMetadata\xea\x02\bOppb::V1b\x06proto3"

var (
	file_oppb_v1_provider_service_proto_rawDescOnce sync.Once
	file_oppb_v1_provider_service_proto_rawDescData []byte
)

func file_oppb_v1_provider_service_proto_rawDescGZIP() []byte {
	file_oppb_v1_provider_service_proto_rawDescOnce.Do(func() {
		file_oppb_v1_provider_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_oppb_v1_provider_service_proto_rawDesc), len(file_oppb_v1_provider_service_proto_rawDesc)))
	})
	return file_oppb_v1_provider_service_proto_rawDescData
}

var file_oppb_v1_provider_service_proto_msgTypes = make([]protoimpl.MessageInfo, 34)
var file_oppb_v1_provider_service_proto_goTypes = []any{
	(*DiscoveryRequest)(nil),                   // 0: oppb.v1.DiscoveryRequest
	(*DiscoveryResponse)(nil),                  // 1: oppb.v1.DiscoveryResponse
	(*JwksRequest)(nil),                        // 2: oppb.v1.JwksRequest
	(*JwksResponse)(nil),                       // 3: oppb.v1.JwksResponse
	(*AuthorizationRequest)(nil),               // 4: oppb.v1.AuthorizationRequest
	(*AuthorizationResponse)(nil),              // 5: oppb.v1.AuthorizationResponse
	(*AuthorizationIssueRequest)(nil),          // 6: oppb.v1.AuthorizationIssueRequest
	(*AuthorizationIssueResponse)(nil),         // 7: oppb.v1.AuthorizationIssueResponse
	(*AuthorizationCancelRequest)(nil),         // 8: oppb.v1.AuthorizationCancelRequest
	(*AuthorizationCancelResponse)(nil),        // 9: oppb.v1.AuthorizationCancelResponse
	(*StartSessionRequest)(nil),                // 10: oppb.v1.StartSessionRequest
	(*StartSessionResponse)(nil),               // 11: oppb.v1.StartSessionResponse
	(*TokenRequest)(nil),                       // 12: oppb.v1.TokenRequest
	(*TokenResponse)(nil),                      // 13: oppb.v1.TokenResponse
	(*UserinfoRequest)(nil),                    // 14: oppb.v1.UserinfoRequest
	(*UserinfoResponse)(nil),                   // 15: oppb.v1.UserinfoResponse
	(*PushedAuthorizationRequest)(nil),         // 16: oppb.v1.PushedAuthorizationRequest
	(*PushedAuthorizationResponse)(nil),        // 17: oppb.v1.PushedAuthorizationResponse
	(*RequestRequest)(nil),                     // 18: oppb.v1.RequestRequest
	(*RequestResponse)(nil),                    // 19: oppb.v1.RequestResponse
	(*AuthorizationFailResponse)(nil),          // 20: oppb.v1.AuthorizationFailResponse
	(*AuthorizationErrorResponse)(nil),         // 21: oppb.v1.AuthorizationErrorResponse
	(*AuthorizationNextActionLogin)(nil),       // 22: oppb.v1.AuthorizationNextActionLogin
	(*AuthorizationNextActionIssue)(nil),       // 23: oppb.v1.AuthorizationNextActionIssue
	(*AuthorizationRedirectResponse)(nil),      // 24: oppb.v1.AuthorizationRedirectResponse
	(*AuthorizationHtmlResponse)(nil),          // 25: oppb.v1.AuthorizationHtmlResponse
	(*TokenSuccessResponse)(nil),               // 26: oppb.v1.TokenSuccessResponse
	(*TokenFailResponse)(nil),                  // 27: oppb.v1.TokenFailResponse
	(*PushedAuthorizationSuccessResponse)(nil), // 28: oppb.v1.PushedAuthorizationSuccessResponse
	(*PushedAuthorizationFailResponse)(nil),    // 29: oppb.v1.PushedAuthorizationFailResponse
	(*OauthError)(nil),                         // 30: oppb.v1.OauthError
	(*BasicAuth)(nil),                          // 31: oppb.v1.BasicAuth
	nil,                                        // 32: oppb.v1.AuthorizationRequest.SessionsEntry
	nil,                                        // 33: oppb.v1.UserinfoResponse.HeadersEntry
	(*IssuerMeta)(nil),                         // 34: oppb.v1.IssuerMeta
	(*Jwk)(nil),                                // 35: oppb.v1.Jwk
	(*AuthorizationParameters)(nil),            // 36: oppb.v1.AuthorizationParameters
	(*ClientMeta)(nil),                         // 37: oppb.v1.ClientMeta
	(*ClientAttribute)(nil),                    // 38: oppb.v1.ClientAttribute
	(*RegistrationCreateRequest)(nil),          // 39: oppb.v1.RegistrationCreateRequest
	(*RegistrationDeleteRequest)(nil),          // 40: oppb.v1.RegistrationDeleteRequest
	(*RegistrationGetRequest)(nil),             // 41: oppb.v1.RegistrationGetRequest
	(*RegistrationCreateResponse)(nil),         // 42: oppb.v1.RegistrationCreateResponse
	(*RegistrationDeleteResponse)(nil),         // 43: oppb.v1.RegistrationDeleteResponse
	(*RegistrationGetResponse)(nil),            // 44: oppb.v1.RegistrationGetResponse
}
var file_oppb_v1_provider_service_proto_depIdxs = []int32{
	34, // 0: oppb.v1.DiscoveryResponse.meta:type_name -> oppb.v1.IssuerMeta
	35, // 1: oppb.v1.JwksResponse.keys:type_name -> oppb.v1.Jwk
	32, // 2: oppb.v1.AuthorizationRequest.sessions:type_name -> oppb.v1.AuthorizationRequest.SessionsEntry
	20, // 3: oppb.v1.AuthorizationResponse.fail:type_name -> oppb.v1.AuthorizationFailResponse
	22, // 4: oppb.v1.AuthorizationResponse.login:type_name -> oppb.v1.AuthorizationNextActionLogin
	23, // 5: oppb.v1.AuthorizationResponse.issue:type_name -> oppb.v1.AuthorizationNextActionIssue
	24, // 6: oppb.v1.AuthorizationResponse.redirect:type_name -> oppb.v1.AuthorizationRedirectResponse
	25, // 7: oppb.v1.AuthorizationResponse.html:type_name -> oppb.v1.AuthorizationHtmlResponse
	36, // 8: oppb.v1.AuthorizationResponse.params:type_name -> oppb.v1.AuthorizationParameters
	37, // 9: oppb.v1.AuthorizationResponse.client:type_name -> oppb.v1.ClientMeta
	38, // 10: oppb.v1.AuthorizationResponse.client_attribute:type_name -> oppb.v1.ClientAttribute
	24, // 11: oppb.v1.AuthorizationIssueResponse.redirect:type_name -> oppb.v1.AuthorizationRedirectResponse
	25, // 12: oppb.v1.AuthorizationIssueResponse.html:type_name -> oppb.v1.AuthorizationHtmlResponse
	24, // 13: oppb.v1.AuthorizationCancelResponse.redirect:type_name -> oppb.v1.AuthorizationRedirectResponse
	25, // 14: oppb.v1.AuthorizationCancelResponse.html:type_name -> oppb.v1.AuthorizationHtmlResponse
	31, // 15: oppb.v1.TokenRequest.basic_auth:type_name -> oppb.v1.BasicAuth
	26, // 16: oppb.v1.TokenResponse.success:type_name -> oppb.v1.TokenSuccessResponse
	27, // 17: oppb.v1.TokenResponse.fail:type_name -> oppb.v1.TokenFailResponse
	33, // 18: oppb.v1.UserinfoResponse.headers:type_name -> oppb.v1.UserinfoResponse.HeadersEntry
	31, // 19: oppb.v1.PushedAuthorizationRequest.basic_auth:type_name -> oppb.v1.BasicAuth
	28, // 20: oppb.v1.PushedAuthorizationResponse.success:type_name -> oppb.v1.PushedAuthorizationSuccessResponse
	29, // 21: oppb.v1.PushedAuthorizationResponse.fail:type_name -> oppb.v1.PushedAuthorizationFailResponse
	37, // 22: oppb.v1.RequestResponse.client:type_name -> oppb.v1.ClientMeta
	36, // 23: oppb.v1.RequestResponse.auth_params:type_name -> oppb.v1.AuthorizationParameters
	21, // 24: oppb.v1.AuthorizationFailResponse.error:type_name -> oppb.v1.AuthorizationErrorResponse
	37, // 25: oppb.v1.AuthorizationNextActionLogin.client:type_name -> oppb.v1.ClientMeta
	36, // 26: oppb.v1.AuthorizationNextActionLogin.auth_params:type_name -> oppb.v1.AuthorizationParameters
	37, // 27: oppb.v1.AuthorizationNextActionIssue.client:type_name -> oppb.v1.ClientMeta
	36, // 28: oppb.v1.AuthorizationNextActionIssue.auth_params:type_name -> oppb.v1.AuthorizationParameters
	30, // 29: oppb.v1.TokenFailResponse.error:type_name -> oppb.v1.OauthError
	30, // 30: oppb.v1.PushedAuthorizationFailResponse.error:type_name -> oppb.v1.OauthError
	0,  // 31: oppb.v1.ProviderService.Discovery:input_type -> oppb.v1.DiscoveryRequest
	2,  // 32: oppb.v1.ProviderService.Jwks:input_type -> oppb.v1.JwksRequest
	4,  // 33: oppb.v1.ProviderService.Authorization:input_type -> oppb.v1.AuthorizationRequest
	6,  // 34: oppb.v1.ProviderService.AuthorizationIssue:input_type -> oppb.v1.AuthorizationIssueRequest
	8,  // 35: oppb.v1.ProviderService.AuthorizationCancel:input_type -> oppb.v1.AuthorizationCancelRequest
	10, // 36: oppb.v1.ProviderService.StartSession:input_type -> oppb.v1.StartSessionRequest
	12, // 37: oppb.v1.ProviderService.Token:input_type -> oppb.v1.TokenRequest
	14, // 38: oppb.v1.ProviderService.Userinfo:input_type -> oppb.v1.UserinfoRequest
	16, // 39: oppb.v1.ProviderService.PushedAuthorization:input_type -> oppb.v1.PushedAuthorizationRequest
	18, // 40: oppb.v1.ProviderService.Request:input_type -> oppb.v1.RequestRequest
	39, // 41: oppb.v1.ProviderService.RegistrationCreate:input_type -> oppb.v1.RegistrationCreateRequest
	40, // 42: oppb.v1.ProviderService.RegistrationDelete:input_type -> oppb.v1.RegistrationDeleteRequest
	41, // 43: oppb.v1.ProviderService.RegistrationGet:input_type -> oppb.v1.RegistrationGetRequest
	1,  // 44: oppb.v1.ProviderService.Discovery:output_type -> oppb.v1.DiscoveryResponse
	3,  // 45: oppb.v1.ProviderService.Jwks:output_type -> oppb.v1.JwksResponse
	5,  // 46: oppb.v1.ProviderService.Authorization:output_type -> oppb.v1.AuthorizationResponse
	7,  // 47: oppb.v1.ProviderService.AuthorizationIssue:output_type -> oppb.v1.AuthorizationIssueResponse
	9,  // 48: oppb.v1.ProviderService.AuthorizationCancel:output_type -> oppb.v1.AuthorizationCancelResponse
	11, // 49: oppb.v1.ProviderService.StartSession:output_type -> oppb.v1.StartSessionResponse
	13, // 50: oppb.v1.ProviderService.Token:output_type -> oppb.v1.TokenResponse
	15, // 51: oppb.v1.ProviderService.Userinfo:output_type -> oppb.v1.UserinfoResponse
	17, // 52: oppb.v1.ProviderService.PushedAuthorization:output_type -> oppb.v1.PushedAuthorizationResponse
	19, // 53: oppb.v1.ProviderService.Request:output_type -> oppb.v1.RequestResponse
	42, // 54: oppb.v1.ProviderService.RegistrationCreate:output_type -> oppb.v1.RegistrationCreateResponse
	43, // 55: oppb.v1.ProviderService.RegistrationDelete:output_type -> oppb.v1.RegistrationDeleteResponse
	44, // 56: oppb.v1.ProviderService.RegistrationGet:output_type -> oppb.v1.RegistrationGetResponse
	44, // [44:57] is the sub-list for method output_type
	31, // [31:44] is the sub-list for method input_type
	31, // [31:31] is the sub-list for extension type_name
	31, // [31:31] is the sub-list for extension extendee
	0,  // [0:31] is the sub-list for field type_name
}

func init() { file_oppb_v1_provider_service_proto_init() }
func file_oppb_v1_provider_service_proto_init() {
	if File_oppb_v1_provider_service_proto != nil {
		return
	}
	file_oppb_v1_authorization_parameters_proto_init()
	file_oppb_v1_client_proto_init()
	file_oppb_v1_client_meta_proto_init()
	file_oppb_v1_issuer_meta_proto_init()
	file_oppb_v1_jwks_proto_init()
	file_oppb_v1_registration_proto_init()
	file_oppb_v1_provider_service_proto_msgTypes[5].OneofWrappers = []any{
		(*AuthorizationResponse_Fail)(nil),
		(*AuthorizationResponse_Login)(nil),
		(*AuthorizationResponse_Issue)(nil),
		(*AuthorizationResponse_Redirect)(nil),
		(*AuthorizationResponse_Html)(nil),
	}
	file_oppb_v1_provider_service_proto_msgTypes[7].OneofWrappers = []any{
		(*AuthorizationIssueResponse_Redirect)(nil),
		(*AuthorizationIssueResponse_Html)(nil),
	}
	file_oppb_v1_provider_service_proto_msgTypes[9].OneofWrappers = []any{
		(*AuthorizationCancelResponse_Redirect)(nil),
		(*AuthorizationCancelResponse_Html)(nil),
	}
	file_oppb_v1_provider_service_proto_msgTypes[13].OneofWrappers = []any{
		(*TokenResponse_Success)(nil),
		(*TokenResponse_Fail)(nil),
	}
	file_oppb_v1_provider_service_proto_msgTypes[17].OneofWrappers = []any{
		(*PushedAuthorizationResponse_Success)(nil),
		(*PushedAuthorizationResponse_Fail)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_oppb_v1_provider_service_proto_rawDesc), len(file_oppb_v1_provider_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   34,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_oppb_v1_provider_service_proto_goTypes,
		DependencyIndexes: file_oppb_v1_provider_service_proto_depIdxs,
		MessageInfos:      file_oppb_v1_provider_service_proto_msgTypes,
	}.Build()
	File_oppb_v1_provider_service_proto = out.File
	file_oppb_v1_provider_service_proto_goTypes = nil
	file_oppb_v1_provider_service_proto_depIdxs = nil
}
