// MIT License
//
// Copyright (c) 2025 Eigen
//
// Permission is hereby granted, free of charge, to any person obtaining a copy
// of this software and associated documentation files (the "Software"), to deal
// in the Software without restriction, including without limitation the rights
// to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
// copies of the Software, and to permit persons to whom the Software is
// furnished to do so, subject to the following conditions:
//
// The above copyright notice and this permission notice shall be included in all
// copies or substantial portions of the Software.
//
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
// IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
// FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
// AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
// LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
// OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
// SOFTWARE.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        (unknown)
// source: oppb/v1/registration.proto

package oppb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RegistrationCreateRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// ClientMeta
	// https://openid.net/specs/openid-connect-registration-1_0.html#ClientMetadata
	RedirectUris                 []string `protobuf:"bytes,101,rep,name=redirect_uris,proto3" json:"redirect_uris,omitempty"`
	ResponseTypes                []string `protobuf:"bytes,102,rep,name=response_types,proto3" json:"response_types,omitempty"`
	GrantTypes                   []string `protobuf:"bytes,103,rep,name=grant_types,proto3" json:"grant_types,omitempty"`
	ApplicationType              string   `protobuf:"bytes,104,opt,name=application_type,proto3" json:"application_type,omitempty"`
	Contacts                     []string `protobuf:"bytes,105,rep,name=contacts,proto3" json:"contacts,omitempty"`
	ClientName                   string   `protobuf:"bytes,106,opt,name=client_name,proto3" json:"client_name,omitempty"`
	LogoUri                      string   `protobuf:"bytes,107,opt,name=logo_uri,proto3" json:"logo_uri,omitempty"`
	ClientUri                    string   `protobuf:"bytes,108,opt,name=client_uri,proto3" json:"client_uri,omitempty"`
	PolicyUri                    string   `protobuf:"bytes,109,opt,name=policy_uri,proto3" json:"policy_uri,omitempty"`
	TosUri                       string   `protobuf:"bytes,110,opt,name=tos_uri,proto3" json:"tos_uri,omitempty"`
	JwksUri                      string   `protobuf:"bytes,111,opt,name=jwks_uri,proto3" json:"jwks_uri,omitempty"`
	Jwks                         *Jwks    `protobuf:"bytes,112,opt,name=jwks,proto3" json:"jwks,omitempty"`
	SectorIdentifierUri          string   `protobuf:"bytes,113,opt,name=sector_identifier_uri,proto3" json:"sector_identifier_uri,omitempty"`
	SubjectType                  string   `protobuf:"bytes,114,opt,name=subject_type,proto3" json:"subject_type,omitempty"`
	IdTokenSignedResponseAlg     string   `protobuf:"bytes,115,opt,name=id_token_signed_response_alg,proto3" json:"id_token_signed_response_alg,omitempty"`
	IdTokenEncryptedResponseAlg  string   `protobuf:"bytes,116,opt,name=id_token_encrypted_response_alg,proto3" json:"id_token_encrypted_response_alg,omitempty"`
	IdTokenEncryptedResponseEnc  string   `protobuf:"bytes,117,opt,name=id_token_encrypted_response_enc,proto3" json:"id_token_encrypted_response_enc,omitempty"`
	UserinfoSignedResponseAlg    string   `protobuf:"bytes,118,opt,name=userinfo_signed_response_alg,proto3" json:"userinfo_signed_response_alg,omitempty"`
	UserinfoEncryptedResponseAlg string   `protobuf:"bytes,119,opt,name=userinfo_encrypted_response_alg,proto3" json:"userinfo_encrypted_response_alg,omitempty"`
	UserinfoEncryptedResponseEnc string   `protobuf:"bytes,120,opt,name=userinfo_encrypted_response_enc,proto3" json:"userinfo_encrypted_response_enc,omitempty"`
	RequestObjectSigningAlg      string   `protobuf:"bytes,121,opt,name=request_object_signing_alg,proto3" json:"request_object_signing_alg,omitempty"`
	RequestObjectEncryptionAlg   string   `protobuf:"bytes,122,opt,name=request_object_encryption_alg,proto3" json:"request_object_encryption_alg,omitempty"`
	RequestObjectEncryptionEnc   string   `protobuf:"bytes,123,opt,name=request_object_encryption_enc,proto3" json:"request_object_encryption_enc,omitempty"`
	TokenEndpointAuthMethod      string   `protobuf:"bytes,124,opt,name=token_endpoint_auth_method,proto3" json:"token_endpoint_auth_method,omitempty"`
	TokenEndpointAuthSigningAlg  string   `protobuf:"bytes,125,opt,name=token_endpoint_auth_signing_alg,proto3" json:"token_endpoint_auth_signing_alg,omitempty"`
	DefaultMaxAge                string   `protobuf:"bytes,126,opt,name=default_max_age,proto3" json:"default_max_age,omitempty"`
	RequireAuthTime              bool     `protobuf:"varint,127,opt,name=require_auth_time,proto3" json:"require_auth_time,omitempty"`
	DefaultAcrValues             []string `protobuf:"bytes,128,rep,name=default_acr_values,proto3" json:"default_acr_values,omitempty"`
	InitiateLoginUri             string   `protobuf:"bytes,129,opt,name=initiate_login_uri,proto3" json:"initiate_login_uri,omitempty"`
	RequestUris                  []string `protobuf:"bytes,130,rep,name=request_uris,proto3" json:"request_uris,omitempty"`
	// https://openid.net/specs/openid-connect-rpinitiated-1_0.html#ClientMetadata
	PostLogoutRedirectUris []string `protobuf:"bytes,131,rep,name=post_logout_redirect_uris,proto3" json:"post_logout_redirect_uris,omitempty"`
	// https://www.rfc-editor.org/rfc/rfc9126.html#section-6
	RequirePushedAuthorizationRequests bool `protobuf:"varint,132,opt,name=require_pushed_authorization_requests,proto3" json:"require_pushed_authorization_requests,omitempty"`
	// https://openid.net/specs/openid-financial-api-jarm.html#client-metadata
	AuthorizationSignedResponseAlg    string `protobuf:"bytes,133,opt,name=authorization_signed_response_alg,proto3" json:"authorization_signed_response_alg,omitempty"`
	AuthorizationEncryptedResponseAlg string `protobuf:"bytes,134,opt,name=authorization_encrypted_response_alg,proto3" json:"authorization_encrypted_response_alg,omitempty"`
	AuthorizationEncryptedResponseEnc string `protobuf:"bytes,135,opt,name=authorization_encrypted_response_enc,proto3" json:"authorization_encrypted_response_enc,omitempty"`
	// https://datatracker.ietf.org/doc/html/rfc8705#section-3.4
	TlsClientCertificateBoundAccessTokens bool `protobuf:"varint,136,opt,name=tls_client_certificate_bound_access_tokens,proto3" json:"tls_client_certificate_bound_access_tokens,omitempty"`
	unknownFields                         protoimpl.UnknownFields
	sizeCache                             protoimpl.SizeCache
}

func (x *RegistrationCreateRequest) Reset() {
	*x = RegistrationCreateRequest{}
	mi := &file_oppb_v1_registration_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegistrationCreateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegistrationCreateRequest) ProtoMessage() {}

func (x *RegistrationCreateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_oppb_v1_registration_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegistrationCreateRequest.ProtoReflect.Descriptor instead.
func (*RegistrationCreateRequest) Descriptor() ([]byte, []int) {
	return file_oppb_v1_registration_proto_rawDescGZIP(), []int{0}
}

func (x *RegistrationCreateRequest) GetRedirectUris() []string {
	if x != nil {
		return x.RedirectUris
	}
	return nil
}

func (x *RegistrationCreateRequest) GetResponseTypes() []string {
	if x != nil {
		return x.ResponseTypes
	}
	return nil
}

func (x *RegistrationCreateRequest) GetGrantTypes() []string {
	if x != nil {
		return x.GrantTypes
	}
	return nil
}

func (x *RegistrationCreateRequest) GetApplicationType() string {
	if x != nil {
		return x.ApplicationType
	}
	return ""
}

func (x *RegistrationCreateRequest) GetContacts() []string {
	if x != nil {
		return x.Contacts
	}
	return nil
}

func (x *RegistrationCreateRequest) GetClientName() string {
	if x != nil {
		return x.ClientName
	}
	return ""
}

func (x *RegistrationCreateRequest) GetLogoUri() string {
	if x != nil {
		return x.LogoUri
	}
	return ""
}

func (x *RegistrationCreateRequest) GetClientUri() string {
	if x != nil {
		return x.ClientUri
	}
	return ""
}

func (x *RegistrationCreateRequest) GetPolicyUri() string {
	if x != nil {
		return x.PolicyUri
	}
	return ""
}

func (x *RegistrationCreateRequest) GetTosUri() string {
	if x != nil {
		return x.TosUri
	}
	return ""
}

func (x *RegistrationCreateRequest) GetJwksUri() string {
	if x != nil {
		return x.JwksUri
	}
	return ""
}

func (x *RegistrationCreateRequest) GetJwks() *Jwks {
	if x != nil {
		return x.Jwks
	}
	return nil
}

func (x *RegistrationCreateRequest) GetSectorIdentifierUri() string {
	if x != nil {
		return x.SectorIdentifierUri
	}
	return ""
}

func (x *RegistrationCreateRequest) GetSubjectType() string {
	if x != nil {
		return x.SubjectType
	}
	return ""
}

func (x *RegistrationCreateRequest) GetIdTokenSignedResponseAlg() string {
	if x != nil {
		return x.IdTokenSignedResponseAlg
	}
	return ""
}

func (x *RegistrationCreateRequest) GetIdTokenEncryptedResponseAlg() string {
	if x != nil {
		return x.IdTokenEncryptedResponseAlg
	}
	return ""
}

func (x *RegistrationCreateRequest) GetIdTokenEncryptedResponseEnc() string {
	if x != nil {
		return x.IdTokenEncryptedResponseEnc
	}
	return ""
}

func (x *RegistrationCreateRequest) GetUserinfoSignedResponseAlg() string {
	if x != nil {
		return x.UserinfoSignedResponseAlg
	}
	return ""
}

func (x *RegistrationCreateRequest) GetUserinfoEncryptedResponseAlg() string {
	if x != nil {
		return x.UserinfoEncryptedResponseAlg
	}
	return ""
}

func (x *RegistrationCreateRequest) GetUserinfoEncryptedResponseEnc() string {
	if x != nil {
		return x.UserinfoEncryptedResponseEnc
	}
	return ""
}

func (x *RegistrationCreateRequest) GetRequestObjectSigningAlg() string {
	if x != nil {
		return x.RequestObjectSigningAlg
	}
	return ""
}

func (x *RegistrationCreateRequest) GetRequestObjectEncryptionAlg() string {
	if x != nil {
		return x.RequestObjectEncryptionAlg
	}
	return ""
}

func (x *RegistrationCreateRequest) GetRequestObjectEncryptionEnc() string {
	if x != nil {
		return x.RequestObjectEncryptionEnc
	}
	return ""
}

func (x *RegistrationCreateRequest) GetTokenEndpointAuthMethod() string {
	if x != nil {
		return x.TokenEndpointAuthMethod
	}
	return ""
}

func (x *RegistrationCreateRequest) GetTokenEndpointAuthSigningAlg() string {
	if x != nil {
		return x.TokenEndpointAuthSigningAlg
	}
	return ""
}

func (x *RegistrationCreateRequest) GetDefaultMaxAge() string {
	if x != nil {
		return x.DefaultMaxAge
	}
	return ""
}

func (x *RegistrationCreateRequest) GetRequireAuthTime() bool {
	if x != nil {
		return x.RequireAuthTime
	}
	return false
}

func (x *RegistrationCreateRequest) GetDefaultAcrValues() []string {
	if x != nil {
		return x.DefaultAcrValues
	}
	return nil
}

func (x *RegistrationCreateRequest) GetInitiateLoginUri() string {
	if x != nil {
		return x.InitiateLoginUri
	}
	return ""
}

func (x *RegistrationCreateRequest) GetRequestUris() []string {
	if x != nil {
		return x.RequestUris
	}
	return nil
}

func (x *RegistrationCreateRequest) GetPostLogoutRedirectUris() []string {
	if x != nil {
		return x.PostLogoutRedirectUris
	}
	return nil
}

func (x *RegistrationCreateRequest) GetRequirePushedAuthorizationRequests() bool {
	if x != nil {
		return x.RequirePushedAuthorizationRequests
	}
	return false
}

func (x *RegistrationCreateRequest) GetAuthorizationSignedResponseAlg() string {
	if x != nil {
		return x.AuthorizationSignedResponseAlg
	}
	return ""
}

func (x *RegistrationCreateRequest) GetAuthorizationEncryptedResponseAlg() string {
	if x != nil {
		return x.AuthorizationEncryptedResponseAlg
	}
	return ""
}

func (x *RegistrationCreateRequest) GetAuthorizationEncryptedResponseEnc() string {
	if x != nil {
		return x.AuthorizationEncryptedResponseEnc
	}
	return ""
}

func (x *RegistrationCreateRequest) GetTlsClientCertificateBoundAccessTokens() bool {
	if x != nil {
		return x.TlsClientCertificateBoundAccessTokens
	}
	return false
}

type RegistrationCreateResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to RegistrationCreateResponseOneof:
	//
	//	*RegistrationCreateResponse_Success
	//	*RegistrationCreateResponse_Fail
	RegistrationCreateResponseOneof isRegistrationCreateResponse_RegistrationCreateResponseOneof `protobuf_oneof:"registration_create_response_oneof"`
	unknownFields                   protoimpl.UnknownFields
	sizeCache                       protoimpl.SizeCache
}

func (x *RegistrationCreateResponse) Reset() {
	*x = RegistrationCreateResponse{}
	mi := &file_oppb_v1_registration_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegistrationCreateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegistrationCreateResponse) ProtoMessage() {}

func (x *RegistrationCreateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_oppb_v1_registration_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegistrationCreateResponse.ProtoReflect.Descriptor instead.
func (*RegistrationCreateResponse) Descriptor() ([]byte, []int) {
	return file_oppb_v1_registration_proto_rawDescGZIP(), []int{1}
}

func (x *RegistrationCreateResponse) GetRegistrationCreateResponseOneof() isRegistrationCreateResponse_RegistrationCreateResponseOneof {
	if x != nil {
		return x.RegistrationCreateResponseOneof
	}
	return nil
}

func (x *RegistrationCreateResponse) GetSuccess() *RegistrationCreateSuccessResponse {
	if x != nil {
		if x, ok := x.RegistrationCreateResponseOneof.(*RegistrationCreateResponse_Success); ok {
			return x.Success
		}
	}
	return nil
}

func (x *RegistrationCreateResponse) GetFail() *RegistrationFailResponse {
	if x != nil {
		if x, ok := x.RegistrationCreateResponseOneof.(*RegistrationCreateResponse_Fail); ok {
			return x.Fail
		}
	}
	return nil
}

type isRegistrationCreateResponse_RegistrationCreateResponseOneof interface {
	isRegistrationCreateResponse_RegistrationCreateResponseOneof()
}

type RegistrationCreateResponse_Success struct {
	Success *RegistrationCreateSuccessResponse `protobuf:"bytes,1,opt,name=success,proto3,oneof"`
}

type RegistrationCreateResponse_Fail struct {
	Fail *RegistrationFailResponse `protobuf:"bytes,2,opt,name=fail,proto3,oneof"`
}

func (*RegistrationCreateResponse_Success) isRegistrationCreateResponse_RegistrationCreateResponseOneof() {
}

func (*RegistrationCreateResponse_Fail) isRegistrationCreateResponse_RegistrationCreateResponseOneof() {
}

type RegistrationGetRequest struct {
	state                   protoimpl.MessageState `protogen:"open.v1"`
	ClientId                string                 `protobuf:"bytes,1,opt,name=client_id,json=clientId,proto3" json:"client_id,omitempty"`
	RegistrationAccessToken string                 `protobuf:"bytes,2,opt,name=registration_access_token,json=registrationAccessToken,proto3" json:"registration_access_token,omitempty"`
	unknownFields           protoimpl.UnknownFields
	sizeCache               protoimpl.SizeCache
}

func (x *RegistrationGetRequest) Reset() {
	*x = RegistrationGetRequest{}
	mi := &file_oppb_v1_registration_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegistrationGetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegistrationGetRequest) ProtoMessage() {}

func (x *RegistrationGetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_oppb_v1_registration_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegistrationGetRequest.ProtoReflect.Descriptor instead.
func (*RegistrationGetRequest) Descriptor() ([]byte, []int) {
	return file_oppb_v1_registration_proto_rawDescGZIP(), []int{2}
}

func (x *RegistrationGetRequest) GetClientId() string {
	if x != nil {
		return x.ClientId
	}
	return ""
}

func (x *RegistrationGetRequest) GetRegistrationAccessToken() string {
	if x != nil {
		return x.RegistrationAccessToken
	}
	return ""
}

type RegistrationGetResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to RegistrationGetResponseOneof:
	//
	//	*RegistrationGetResponse_Success
	//	*RegistrationGetResponse_Fail
	RegistrationGetResponseOneof isRegistrationGetResponse_RegistrationGetResponseOneof `protobuf_oneof:"registration_get_response_oneof"`
	unknownFields                protoimpl.UnknownFields
	sizeCache                    protoimpl.SizeCache
}

func (x *RegistrationGetResponse) Reset() {
	*x = RegistrationGetResponse{}
	mi := &file_oppb_v1_registration_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegistrationGetResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegistrationGetResponse) ProtoMessage() {}

func (x *RegistrationGetResponse) ProtoReflect() protoreflect.Message {
	mi := &file_oppb_v1_registration_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegistrationGetResponse.ProtoReflect.Descriptor instead.
func (*RegistrationGetResponse) Descriptor() ([]byte, []int) {
	return file_oppb_v1_registration_proto_rawDescGZIP(), []int{3}
}

func (x *RegistrationGetResponse) GetRegistrationGetResponseOneof() isRegistrationGetResponse_RegistrationGetResponseOneof {
	if x != nil {
		return x.RegistrationGetResponseOneof
	}
	return nil
}

func (x *RegistrationGetResponse) GetSuccess() *RegistrationGetSuccessResponse {
	if x != nil {
		if x, ok := x.RegistrationGetResponseOneof.(*RegistrationGetResponse_Success); ok {
			return x.Success
		}
	}
	return nil
}

func (x *RegistrationGetResponse) GetFail() *RegistrationFailResponse {
	if x != nil {
		if x, ok := x.RegistrationGetResponseOneof.(*RegistrationGetResponse_Fail); ok {
			return x.Fail
		}
	}
	return nil
}

type isRegistrationGetResponse_RegistrationGetResponseOneof interface {
	isRegistrationGetResponse_RegistrationGetResponseOneof()
}

type RegistrationGetResponse_Success struct {
	Success *RegistrationGetSuccessResponse `protobuf:"bytes,1,opt,name=success,proto3,oneof"`
}

type RegistrationGetResponse_Fail struct {
	Fail *RegistrationFailResponse `protobuf:"bytes,2,opt,name=fail,proto3,oneof"`
}

func (*RegistrationGetResponse_Success) isRegistrationGetResponse_RegistrationGetResponseOneof() {}

func (*RegistrationGetResponse_Fail) isRegistrationGetResponse_RegistrationGetResponseOneof() {}

type RegistrationDeleteRequest struct {
	state                   protoimpl.MessageState `protogen:"open.v1"`
	ClientId                string                 `protobuf:"bytes,1,opt,name=client_id,json=clientId,proto3" json:"client_id,omitempty"`
	RegistrationAccessToken string                 `protobuf:"bytes,2,opt,name=registration_access_token,json=registrationAccessToken,proto3" json:"registration_access_token,omitempty"`
	unknownFields           protoimpl.UnknownFields
	sizeCache               protoimpl.SizeCache
}

func (x *RegistrationDeleteRequest) Reset() {
	*x = RegistrationDeleteRequest{}
	mi := &file_oppb_v1_registration_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegistrationDeleteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegistrationDeleteRequest) ProtoMessage() {}

func (x *RegistrationDeleteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_oppb_v1_registration_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegistrationDeleteRequest.ProtoReflect.Descriptor instead.
func (*RegistrationDeleteRequest) Descriptor() ([]byte, []int) {
	return file_oppb_v1_registration_proto_rawDescGZIP(), []int{4}
}

func (x *RegistrationDeleteRequest) GetClientId() string {
	if x != nil {
		return x.ClientId
	}
	return ""
}

func (x *RegistrationDeleteRequest) GetRegistrationAccessToken() string {
	if x != nil {
		return x.RegistrationAccessToken
	}
	return ""
}

type RegistrationDeleteResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to RegistrationDeleteResponseOneof:
	//
	//	*RegistrationDeleteResponse_Success
	//	*RegistrationDeleteResponse_Fail
	RegistrationDeleteResponseOneof isRegistrationDeleteResponse_RegistrationDeleteResponseOneof `protobuf_oneof:"registration_delete_response_oneof"`
	unknownFields                   protoimpl.UnknownFields
	sizeCache                       protoimpl.SizeCache
}

func (x *RegistrationDeleteResponse) Reset() {
	*x = RegistrationDeleteResponse{}
	mi := &file_oppb_v1_registration_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegistrationDeleteResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegistrationDeleteResponse) ProtoMessage() {}

func (x *RegistrationDeleteResponse) ProtoReflect() protoreflect.Message {
	mi := &file_oppb_v1_registration_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegistrationDeleteResponse.ProtoReflect.Descriptor instead.
func (*RegistrationDeleteResponse) Descriptor() ([]byte, []int) {
	return file_oppb_v1_registration_proto_rawDescGZIP(), []int{5}
}

func (x *RegistrationDeleteResponse) GetRegistrationDeleteResponseOneof() isRegistrationDeleteResponse_RegistrationDeleteResponseOneof {
	if x != nil {
		return x.RegistrationDeleteResponseOneof
	}
	return nil
}

func (x *RegistrationDeleteResponse) GetSuccess() *RegistrationDeleteSuccessResponse {
	if x != nil {
		if x, ok := x.RegistrationDeleteResponseOneof.(*RegistrationDeleteResponse_Success); ok {
			return x.Success
		}
	}
	return nil
}

func (x *RegistrationDeleteResponse) GetFail() *RegistrationFailResponse {
	if x != nil {
		if x, ok := x.RegistrationDeleteResponseOneof.(*RegistrationDeleteResponse_Fail); ok {
			return x.Fail
		}
	}
	return nil
}

type isRegistrationDeleteResponse_RegistrationDeleteResponseOneof interface {
	isRegistrationDeleteResponse_RegistrationDeleteResponseOneof()
}

type RegistrationDeleteResponse_Success struct {
	Success *RegistrationDeleteSuccessResponse `protobuf:"bytes,1,opt,name=success,proto3,oneof"`
}

type RegistrationDeleteResponse_Fail struct {
	Fail *RegistrationFailResponse `protobuf:"bytes,2,opt,name=fail,proto3,oneof"`
}

func (*RegistrationDeleteResponse_Success) isRegistrationDeleteResponse_RegistrationDeleteResponseOneof() {
}

func (*RegistrationDeleteResponse_Fail) isRegistrationDeleteResponse_RegistrationDeleteResponseOneof() {
}

type RegistrationCreateSuccessResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// ClientIdentity
	// https://openid.net/specs/openid-connect-registration-1_0.html#RegistrationResponse
	ClientId                string `protobuf:"bytes,1,opt,name=client_id,proto3" json:"client_id,omitempty"`
	ClientSecret            string `protobuf:"bytes,2,opt,name=client_secret,proto3" json:"client_secret,omitempty"`
	RegistrationAccessToken string `protobuf:"bytes,3,opt,name=registration_access_token,proto3" json:"registration_access_token,omitempty"`
	RegistrationClientUri   string `protobuf:"bytes,4,opt,name=registration_client_uri,proto3" json:"registration_client_uri,omitempty"`
	ClientIdIssuedAt        int32  `protobuf:"varint,5,opt,name=client_id_issued_at,proto3" json:"client_id_issued_at,omitempty"`
	ClientSecretExpiresAt   int32  `protobuf:"varint,6,opt,name=client_secret_expires_at,proto3" json:"client_secret_expires_at,omitempty"`
	// ClientMeta
	// https://openid.net/specs/openid-connect-registration-1_0.html#ClientMetadata
	RedirectUris                 []string `protobuf:"bytes,101,rep,name=redirect_uris,proto3" json:"redirect_uris,omitempty"`
	ResponseTypes                []string `protobuf:"bytes,102,rep,name=response_types,proto3" json:"response_types,omitempty"`
	GrantTypes                   []string `protobuf:"bytes,103,rep,name=grant_types,proto3" json:"grant_types,omitempty"`
	ApplicationType              string   `protobuf:"bytes,104,opt,name=application_type,proto3" json:"application_type,omitempty"`
	Contacts                     []string `protobuf:"bytes,105,rep,name=contacts,proto3" json:"contacts,omitempty"`
	ClientName                   string   `protobuf:"bytes,106,opt,name=client_name,proto3" json:"client_name,omitempty"`
	LogoUri                      string   `protobuf:"bytes,107,opt,name=logo_uri,proto3" json:"logo_uri,omitempty"`
	ClientUri                    string   `protobuf:"bytes,108,opt,name=client_uri,proto3" json:"client_uri,omitempty"`
	PolicyUri                    string   `protobuf:"bytes,109,opt,name=policy_uri,proto3" json:"policy_uri,omitempty"`
	TosUri                       string   `protobuf:"bytes,110,opt,name=tos_uri,proto3" json:"tos_uri,omitempty"`
	JwksUri                      string   `protobuf:"bytes,111,opt,name=jwks_uri,proto3" json:"jwks_uri,omitempty"`
	Jwks                         *Jwks    `protobuf:"bytes,112,opt,name=jwks,proto3" json:"jwks,omitempty"`
	SectorIdentifierUri          string   `protobuf:"bytes,113,opt,name=sector_identifier_uri,proto3" json:"sector_identifier_uri,omitempty"`
	SubjectType                  string   `protobuf:"bytes,114,opt,name=subject_type,proto3" json:"subject_type,omitempty"`
	IdTokenSignedResponseAlg     string   `protobuf:"bytes,115,opt,name=id_token_signed_response_alg,proto3" json:"id_token_signed_response_alg,omitempty"`
	IdTokenEncryptedResponseAlg  string   `protobuf:"bytes,116,opt,name=id_token_encrypted_response_alg,proto3" json:"id_token_encrypted_response_alg,omitempty"`
	IdTokenEncryptedResponseEnc  string   `protobuf:"bytes,117,opt,name=id_token_encrypted_response_enc,proto3" json:"id_token_encrypted_response_enc,omitempty"`
	UserinfoSignedResponseAlg    string   `protobuf:"bytes,118,opt,name=userinfo_signed_response_alg,proto3" json:"userinfo_signed_response_alg,omitempty"`
	UserinfoEncryptedResponseAlg string   `protobuf:"bytes,119,opt,name=userinfo_encrypted_response_alg,proto3" json:"userinfo_encrypted_response_alg,omitempty"`
	UserinfoEncryptedResponseEnc string   `protobuf:"bytes,120,opt,name=userinfo_encrypted_response_enc,proto3" json:"userinfo_encrypted_response_enc,omitempty"`
	RequestObjectSigningAlg      string   `protobuf:"bytes,121,opt,name=request_object_signing_alg,proto3" json:"request_object_signing_alg,omitempty"`
	RequestObjectEncryptionAlg   string   `protobuf:"bytes,122,opt,name=request_object_encryption_alg,proto3" json:"request_object_encryption_alg,omitempty"`
	RequestObjectEncryptionEnc   string   `protobuf:"bytes,123,opt,name=request_object_encryption_enc,proto3" json:"request_object_encryption_enc,omitempty"`
	TokenEndpointAuthMethod      string   `protobuf:"bytes,124,opt,name=token_endpoint_auth_method,proto3" json:"token_endpoint_auth_method,omitempty"`
	TokenEndpointAuthSigningAlg  string   `protobuf:"bytes,125,opt,name=token_endpoint_auth_signing_alg,proto3" json:"token_endpoint_auth_signing_alg,omitempty"`
	DefaultMaxAge                string   `protobuf:"bytes,126,opt,name=default_max_age,proto3" json:"default_max_age,omitempty"`
	RequireAuthTime              bool     `protobuf:"varint,127,opt,name=require_auth_time,proto3" json:"require_auth_time,omitempty"`
	DefaultAcrValues             []string `protobuf:"bytes,128,rep,name=default_acr_values,proto3" json:"default_acr_values,omitempty"`
	InitiateLoginUri             string   `protobuf:"bytes,129,opt,name=initiate_login_uri,proto3" json:"initiate_login_uri,omitempty"`
	RequestUris                  []string `protobuf:"bytes,130,rep,name=request_uris,proto3" json:"request_uris,omitempty"`
	// https://openid.net/specs/openid-connect-rpinitiated-1_0.html#ClientMetadata
	PostLogoutRedirectUris []string `protobuf:"bytes,131,rep,name=post_logout_redirect_uris,proto3" json:"post_logout_redirect_uris,omitempty"`
	// https://www.rfc-editor.org/rfc/rfc9126.html#section-6
	RequirePushedAuthorizationRequests bool `protobuf:"varint,132,opt,name=require_pushed_authorization_requests,proto3" json:"require_pushed_authorization_requests,omitempty"`
	// https://openid.net/specs/openid-financial-api-jarm.html#client-metadata
	AuthorizationSignedResponseAlg    string `protobuf:"bytes,133,opt,name=authorization_signed_response_alg,proto3" json:"authorization_signed_response_alg,omitempty"`
	AuthorizationEncryptedResponseAlg string `protobuf:"bytes,134,opt,name=authorization_encrypted_response_alg,proto3" json:"authorization_encrypted_response_alg,omitempty"`
	AuthorizationEncryptedResponseEnc string `protobuf:"bytes,135,opt,name=authorization_encrypted_response_enc,proto3" json:"authorization_encrypted_response_enc,omitempty"`
	// https://datatracker.ietf.org/doc/html/rfc8705#section-3.4
	TlsClientCertificateBoundAccessTokens bool `protobuf:"varint,136,opt,name=tls_client_certificate_bound_access_tokens,proto3" json:"tls_client_certificate_bound_access_tokens,omitempty"`
	unknownFields                         protoimpl.UnknownFields
	sizeCache                             protoimpl.SizeCache
}

func (x *RegistrationCreateSuccessResponse) Reset() {
	*x = RegistrationCreateSuccessResponse{}
	mi := &file_oppb_v1_registration_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegistrationCreateSuccessResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegistrationCreateSuccessResponse) ProtoMessage() {}

func (x *RegistrationCreateSuccessResponse) ProtoReflect() protoreflect.Message {
	mi := &file_oppb_v1_registration_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegistrationCreateSuccessResponse.ProtoReflect.Descriptor instead.
func (*RegistrationCreateSuccessResponse) Descriptor() ([]byte, []int) {
	return file_oppb_v1_registration_proto_rawDescGZIP(), []int{6}
}

func (x *RegistrationCreateSuccessResponse) GetClientId() string {
	if x != nil {
		return x.ClientId
	}
	return ""
}

func (x *RegistrationCreateSuccessResponse) GetClientSecret() string {
	if x != nil {
		return x.ClientSecret
	}
	return ""
}

func (x *RegistrationCreateSuccessResponse) GetRegistrationAccessToken() string {
	if x != nil {
		return x.RegistrationAccessToken
	}
	return ""
}

func (x *RegistrationCreateSuccessResponse) GetRegistrationClientUri() string {
	if x != nil {
		return x.RegistrationClientUri
	}
	return ""
}

func (x *RegistrationCreateSuccessResponse) GetClientIdIssuedAt() int32 {
	if x != nil {
		return x.ClientIdIssuedAt
	}
	return 0
}

func (x *RegistrationCreateSuccessResponse) GetClientSecretExpiresAt() int32 {
	if x != nil {
		return x.ClientSecretExpiresAt
	}
	return 0
}

func (x *RegistrationCreateSuccessResponse) GetRedirectUris() []string {
	if x != nil {
		return x.RedirectUris
	}
	return nil
}

func (x *RegistrationCreateSuccessResponse) GetResponseTypes() []string {
	if x != nil {
		return x.ResponseTypes
	}
	return nil
}

func (x *RegistrationCreateSuccessResponse) GetGrantTypes() []string {
	if x != nil {
		return x.GrantTypes
	}
	return nil
}

func (x *RegistrationCreateSuccessResponse) GetApplicationType() string {
	if x != nil {
		return x.ApplicationType
	}
	return ""
}

func (x *RegistrationCreateSuccessResponse) GetContacts() []string {
	if x != nil {
		return x.Contacts
	}
	return nil
}

func (x *RegistrationCreateSuccessResponse) GetClientName() string {
	if x != nil {
		return x.ClientName
	}
	return ""
}

func (x *RegistrationCreateSuccessResponse) GetLogoUri() string {
	if x != nil {
		return x.LogoUri
	}
	return ""
}

func (x *RegistrationCreateSuccessResponse) GetClientUri() string {
	if x != nil {
		return x.ClientUri
	}
	return ""
}

func (x *RegistrationCreateSuccessResponse) GetPolicyUri() string {
	if x != nil {
		return x.PolicyUri
	}
	return ""
}

func (x *RegistrationCreateSuccessResponse) GetTosUri() string {
	if x != nil {
		return x.TosUri
	}
	return ""
}

func (x *RegistrationCreateSuccessResponse) GetJwksUri() string {
	if x != nil {
		return x.JwksUri
	}
	return ""
}

func (x *RegistrationCreateSuccessResponse) GetJwks() *Jwks {
	if x != nil {
		return x.Jwks
	}
	return nil
}

func (x *RegistrationCreateSuccessResponse) GetSectorIdentifierUri() string {
	if x != nil {
		return x.SectorIdentifierUri
	}
	return ""
}

func (x *RegistrationCreateSuccessResponse) GetSubjectType() string {
	if x != nil {
		return x.SubjectType
	}
	return ""
}

func (x *RegistrationCreateSuccessResponse) GetIdTokenSignedResponseAlg() string {
	if x != nil {
		return x.IdTokenSignedResponseAlg
	}
	return ""
}

func (x *RegistrationCreateSuccessResponse) GetIdTokenEncryptedResponseAlg() string {
	if x != nil {
		return x.IdTokenEncryptedResponseAlg
	}
	return ""
}

func (x *RegistrationCreateSuccessResponse) GetIdTokenEncryptedResponseEnc() string {
	if x != nil {
		return x.IdTokenEncryptedResponseEnc
	}
	return ""
}

func (x *RegistrationCreateSuccessResponse) GetUserinfoSignedResponseAlg() string {
	if x != nil {
		return x.UserinfoSignedResponseAlg
	}
	return ""
}

func (x *RegistrationCreateSuccessResponse) GetUserinfoEncryptedResponseAlg() string {
	if x != nil {
		return x.UserinfoEncryptedResponseAlg
	}
	return ""
}

func (x *RegistrationCreateSuccessResponse) GetUserinfoEncryptedResponseEnc() string {
	if x != nil {
		return x.UserinfoEncryptedResponseEnc
	}
	return ""
}

func (x *RegistrationCreateSuccessResponse) GetRequestObjectSigningAlg() string {
	if x != nil {
		return x.RequestObjectSigningAlg
	}
	return ""
}

func (x *RegistrationCreateSuccessResponse) GetRequestObjectEncryptionAlg() string {
	if x != nil {
		return x.RequestObjectEncryptionAlg
	}
	return ""
}

func (x *RegistrationCreateSuccessResponse) GetRequestObjectEncryptionEnc() string {
	if x != nil {
		return x.RequestObjectEncryptionEnc
	}
	return ""
}

func (x *RegistrationCreateSuccessResponse) GetTokenEndpointAuthMethod() string {
	if x != nil {
		return x.TokenEndpointAuthMethod
	}
	return ""
}

func (x *RegistrationCreateSuccessResponse) GetTokenEndpointAuthSigningAlg() string {
	if x != nil {
		return x.TokenEndpointAuthSigningAlg
	}
	return ""
}

func (x *RegistrationCreateSuccessResponse) GetDefaultMaxAge() string {
	if x != nil {
		return x.DefaultMaxAge
	}
	return ""
}

func (x *RegistrationCreateSuccessResponse) GetRequireAuthTime() bool {
	if x != nil {
		return x.RequireAuthTime
	}
	return false
}

func (x *RegistrationCreateSuccessResponse) GetDefaultAcrValues() []string {
	if x != nil {
		return x.DefaultAcrValues
	}
	return nil
}

func (x *RegistrationCreateSuccessResponse) GetInitiateLoginUri() string {
	if x != nil {
		return x.InitiateLoginUri
	}
	return ""
}

func (x *RegistrationCreateSuccessResponse) GetRequestUris() []string {
	if x != nil {
		return x.RequestUris
	}
	return nil
}

func (x *RegistrationCreateSuccessResponse) GetPostLogoutRedirectUris() []string {
	if x != nil {
		return x.PostLogoutRedirectUris
	}
	return nil
}

func (x *RegistrationCreateSuccessResponse) GetRequirePushedAuthorizationRequests() bool {
	if x != nil {
		return x.RequirePushedAuthorizationRequests
	}
	return false
}

func (x *RegistrationCreateSuccessResponse) GetAuthorizationSignedResponseAlg() string {
	if x != nil {
		return x.AuthorizationSignedResponseAlg
	}
	return ""
}

func (x *RegistrationCreateSuccessResponse) GetAuthorizationEncryptedResponseAlg() string {
	if x != nil {
		return x.AuthorizationEncryptedResponseAlg
	}
	return ""
}

func (x *RegistrationCreateSuccessResponse) GetAuthorizationEncryptedResponseEnc() string {
	if x != nil {
		return x.AuthorizationEncryptedResponseEnc
	}
	return ""
}

func (x *RegistrationCreateSuccessResponse) GetTlsClientCertificateBoundAccessTokens() bool {
	if x != nil {
		return x.TlsClientCertificateBoundAccessTokens
	}
	return false
}

type RegistrationGetSuccessResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// ClientIdentity
	// https://openid.net/specs/openid-connect-registration-1_0.html#RegistrationResponse
	ClientId     string `protobuf:"bytes,1,opt,name=client_id,proto3" json:"client_id,omitempty"`
	ClientSecret string `protobuf:"bytes,2,opt,name=client_secret,proto3" json:"client_secret,omitempty"`
	// string registration_access_token = 3 [json_name = "registration_access_token"];
	// string registration_client_uri = 4 [json_name = "registration_client_uri"];
	ClientIdIssuedAt      int32 `protobuf:"varint,5,opt,name=client_id_issued_at,proto3" json:"client_id_issued_at,omitempty"`
	ClientSecretExpiresAt int32 `protobuf:"varint,6,opt,name=client_secret_expires_at,proto3" json:"client_secret_expires_at,omitempty"`
	// ClientMeta
	// https://openid.net/specs/openid-connect-registration-1_0.html#ClientMetadata
	RedirectUris                 []string `protobuf:"bytes,101,rep,name=redirect_uris,proto3" json:"redirect_uris,omitempty"`
	ResponseTypes                []string `protobuf:"bytes,102,rep,name=response_types,proto3" json:"response_types,omitempty"`
	GrantTypes                   []string `protobuf:"bytes,103,rep,name=grant_types,proto3" json:"grant_types,omitempty"`
	ApplicationType              string   `protobuf:"bytes,104,opt,name=application_type,proto3" json:"application_type,omitempty"`
	Contacts                     []string `protobuf:"bytes,105,rep,name=contacts,proto3" json:"contacts,omitempty"`
	ClientName                   string   `protobuf:"bytes,106,opt,name=client_name,proto3" json:"client_name,omitempty"`
	LogoUri                      string   `protobuf:"bytes,107,opt,name=logo_uri,proto3" json:"logo_uri,omitempty"`
	ClientUri                    string   `protobuf:"bytes,108,opt,name=client_uri,proto3" json:"client_uri,omitempty"`
	PolicyUri                    string   `protobuf:"bytes,109,opt,name=policy_uri,proto3" json:"policy_uri,omitempty"`
	TosUri                       string   `protobuf:"bytes,110,opt,name=tos_uri,proto3" json:"tos_uri,omitempty"`
	JwksUri                      string   `protobuf:"bytes,111,opt,name=jwks_uri,proto3" json:"jwks_uri,omitempty"`
	Jwks                         *Jwks    `protobuf:"bytes,112,opt,name=jwks,proto3" json:"jwks,omitempty"`
	SectorIdentifierUri          string   `protobuf:"bytes,113,opt,name=sector_identifier_uri,proto3" json:"sector_identifier_uri,omitempty"`
	SubjectType                  string   `protobuf:"bytes,114,opt,name=subject_type,proto3" json:"subject_type,omitempty"`
	IdTokenSignedResponseAlg     string   `protobuf:"bytes,115,opt,name=id_token_signed_response_alg,proto3" json:"id_token_signed_response_alg,omitempty"`
	IdTokenEncryptedResponseAlg  string   `protobuf:"bytes,116,opt,name=id_token_encrypted_response_alg,proto3" json:"id_token_encrypted_response_alg,omitempty"`
	IdTokenEncryptedResponseEnc  string   `protobuf:"bytes,117,opt,name=id_token_encrypted_response_enc,proto3" json:"id_token_encrypted_response_enc,omitempty"`
	UserinfoSignedResponseAlg    string   `protobuf:"bytes,118,opt,name=userinfo_signed_response_alg,proto3" json:"userinfo_signed_response_alg,omitempty"`
	UserinfoEncryptedResponseAlg string   `protobuf:"bytes,119,opt,name=userinfo_encrypted_response_alg,proto3" json:"userinfo_encrypted_response_alg,omitempty"`
	UserinfoEncryptedResponseEnc string   `protobuf:"bytes,120,opt,name=userinfo_encrypted_response_enc,proto3" json:"userinfo_encrypted_response_enc,omitempty"`
	RequestObjectSigningAlg      string   `protobuf:"bytes,121,opt,name=request_object_signing_alg,proto3" json:"request_object_signing_alg,omitempty"`
	RequestObjectEncryptionAlg   string   `protobuf:"bytes,122,opt,name=request_object_encryption_alg,proto3" json:"request_object_encryption_alg,omitempty"`
	RequestObjectEncryptionEnc   string   `protobuf:"bytes,123,opt,name=request_object_encryption_enc,proto3" json:"request_object_encryption_enc,omitempty"`
	TokenEndpointAuthMethod      string   `protobuf:"bytes,124,opt,name=token_endpoint_auth_method,proto3" json:"token_endpoint_auth_method,omitempty"`
	TokenEndpointAuthSigningAlg  string   `protobuf:"bytes,125,opt,name=token_endpoint_auth_signing_alg,proto3" json:"token_endpoint_auth_signing_alg,omitempty"`
	DefaultMaxAge                string   `protobuf:"bytes,126,opt,name=default_max_age,proto3" json:"default_max_age,omitempty"`
	RequireAuthTime              bool     `protobuf:"varint,127,opt,name=require_auth_time,proto3" json:"require_auth_time,omitempty"`
	DefaultAcrValues             []string `protobuf:"bytes,128,rep,name=default_acr_values,proto3" json:"default_acr_values,omitempty"`
	InitiateLoginUri             string   `protobuf:"bytes,129,opt,name=initiate_login_uri,proto3" json:"initiate_login_uri,omitempty"`
	RequestUris                  []string `protobuf:"bytes,130,rep,name=request_uris,proto3" json:"request_uris,omitempty"`
	// https://openid.net/specs/openid-connect-rpinitiated-1_0.html#ClientMetadata
	PostLogoutRedirectUris []string `protobuf:"bytes,131,rep,name=post_logout_redirect_uris,proto3" json:"post_logout_redirect_uris,omitempty"`
	// https://www.rfc-editor.org/rfc/rfc9126.html#section-6
	RequirePushedAuthorizationRequests bool `protobuf:"varint,132,opt,name=require_pushed_authorization_requests,proto3" json:"require_pushed_authorization_requests,omitempty"`
	// https://openid.net/specs/openid-financial-api-jarm.html#client-metadata
	AuthorizationSignedResponseAlg    string `protobuf:"bytes,133,opt,name=authorization_signed_response_alg,proto3" json:"authorization_signed_response_alg,omitempty"`
	AuthorizationEncryptedResponseAlg string `protobuf:"bytes,134,opt,name=authorization_encrypted_response_alg,proto3" json:"authorization_encrypted_response_alg,omitempty"`
	AuthorizationEncryptedResponseEnc string `protobuf:"bytes,135,opt,name=authorization_encrypted_response_enc,proto3" json:"authorization_encrypted_response_enc,omitempty"`
	// https://datatracker.ietf.org/doc/html/rfc8705#section-3.4
	TlsClientCertificateBoundAccessTokens bool `protobuf:"varint,136,opt,name=tls_client_certificate_bound_access_tokens,proto3" json:"tls_client_certificate_bound_access_tokens,omitempty"`
	unknownFields                         protoimpl.UnknownFields
	sizeCache                             protoimpl.SizeCache
}

func (x *RegistrationGetSuccessResponse) Reset() {
	*x = RegistrationGetSuccessResponse{}
	mi := &file_oppb_v1_registration_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegistrationGetSuccessResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegistrationGetSuccessResponse) ProtoMessage() {}

func (x *RegistrationGetSuccessResponse) ProtoReflect() protoreflect.Message {
	mi := &file_oppb_v1_registration_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegistrationGetSuccessResponse.ProtoReflect.Descriptor instead.
func (*RegistrationGetSuccessResponse) Descriptor() ([]byte, []int) {
	return file_oppb_v1_registration_proto_rawDescGZIP(), []int{7}
}

func (x *RegistrationGetSuccessResponse) GetClientId() string {
	if x != nil {
		return x.ClientId
	}
	return ""
}

func (x *RegistrationGetSuccessResponse) GetClientSecret() string {
	if x != nil {
		return x.ClientSecret
	}
	return ""
}

func (x *RegistrationGetSuccessResponse) GetClientIdIssuedAt() int32 {
	if x != nil {
		return x.ClientIdIssuedAt
	}
	return 0
}

func (x *RegistrationGetSuccessResponse) GetClientSecretExpiresAt() int32 {
	if x != nil {
		return x.ClientSecretExpiresAt
	}
	return 0
}

func (x *RegistrationGetSuccessResponse) GetRedirectUris() []string {
	if x != nil {
		return x.RedirectUris
	}
	return nil
}

func (x *RegistrationGetSuccessResponse) GetResponseTypes() []string {
	if x != nil {
		return x.ResponseTypes
	}
	return nil
}

func (x *RegistrationGetSuccessResponse) GetGrantTypes() []string {
	if x != nil {
		return x.GrantTypes
	}
	return nil
}

func (x *RegistrationGetSuccessResponse) GetApplicationType() string {
	if x != nil {
		return x.ApplicationType
	}
	return ""
}

func (x *RegistrationGetSuccessResponse) GetContacts() []string {
	if x != nil {
		return x.Contacts
	}
	return nil
}

func (x *RegistrationGetSuccessResponse) GetClientName() string {
	if x != nil {
		return x.ClientName
	}
	return ""
}

func (x *RegistrationGetSuccessResponse) GetLogoUri() string {
	if x != nil {
		return x.LogoUri
	}
	return ""
}

func (x *RegistrationGetSuccessResponse) GetClientUri() string {
	if x != nil {
		return x.ClientUri
	}
	return ""
}

func (x *RegistrationGetSuccessResponse) GetPolicyUri() string {
	if x != nil {
		return x.PolicyUri
	}
	return ""
}

func (x *RegistrationGetSuccessResponse) GetTosUri() string {
	if x != nil {
		return x.TosUri
	}
	return ""
}

func (x *RegistrationGetSuccessResponse) GetJwksUri() string {
	if x != nil {
		return x.JwksUri
	}
	return ""
}

func (x *RegistrationGetSuccessResponse) GetJwks() *Jwks {
	if x != nil {
		return x.Jwks
	}
	return nil
}

func (x *RegistrationGetSuccessResponse) GetSectorIdentifierUri() string {
	if x != nil {
		return x.SectorIdentifierUri
	}
	return ""
}

func (x *RegistrationGetSuccessResponse) GetSubjectType() string {
	if x != nil {
		return x.SubjectType
	}
	return ""
}

func (x *RegistrationGetSuccessResponse) GetIdTokenSignedResponseAlg() string {
	if x != nil {
		return x.IdTokenSignedResponseAlg
	}
	return ""
}

func (x *RegistrationGetSuccessResponse) GetIdTokenEncryptedResponseAlg() string {
	if x != nil {
		return x.IdTokenEncryptedResponseAlg
	}
	return ""
}

func (x *RegistrationGetSuccessResponse) GetIdTokenEncryptedResponseEnc() string {
	if x != nil {
		return x.IdTokenEncryptedResponseEnc
	}
	return ""
}

func (x *RegistrationGetSuccessResponse) GetUserinfoSignedResponseAlg() string {
	if x != nil {
		return x.UserinfoSignedResponseAlg
	}
	return ""
}

func (x *RegistrationGetSuccessResponse) GetUserinfoEncryptedResponseAlg() string {
	if x != nil {
		return x.UserinfoEncryptedResponseAlg
	}
	return ""
}

func (x *RegistrationGetSuccessResponse) GetUserinfoEncryptedResponseEnc() string {
	if x != nil {
		return x.UserinfoEncryptedResponseEnc
	}
	return ""
}

func (x *RegistrationGetSuccessResponse) GetRequestObjectSigningAlg() string {
	if x != nil {
		return x.RequestObjectSigningAlg
	}
	return ""
}

func (x *RegistrationGetSuccessResponse) GetRequestObjectEncryptionAlg() string {
	if x != nil {
		return x.RequestObjectEncryptionAlg
	}
	return ""
}

func (x *RegistrationGetSuccessResponse) GetRequestObjectEncryptionEnc() string {
	if x != nil {
		return x.RequestObjectEncryptionEnc
	}
	return ""
}

func (x *RegistrationGetSuccessResponse) GetTokenEndpointAuthMethod() string {
	if x != nil {
		return x.TokenEndpointAuthMethod
	}
	return ""
}

func (x *RegistrationGetSuccessResponse) GetTokenEndpointAuthSigningAlg() string {
	if x != nil {
		return x.TokenEndpointAuthSigningAlg
	}
	return ""
}

func (x *RegistrationGetSuccessResponse) GetDefaultMaxAge() string {
	if x != nil {
		return x.DefaultMaxAge
	}
	return ""
}

func (x *RegistrationGetSuccessResponse) GetRequireAuthTime() bool {
	if x != nil {
		return x.RequireAuthTime
	}
	return false
}

func (x *RegistrationGetSuccessResponse) GetDefaultAcrValues() []string {
	if x != nil {
		return x.DefaultAcrValues
	}
	return nil
}

func (x *RegistrationGetSuccessResponse) GetInitiateLoginUri() string {
	if x != nil {
		return x.InitiateLoginUri
	}
	return ""
}

func (x *RegistrationGetSuccessResponse) GetRequestUris() []string {
	if x != nil {
		return x.RequestUris
	}
	return nil
}

func (x *RegistrationGetSuccessResponse) GetPostLogoutRedirectUris() []string {
	if x != nil {
		return x.PostLogoutRedirectUris
	}
	return nil
}

func (x *RegistrationGetSuccessResponse) GetRequirePushedAuthorizationRequests() bool {
	if x != nil {
		return x.RequirePushedAuthorizationRequests
	}
	return false
}

func (x *RegistrationGetSuccessResponse) GetAuthorizationSignedResponseAlg() string {
	if x != nil {
		return x.AuthorizationSignedResponseAlg
	}
	return ""
}

func (x *RegistrationGetSuccessResponse) GetAuthorizationEncryptedResponseAlg() string {
	if x != nil {
		return x.AuthorizationEncryptedResponseAlg
	}
	return ""
}

func (x *RegistrationGetSuccessResponse) GetAuthorizationEncryptedResponseEnc() string {
	if x != nil {
		return x.AuthorizationEncryptedResponseEnc
	}
	return ""
}

func (x *RegistrationGetSuccessResponse) GetTlsClientCertificateBoundAccessTokens() bool {
	if x != nil {
		return x.TlsClientCertificateBoundAccessTokens
	}
	return false
}

type RegistrationDeleteSuccessResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegistrationDeleteSuccessResponse) Reset() {
	*x = RegistrationDeleteSuccessResponse{}
	mi := &file_oppb_v1_registration_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegistrationDeleteSuccessResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegistrationDeleteSuccessResponse) ProtoMessage() {}

func (x *RegistrationDeleteSuccessResponse) ProtoReflect() protoreflect.Message {
	mi := &file_oppb_v1_registration_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegistrationDeleteSuccessResponse.ProtoReflect.Descriptor instead.
func (*RegistrationDeleteSuccessResponse) Descriptor() ([]byte, []int) {
	return file_oppb_v1_registration_proto_rawDescGZIP(), []int{8}
}

type RegistrationFailResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StatusCode    int32                  `protobuf:"varint,1,opt,name=status_code,json=statusCode,proto3" json:"status_code,omitempty"`
	Error         *RegistrationError     `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegistrationFailResponse) Reset() {
	*x = RegistrationFailResponse{}
	mi := &file_oppb_v1_registration_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegistrationFailResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegistrationFailResponse) ProtoMessage() {}

func (x *RegistrationFailResponse) ProtoReflect() protoreflect.Message {
	mi := &file_oppb_v1_registration_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegistrationFailResponse.ProtoReflect.Descriptor instead.
func (*RegistrationFailResponse) Descriptor() ([]byte, []int) {
	return file_oppb_v1_registration_proto_rawDescGZIP(), []int{9}
}

func (x *RegistrationFailResponse) GetStatusCode() int32 {
	if x != nil {
		return x.StatusCode
	}
	return 0
}

func (x *RegistrationFailResponse) GetError() *RegistrationError {
	if x != nil {
		return x.Error
	}
	return nil
}

// https://openid.net/specs/openid-connect-registration-1_0.html#RegistrationError
type RegistrationError struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Error            string                 `protobuf:"bytes,1,opt,name=error,proto3" json:"error,omitempty"`
	ErrorDescription string                 `protobuf:"bytes,2,opt,name=error_description,json=errorDescription,proto3" json:"error_description,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *RegistrationError) Reset() {
	*x = RegistrationError{}
	mi := &file_oppb_v1_registration_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegistrationError) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegistrationError) ProtoMessage() {}

func (x *RegistrationError) ProtoReflect() protoreflect.Message {
	mi := &file_oppb_v1_registration_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegistrationError.ProtoReflect.Descriptor instead.
func (*RegistrationError) Descriptor() ([]byte, []int) {
	return file_oppb_v1_registration_proto_rawDescGZIP(), []int{10}
}

func (x *RegistrationError) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *RegistrationError) GetErrorDescription() string {
	if x != nil {
		return x.ErrorDescription
	}
	return ""
}

var File_oppb_v1_registration_proto protoreflect.FileDescriptor

const file_oppb_v1_registration_proto_rawDesc = "" +
	"\n" +
	"\x1aoppb/v1/registration.proto\x12\aoppb.v1\x1a\x12oppb/v1/jwks.proto\"\xd9\x0f\n" +
	"\x19RegistrationCreateRequest\x12$\n" +
	"\rredirect_uris\x18e \x03(\tR\rredirect_uris\x12&\n" +
	"\x0eresponse_types\x18f \x03(\tR\x0eresponse_types\x12 \n" +
	"\vgrant_types\x18g \x03(\tR\vgrant_types\x12*\n" +
	"\x10application_type\x18h \x01(\tR\x10application_type\x12\x1a\n" +
	"\bcontacts\x18i \x03(\tR\bcontacts\x12 \n" +
	"\vclient_name\x18j \x01(\tR\vclient_name\x12\x1a\n" +
	"\blogo_uri\x18k \x01(\tR\blogo_uri\x12\x1e\n" +
	"\n" +
	"client_uri\x18l \x01(\tR\n" +
	"client_uri\x12\x1e\n" +
	"\n" +
	"policy_uri\x18m \x01(\tR\n" +
	"policy_uri\x12\x18\n" +
	"\atos_uri\x18n \x01(\tR\atos_uri\x12\x1a\n" +
	"\bjwks_uri\x18o \x01(\tR\bjwks_uri\x12!\n" +
	"\x04jwks\x18p \x01(\v2\r.oppb.v1.JwksR\x04jwks\x124\n" +
	"\x15sector_identifier_uri\x18q \x01(\tR\x15sector_identifier_uri\x12\"\n" +
	"\fsubject_type\x18r \x01(\tR\fsubject_type\x12B\n" +
	"\x1cid_token_signed_response_alg\x18s \x01(\tR\x1cid_token_signed_response_alg\x12H\n" +
	"\x1fid_token_encrypted_response_alg\x18t \x01(\tR\x1fid_token_encrypted_response_alg\x12H\n" +
	"\x1fid_token_encrypted_response_enc\x18u \x01(\tR\x1fid_token_encrypted_response_enc\x12B\n" +
	"\x1cuserinfo_signed_response_alg\x18v \x01(\tR\x1cuserinfo_signed_response_alg\x12H\n" +
	"\x1fuserinfo_encrypted_response_alg\x18w \x01(\tR\x1fuserinfo_encrypted_response_alg\x12H\n" +
	"\x1fuserinfo_encrypted_response_enc\x18x \x01(\tR\x1fuserinfo_encrypted_response_enc\x12>\n" +
	"\x1arequest_object_signing_alg\x18y \x01(\tR\x1arequest_object_signing_alg\x12D\n" +
	"\x1drequest_object_encryption_alg\x18z \x01(\tR\x1drequest_object_encryption_alg\x12D\n" +
	"\x1drequest_object_encryption_enc\x18{ \x01(\tR\x1drequest_object_encryption_enc\x12>\n" +
	"\x1atoken_endpoint_auth_method\x18| \x01(\tR\x1atoken_endpoint_auth_method\x12H\n" +
	"\x1ftoken_endpoint_auth_signing_alg\x18} \x01(\tR\x1ftoken_endpoint_auth_signing_alg\x12(\n" +
	"\x0fdefault_max_age\x18~ \x01(\tR\x0fdefault_max_age\x12,\n" +
	"\x11require_auth_time\x18\x7f \x01(\bR\x11require_auth_time\x12/\n" +
	"\x12default_acr_values\x18\x80\x01 \x03(\tR\x12default_acr_values\x12/\n" +
	"\x12initiate_login_uri\x18\x81\x01 \x01(\tR\x12initiate_login_uri\x12#\n" +
	"\frequest_uris\x18\x82\x01 \x03(\tR\frequest_uris\x12=\n" +
	"\x19post_logout_redirect_uris\x18\x83\x01 \x03(\tR\x19post_logout_redirect_uris\x12U\n" +
	"%require_pushed_authorization_requests\x18\x84\x01 \x01(\bR%require_pushed_authorization_requests\x12M\n" +
	"!authorization_signed_response_alg\x18\x85\x01 \x01(\tR!authorization_signed_response_alg\x12S\n" +
	"$authorization_encrypted_response_alg\x18\x86\x01 \x01(\tR$authorization_encrypted_response_alg\x12S\n" +
	"$authorization_encrypted_response_enc\x18\x87\x01 \x01(\tR$authorization_encrypted_response_enc\x12_\n" +
	"*tls_client_certificate_bound_access_tokens\x18\x88\x01 \x01(\bR*tls_client_certificate_bound_access_tokens\"\xc3\x01\n" +
	"\x1aRegistrationCreateResponse\x12F\n" +
	"\asuccess\x18\x01 \x01(\v2*.oppb.v1.RegistrationCreateSuccessResponseH\x00R\asuccess\x127\n" +
	"\x04fail\x18\x02 \x01(\v2!.oppb.v1.RegistrationFailResponseH\x00R\x04failB$\n" +
	"\"registration_create_response_oneof\"q\n" +
	"\x16RegistrationGetRequest\x12\x1b\n" +
	"\tclient_id\x18\x01 \x01(\tR\bclientId\x12:\n" +
	"\x19registration_access_token\x18\x02 \x01(\tR\x17registrationAccessToken\"\xba\x01\n" +
	"\x17RegistrationGetResponse\x12C\n" +
	"\asuccess\x18\x01 \x01(\v2'.oppb.v1.RegistrationGetSuccessResponseH\x00R\asuccess\x127\n" +
	"\x04fail\x18\x02 \x01(\v2!.oppb.v1.RegistrationFailResponseH\x00R\x04failB!\n" +
	"\x1fregistration_get_response_oneof\"t\n" +
	"\x19RegistrationDeleteRequest\x12\x1b\n" +
	"\tclient_id\x18\x01 \x01(\tR\bclientId\x12:\n" +
	"\x19registration_access_token\x18\x02 \x01(\tR\x17registrationAccessToken\"\xc3\x01\n" +
	"\x1aRegistrationDeleteResponse\x12F\n" +
	"\asuccess\x18\x01 \x01(\v2*.oppb.v1.RegistrationDeleteSuccessResponseH\x00R\asuccess\x127\n" +
	"\x04fail\x18\x02 \x01(\v2!.oppb.v1.RegistrationFailResponseH\x00R\x04failB$\n" +
	"\"registration_delete_response_oneof\"\x8b\x12\n" +
	"!RegistrationCreateSuccessResponse\x12\x1c\n" +
	"\tclient_id\x18\x01 \x01(\tR\tclient_id\x12$\n" +
	"\rclient_secret\x18\x02 \x01(\tR\rclient_secret\x12<\n" +
	"\x19registration_access_token\x18\x03 \x01(\tR\x19registration_access_token\x128\n" +
	"\x17registration_client_uri\x18\x04 \x01(\tR\x17registration_client_uri\x120\n" +
	"\x13client_id_issued_at\x18\x05 \x01(\x05R\x13client_id_issued_at\x12:\n" +
	"\x18client_secret_expires_at\x18\x06 \x01(\x05R\x18client_secret_expires_at\x12$\n" +
	"\rredirect_uris\x18e \x03(\tR\rredirect_uris\x12&\n" +
	"\x0eresponse_types\x18f \x03(\tR\x0eresponse_types\x12 \n" +
	"\vgrant_types\x18g \x03(\tR\vgrant_types\x12*\n" +
	"\x10application_type\x18h \x01(\tR\x10application_type\x12\x1a\n" +
	"\bcontacts\x18i \x03(\tR\bcontacts\x12 \n" +
	"\vclient_name\x18j \x01(\tR\vclient_name\x12\x1a\n" +
	"\blogo_uri\x18k \x01(\tR\blogo_uri\x12\x1e\n" +
	"\n" +
	"client_uri\x18l \x01(\tR\n" +
	"client_uri\x12\x1e\n" +
	"\n" +
	"policy_uri\x18m \x01(\tR\n" +
	"policy_uri\x12\x18\n" +
	"\atos_uri\x18n \x01(\tR\atos_uri\x12\x1a\n" +
	"\bjwks_uri\x18o \x01(\tR\bjwks_uri\x12!\n" +
	"\x04jwks\x18p \x01(\v2\r.oppb.v1.JwksR\x04jwks\x124\n" +
	"\x15sector_identifier_uri\x18q \x01(\tR\x15sector_identifier_uri\x12\"\n" +
	"\fsubject_type\x18r \x01(\tR\fsubject_type\x12B\n" +
	"\x1cid_token_signed_response_alg\x18s \x01(\tR\x1cid_token_signed_response_alg\x12H\n" +
	"\x1fid_token_encrypted_response_alg\x18t \x01(\tR\x1fid_token_encrypted_response_alg\x12H\n" +
	"\x1fid_token_encrypted_response_enc\x18u \x01(\tR\x1fid_token_encrypted_response_enc\x12B\n" +
	"\x1cuserinfo_signed_response_alg\x18v \x01(\tR\x1cuserinfo_signed_response_alg\x12H\n" +
	"\x1fuserinfo_encrypted_response_alg\x18w \x01(\tR\x1fuserinfo_encrypted_response_alg\x12H\n" +
	"\x1fuserinfo_encrypted_response_enc\x18x \x01(\tR\x1fuserinfo_encrypted_response_enc\x12>\n" +
	"\x1arequest_object_signing_alg\x18y \x01(\tR\x1arequest_object_signing_alg\x12D\n" +
	"\x1drequest_object_encryption_alg\x18z \x01(\tR\x1drequest_object_encryption_alg\x12D\n" +
	"\x1drequest_object_encryption_enc\x18{ \x01(\tR\x1drequest_object_encryption_enc\x12>\n" +
	"\x1atoken_endpoint_auth_method\x18| \x01(\tR\x1atoken_endpoint_auth_method\x12H\n" +
	"\x1ftoken_endpoint_auth_signing_alg\x18} \x01(\tR\x1ftoken_endpoint_auth_signing_alg\x12(\n" +
	"\x0fdefault_max_age\x18~ \x01(\tR\x0fdefault_max_age\x12,\n" +
	"\x11require_auth_time\x18\x7f \x01(\bR\x11require_auth_time\x12/\n" +
	"\x12default_acr_values\x18\x80\x01 \x03(\tR\x12default_acr_values\x12/\n" +
	"\x12initiate_login_uri\x18\x81\x01 \x01(\tR\x12initiate_login_uri\x12#\n" +
	"\frequest_uris\x18\x82\x01 \x03(\tR\frequest_uris\x12=\n" +
	"\x19post_logout_redirect_uris\x18\x83\x01 \x03(\tR\x19post_logout_redirect_uris\x12U\n" +
	"%require_pushed_authorization_requests\x18\x84\x01 \x01(\bR%require_pushed_authorization_requests\x12M\n" +
	"!authorization_signed_response_alg\x18\x85\x01 \x01(\tR!authorization_signed_response_alg\x12S\n" +
	"$authorization_encrypted_response_alg\x18\x86\x01 \x01(\tR$authorization_encrypted_response_alg\x12S\n" +
	"$authorization_encrypted_response_enc\x18\x87\x01 \x01(\tR$authorization_encrypted_response_enc\x12_\n" +
	"*tls_client_certificate_bound_access_tokens\x18\x88\x01 \x01(\bR*tls_client_certificate_bound_access_tokens\"\x90\x11\n" +
	"\x1eRegistrationGetSuccessResponse\x12\x1c\n" +
	"\tclient_id\x18\x01 \x01(\tR\tclient_id\x12$\n" +
	"\rclient_secret\x18\x02 \x01(\tR\rclient_secret\x120\n" +
	"\x13client_id_issued_at\x18\x05 \x01(\x05R\x13client_id_issued_at\x12:\n" +
	"\x18client_secret_expires_at\x18\x06 \x01(\x05R\x18client_secret_expires_at\x12$\n" +
	"\rredirect_uris\x18e \x03(\tR\rredirect_uris\x12&\n" +
	"\x0eresponse_types\x18f \x03(\tR\x0eresponse_types\x12 \n" +
	"\vgrant_types\x18g \x03(\tR\vgrant_types\x12*\n" +
	"\x10application_type\x18h \x01(\tR\x10application_type\x12\x1a\n" +
	"\bcontacts\x18i \x03(\tR\bcontacts\x12 \n" +
	"\vclient_name\x18j \x01(\tR\vclient_name\x12\x1a\n" +
	"\blogo_uri\x18k \x01(\tR\blogo_uri\x12\x1e\n" +
	"\n" +
	"client_uri\x18l \x01(\tR\n" +
	"client_uri\x12\x1e\n" +
	"\n" +
	"policy_uri\x18m \x01(\tR\n" +
	"policy_uri\x12\x18\n" +
	"\atos_uri\x18n \x01(\tR\atos_uri\x12\x1a\n" +
	"\bjwks_uri\x18o \x01(\tR\bjwks_uri\x12!\n" +
	"\x04jwks\x18p \x01(\v2\r.oppb.v1.JwksR\x04jwks\x124\n" +
	"\x15sector_identifier_uri\x18q \x01(\tR\x15sector_identifier_uri\x12\"\n" +
	"\fsubject_type\x18r \x01(\tR\fsubject_type\x12B\n" +
	"\x1cid_token_signed_response_alg\x18s \x01(\tR\x1cid_token_signed_response_alg\x12H\n" +
	"\x1fid_token_encrypted_response_alg\x18t \x01(\tR\x1fid_token_encrypted_response_alg\x12H\n" +
	"\x1fid_token_encrypted_response_enc\x18u \x01(\tR\x1fid_token_encrypted_response_enc\x12B\n" +
	"\x1cuserinfo_signed_response_alg\x18v \x01(\tR\x1cuserinfo_signed_response_alg\x12H\n" +
	"\x1fuserinfo_encrypted_response_alg\x18w \x01(\tR\x1fuserinfo_encrypted_response_alg\x12H\n" +
	"\x1fuserinfo_encrypted_response_enc\x18x \x01(\tR\x1fuserinfo_encrypted_response_enc\x12>\n" +
	"\x1arequest_object_signing_alg\x18y \x01(\tR\x1arequest_object_signing_alg\x12D\n" +
	"\x1drequest_object_encryption_alg\x18z \x01(\tR\x1drequest_object_encryption_alg\x12D\n" +
	"\x1drequest_object_encryption_enc\x18{ \x01(\tR\x1drequest_object_encryption_enc\x12>\n" +
	"\x1atoken_endpoint_auth_method\x18| \x01(\tR\x1atoken_endpoint_auth_method\x12H\n" +
	"\x1ftoken_endpoint_auth_signing_alg\x18} \x01(\tR\x1ftoken_endpoint_auth_signing_alg\x12(\n" +
	"\x0fdefault_max_age\x18~ \x01(\tR\x0fdefault_max_age\x12,\n" +
	"\x11require_auth_time\x18\x7f \x01(\bR\x11require_auth_time\x12/\n" +
	"\x12default_acr_values\x18\x80\x01 \x03(\tR\x12default_acr_values\x12/\n" +
	"\x12initiate_login_uri\x18\x81\x01 \x01(\tR\x12initiate_login_uri\x12#\n" +
	"\frequest_uris\x18\x82\x01 \x03(\tR\frequest_uris\x12=\n" +
	"\x19post_logout_redirect_uris\x18\x83\x01 \x03(\tR\x19post_logout_redirect_uris\x12U\n" +
	"%require_pushed_authorization_requests\x18\x84\x01 \x01(\bR%require_pushed_authorization_requests\x12M\n" +
	"!authorization_signed_response_alg\x18\x85\x01 \x01(\tR!authorization_signed_response_alg\x12S\n" +
	"$authorization_encrypted_response_alg\x18\x86\x01 \x01(\tR$authorization_encrypted_response_alg\x12S\n" +
	"$authorization_encrypted_response_enc\x18\x87\x01 \x01(\tR$authorization_encrypted_response_enc\x12_\n" +
	"*tls_client_certificate_bound_access_tokens\x18\x88\x01 \x01(\bR*tls_client_certificate_bound_access_tokens\"#\n" +
	"!RegistrationDeleteSuccessResponse\"m\n" +
	"\x18RegistrationFailResponse\x12\x1f\n" +
	"\vstatus_code\x18\x01 \x01(\x05R\n" +
	"statusCode\x120\n" +
	"\x05error\x18\x02 \x01(\v2\x1a.oppb.v1.RegistrationErrorR\x05error\"V\n" +
	"\x11RegistrationError\x12\x14\n" +
	"\x05error\x18\x01 \x01(\tR\x05error\x12+\n" +
	"\x11error_description\x18\x02 \x01(\tR\x10errorDescriptionB\x97\x01\n" +
	"\vcom.oppb.v1B\x11RegistrationProtoP\x01Z8github.com/Eigen438/opgo/pkg/auto-generated/oppb/v1;oppb\xa2\x02\x03OXX\xaa\x02\aOppb.V1\xca\x02\aOppb\\V1\xe2\x02\x13Oppb\\V1\\GPBMetadata\xea\x02\bOppb::V1b\x06proto3"

var (
	file_oppb_v1_registration_proto_rawDescOnce sync.Once
	file_oppb_v1_registration_proto_rawDescData []byte
)

func file_oppb_v1_registration_proto_rawDescGZIP() []byte {
	file_oppb_v1_registration_proto_rawDescOnce.Do(func() {
		file_oppb_v1_registration_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_oppb_v1_registration_proto_rawDesc), len(file_oppb_v1_registration_proto_rawDesc)))
	})
	return file_oppb_v1_registration_proto_rawDescData
}

var file_oppb_v1_registration_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_oppb_v1_registration_proto_goTypes = []any{
	(*RegistrationCreateRequest)(nil),         // 0: oppb.v1.RegistrationCreateRequest
	(*RegistrationCreateResponse)(nil),        // 1: oppb.v1.RegistrationCreateResponse
	(*RegistrationGetRequest)(nil),            // 2: oppb.v1.RegistrationGetRequest
	(*RegistrationGetResponse)(nil),           // 3: oppb.v1.RegistrationGetResponse
	(*RegistrationDeleteRequest)(nil),         // 4: oppb.v1.RegistrationDeleteRequest
	(*RegistrationDeleteResponse)(nil),        // 5: oppb.v1.RegistrationDeleteResponse
	(*RegistrationCreateSuccessResponse)(nil), // 6: oppb.v1.RegistrationCreateSuccessResponse
	(*RegistrationGetSuccessResponse)(nil),    // 7: oppb.v1.RegistrationGetSuccessResponse
	(*RegistrationDeleteSuccessResponse)(nil), // 8: oppb.v1.RegistrationDeleteSuccessResponse
	(*RegistrationFailResponse)(nil),          // 9: oppb.v1.RegistrationFailResponse
	(*RegistrationError)(nil),                 // 10: oppb.v1.RegistrationError
	(*Jwks)(nil),                              // 11: oppb.v1.Jwks
}
var file_oppb_v1_registration_proto_depIdxs = []int32{
	11, // 0: oppb.v1.RegistrationCreateRequest.jwks:type_name -> oppb.v1.Jwks
	6,  // 1: oppb.v1.RegistrationCreateResponse.success:type_name -> oppb.v1.RegistrationCreateSuccessResponse
	9,  // 2: oppb.v1.RegistrationCreateResponse.fail:type_name -> oppb.v1.RegistrationFailResponse
	7,  // 3: oppb.v1.RegistrationGetResponse.success:type_name -> oppb.v1.RegistrationGetSuccessResponse
	9,  // 4: oppb.v1.RegistrationGetResponse.fail:type_name -> oppb.v1.RegistrationFailResponse
	8,  // 5: oppb.v1.RegistrationDeleteResponse.success:type_name -> oppb.v1.RegistrationDeleteSuccessResponse
	9,  // 6: oppb.v1.RegistrationDeleteResponse.fail:type_name -> oppb.v1.RegistrationFailResponse
	11, // 7: oppb.v1.RegistrationCreateSuccessResponse.jwks:type_name -> oppb.v1.Jwks
	11, // 8: oppb.v1.RegistrationGetSuccessResponse.jwks:type_name -> oppb.v1.Jwks
	10, // 9: oppb.v1.RegistrationFailResponse.error:type_name -> oppb.v1.RegistrationError
	10, // [10:10] is the sub-list for method output_type
	10, // [10:10] is the sub-list for method input_type
	10, // [10:10] is the sub-list for extension type_name
	10, // [10:10] is the sub-list for extension extendee
	0,  // [0:10] is the sub-list for field type_name
}

func init() { file_oppb_v1_registration_proto_init() }
func file_oppb_v1_registration_proto_init() {
	if File_oppb_v1_registration_proto != nil {
		return
	}
	file_oppb_v1_jwks_proto_init()
	file_oppb_v1_registration_proto_msgTypes[1].OneofWrappers = []any{
		(*RegistrationCreateResponse_Success)(nil),
		(*RegistrationCreateResponse_Fail)(nil),
	}
	file_oppb_v1_registration_proto_msgTypes[3].OneofWrappers = []any{
		(*RegistrationGetResponse_Success)(nil),
		(*RegistrationGetResponse_Fail)(nil),
	}
	file_oppb_v1_registration_proto_msgTypes[5].OneofWrappers = []any{
		(*RegistrationDeleteResponse_Success)(nil),
		(*RegistrationDeleteResponse_Fail)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_oppb_v1_registration_proto_rawDesc), len(file_oppb_v1_registration_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_oppb_v1_registration_proto_goTypes,
		DependencyIndexes: file_oppb_v1_registration_proto_depIdxs,
		MessageInfos:      file_oppb_v1_registration_proto_msgTypes,
	}.Build()
	File_oppb_v1_registration_proto = out.File
	file_oppb_v1_registration_proto_goTypes = nil
	file_oppb_v1_registration_proto_depIdxs = nil
}
