// MIT License
//
// Copyright (c) 2025 Eigen
//
// Permission is hereby granted, free of charge, to any person obtaining a copy
// of this software and associated documentation files (the "Software"), to deal
// in the Software without restriction, including without limitation the rights
// to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
// copies of the Software, and to permit persons to whom the Software is
// furnished to do so, subject to the following conditions:
//
// The above copyright notice and this permission notice shall be included in all
// copies or substantial portions of the Software.
//
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
// IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
// FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
// AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
// LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
// OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
// SOFTWARE.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        (unknown)
// source: oppb/v1/rest_service.proto

package oppb

import (
	_ "buf.build/gen/go/bufbuild/protovalidate/protocolbuffers/go/buf/validate"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type IssuerCreateRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Meta          *IssuerMeta            `protobuf:"bytes,1,opt,name=meta,proto3" json:"meta,omitempty"`
	Attribute     *IssuerAttribute       `protobuf:"bytes,2,opt,name=attribute,proto3" json:"attribute,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IssuerCreateRequest) Reset() {
	*x = IssuerCreateRequest{}
	mi := &file_oppb_v1_rest_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IssuerCreateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IssuerCreateRequest) ProtoMessage() {}

func (x *IssuerCreateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_oppb_v1_rest_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IssuerCreateRequest.ProtoReflect.Descriptor instead.
func (*IssuerCreateRequest) Descriptor() ([]byte, []int) {
	return file_oppb_v1_rest_service_proto_rawDescGZIP(), []int{0}
}

func (x *IssuerCreateRequest) GetMeta() *IssuerMeta {
	if x != nil {
		return x.Meta
	}
	return nil
}

func (x *IssuerCreateRequest) GetAttribute() *IssuerAttribute {
	if x != nil {
		return x.Attribute
	}
	return nil
}

type IssuerCreateResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           *CommonKey             `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Meta          *IssuerMeta            `protobuf:"bytes,2,opt,name=meta,proto3" json:"meta,omitempty"`
	Secret        *IssuerSecret          `protobuf:"bytes,3,opt,name=secret,proto3" json:"secret,omitempty"`
	Attribute     *IssuerAttribute       `protobuf:"bytes,4,opt,name=attribute,proto3" json:"attribute,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IssuerCreateResponse) Reset() {
	*x = IssuerCreateResponse{}
	mi := &file_oppb_v1_rest_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IssuerCreateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IssuerCreateResponse) ProtoMessage() {}

func (x *IssuerCreateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_oppb_v1_rest_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IssuerCreateResponse.ProtoReflect.Descriptor instead.
func (*IssuerCreateResponse) Descriptor() ([]byte, []int) {
	return file_oppb_v1_rest_service_proto_rawDescGZIP(), []int{1}
}

func (x *IssuerCreateResponse) GetKey() *CommonKey {
	if x != nil {
		return x.Key
	}
	return nil
}

func (x *IssuerCreateResponse) GetMeta() *IssuerMeta {
	if x != nil {
		return x.Meta
	}
	return nil
}

func (x *IssuerCreateResponse) GetSecret() *IssuerSecret {
	if x != nil {
		return x.Secret
	}
	return nil
}

func (x *IssuerCreateResponse) GetAttribute() *IssuerAttribute {
	if x != nil {
		return x.Attribute
	}
	return nil
}

type IssuerGetRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IssuerGetRequest) Reset() {
	*x = IssuerGetRequest{}
	mi := &file_oppb_v1_rest_service_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IssuerGetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IssuerGetRequest) ProtoMessage() {}

func (x *IssuerGetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_oppb_v1_rest_service_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IssuerGetRequest.ProtoReflect.Descriptor instead.
func (*IssuerGetRequest) Descriptor() ([]byte, []int) {
	return file_oppb_v1_rest_service_proto_rawDescGZIP(), []int{2}
}

type IssuerGetResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Meta          *IssuerMeta            `protobuf:"bytes,1,opt,name=meta,proto3" json:"meta,omitempty"`
	Attribute     *IssuerAttribute       `protobuf:"bytes,2,opt,name=attribute,proto3" json:"attribute,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IssuerGetResponse) Reset() {
	*x = IssuerGetResponse{}
	mi := &file_oppb_v1_rest_service_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IssuerGetResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IssuerGetResponse) ProtoMessage() {}

func (x *IssuerGetResponse) ProtoReflect() protoreflect.Message {
	mi := &file_oppb_v1_rest_service_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IssuerGetResponse.ProtoReflect.Descriptor instead.
func (*IssuerGetResponse) Descriptor() ([]byte, []int) {
	return file_oppb_v1_rest_service_proto_rawDescGZIP(), []int{3}
}

func (x *IssuerGetResponse) GetMeta() *IssuerMeta {
	if x != nil {
		return x.Meta
	}
	return nil
}

func (x *IssuerGetResponse) GetAttribute() *IssuerAttribute {
	if x != nil {
		return x.Attribute
	}
	return nil
}

type IssuerUpdateRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Meta          *IssuerMeta            `protobuf:"bytes,1,opt,name=meta,proto3" json:"meta,omitempty"`
	Attribute     *IssuerAttribute       `protobuf:"bytes,2,opt,name=attribute,proto3" json:"attribute,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IssuerUpdateRequest) Reset() {
	*x = IssuerUpdateRequest{}
	mi := &file_oppb_v1_rest_service_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IssuerUpdateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IssuerUpdateRequest) ProtoMessage() {}

func (x *IssuerUpdateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_oppb_v1_rest_service_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IssuerUpdateRequest.ProtoReflect.Descriptor instead.
func (*IssuerUpdateRequest) Descriptor() ([]byte, []int) {
	return file_oppb_v1_rest_service_proto_rawDescGZIP(), []int{4}
}

func (x *IssuerUpdateRequest) GetMeta() *IssuerMeta {
	if x != nil {
		return x.Meta
	}
	return nil
}

func (x *IssuerUpdateRequest) GetAttribute() *IssuerAttribute {
	if x != nil {
		return x.Attribute
	}
	return nil
}

type IssuerUpdateResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Meta          *IssuerMeta            `protobuf:"bytes,1,opt,name=meta,proto3" json:"meta,omitempty"`
	Attribute     *IssuerAttribute       `protobuf:"bytes,2,opt,name=attribute,proto3" json:"attribute,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IssuerUpdateResponse) Reset() {
	*x = IssuerUpdateResponse{}
	mi := &file_oppb_v1_rest_service_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IssuerUpdateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IssuerUpdateResponse) ProtoMessage() {}

func (x *IssuerUpdateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_oppb_v1_rest_service_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IssuerUpdateResponse.ProtoReflect.Descriptor instead.
func (*IssuerUpdateResponse) Descriptor() ([]byte, []int) {
	return file_oppb_v1_rest_service_proto_rawDescGZIP(), []int{5}
}

func (x *IssuerUpdateResponse) GetMeta() *IssuerMeta {
	if x != nil {
		return x.Meta
	}
	return nil
}

func (x *IssuerUpdateResponse) GetAttribute() *IssuerAttribute {
	if x != nil {
		return x.Attribute
	}
	return nil
}

type ClientCreateRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Identity      *ClientIdentity        `protobuf:"bytes,1,opt,name=identity,proto3" json:"identity,omitempty"`
	Meta          *ClientMeta            `protobuf:"bytes,2,opt,name=meta,json=mata,proto3" json:"meta,omitempty"`
	Attribute     *ClientAttribute       `protobuf:"bytes,3,opt,name=attribute,proto3" json:"attribute,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClientCreateRequest) Reset() {
	*x = ClientCreateRequest{}
	mi := &file_oppb_v1_rest_service_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClientCreateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClientCreateRequest) ProtoMessage() {}

func (x *ClientCreateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_oppb_v1_rest_service_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClientCreateRequest.ProtoReflect.Descriptor instead.
func (*ClientCreateRequest) Descriptor() ([]byte, []int) {
	return file_oppb_v1_rest_service_proto_rawDescGZIP(), []int{6}
}

func (x *ClientCreateRequest) GetIdentity() *ClientIdentity {
	if x != nil {
		return x.Identity
	}
	return nil
}

func (x *ClientCreateRequest) GetMeta() *ClientMeta {
	if x != nil {
		return x.Meta
	}
	return nil
}

func (x *ClientCreateRequest) GetAttribute() *ClientAttribute {
	if x != nil {
		return x.Attribute
	}
	return nil
}

type ClientCreateResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Identity      *ClientIdentity        `protobuf:"bytes,1,opt,name=identity,proto3" json:"identity,omitempty"`
	Meta          *ClientMeta            `protobuf:"bytes,2,opt,name=meta,json=mata,proto3" json:"meta,omitempty"`
	Attribute     *ClientAttribute       `protobuf:"bytes,3,opt,name=attribute,proto3" json:"attribute,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClientCreateResponse) Reset() {
	*x = ClientCreateResponse{}
	mi := &file_oppb_v1_rest_service_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClientCreateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClientCreateResponse) ProtoMessage() {}

func (x *ClientCreateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_oppb_v1_rest_service_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClientCreateResponse.ProtoReflect.Descriptor instead.
func (*ClientCreateResponse) Descriptor() ([]byte, []int) {
	return file_oppb_v1_rest_service_proto_rawDescGZIP(), []int{7}
}

func (x *ClientCreateResponse) GetIdentity() *ClientIdentity {
	if x != nil {
		return x.Identity
	}
	return nil
}

func (x *ClientCreateResponse) GetMeta() *ClientMeta {
	if x != nil {
		return x.Meta
	}
	return nil
}

func (x *ClientCreateResponse) GetAttribute() *ClientAttribute {
	if x != nil {
		return x.Attribute
	}
	return nil
}

type SessionGroupCreateRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           *CommonKey             `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Attribute     *SessionGroupAttribute `protobuf:"bytes,2,opt,name=attribute,proto3" json:"attribute,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SessionGroupCreateRequest) Reset() {
	*x = SessionGroupCreateRequest{}
	mi := &file_oppb_v1_rest_service_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SessionGroupCreateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SessionGroupCreateRequest) ProtoMessage() {}

func (x *SessionGroupCreateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_oppb_v1_rest_service_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SessionGroupCreateRequest.ProtoReflect.Descriptor instead.
func (*SessionGroupCreateRequest) Descriptor() ([]byte, []int) {
	return file_oppb_v1_rest_service_proto_rawDescGZIP(), []int{8}
}

func (x *SessionGroupCreateRequest) GetKey() *CommonKey {
	if x != nil {
		return x.Key
	}
	return nil
}

func (x *SessionGroupCreateRequest) GetAttribute() *SessionGroupAttribute {
	if x != nil {
		return x.Attribute
	}
	return nil
}

type SessionGroupCreateResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Attribute     *SessionGroupAttribute `protobuf:"bytes,1,opt,name=attribute,proto3" json:"attribute,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SessionGroupCreateResponse) Reset() {
	*x = SessionGroupCreateResponse{}
	mi := &file_oppb_v1_rest_service_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SessionGroupCreateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SessionGroupCreateResponse) ProtoMessage() {}

func (x *SessionGroupCreateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_oppb_v1_rest_service_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SessionGroupCreateResponse.ProtoReflect.Descriptor instead.
func (*SessionGroupCreateResponse) Descriptor() ([]byte, []int) {
	return file_oppb_v1_rest_service_proto_rawDescGZIP(), []int{9}
}

func (x *SessionGroupCreateResponse) GetAttribute() *SessionGroupAttribute {
	if x != nil {
		return x.Attribute
	}
	return nil
}

type KeyRotateRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	KeyType       string                 `protobuf:"bytes,1,opt,name=key_type,proto3" json:"key_type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *KeyRotateRequest) Reset() {
	*x = KeyRotateRequest{}
	mi := &file_oppb_v1_rest_service_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *KeyRotateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KeyRotateRequest) ProtoMessage() {}

func (x *KeyRotateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_oppb_v1_rest_service_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KeyRotateRequest.ProtoReflect.Descriptor instead.
func (*KeyRotateRequest) Descriptor() ([]byte, []int) {
	return file_oppb_v1_rest_service_proto_rawDescGZIP(), []int{10}
}

func (x *KeyRotateRequest) GetKeyType() string {
	if x != nil {
		return x.KeyType
	}
	return ""
}

type KeyRotateResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *KeyRotateResponse) Reset() {
	*x = KeyRotateResponse{}
	mi := &file_oppb_v1_rest_service_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *KeyRotateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KeyRotateResponse) ProtoMessage() {}

func (x *KeyRotateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_oppb_v1_rest_service_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KeyRotateResponse.ProtoReflect.Descriptor instead.
func (*KeyRotateResponse) Descriptor() ([]byte, []int) {
	return file_oppb_v1_rest_service_proto_rawDescGZIP(), []int{11}
}

var File_oppb_v1_rest_service_proto protoreflect.FileDescriptor

const file_oppb_v1_rest_service_proto_rawDesc = "" +
	"\n" +
	"\x1aoppb/v1/rest_service.proto\x12\aoppb.v1\x1a\x1bbuf/validate/validate.proto\x1a\x1cgoogle/api/annotations.proto\x1a\x14oppb/v1/client.proto\x1a\x19oppb/v1/client_meta.proto\x1a\x14oppb/v1/common.proto\x1a\x14oppb/v1/issuer.proto\x1a\x19oppb/v1/issuer_meta.proto\x1a\x1boppb/v1/session_group.proto\"~\n" +
	"\x13IssuerCreateRequest\x12/\n" +
	"\x04meta\x18\x01 \x01(\v2\x13.oppb.v1.IssuerMetaB\x06\xbaH\x03\xc8\x01\x01R\x04meta\x126\n" +
	"\tattribute\x18\x02 \x01(\v2\x18.oppb.v1.IssuerAttributeR\tattribute\"\xcc\x01\n" +
	"\x14IssuerCreateResponse\x12$\n" +
	"\x03key\x18\x01 \x01(\v2\x12.oppb.v1.CommonKeyR\x03key\x12'\n" +
	"\x04meta\x18\x02 \x01(\v2\x13.oppb.v1.IssuerMetaR\x04meta\x12-\n" +
	"\x06secret\x18\x03 \x01(\v2\x15.oppb.v1.IssuerSecretR\x06secret\x126\n" +
	"\tattribute\x18\x04 \x01(\v2\x18.oppb.v1.IssuerAttributeR\tattribute\"\x12\n" +
	"\x10IssuerGetRequest\"t\n" +
	"\x11IssuerGetResponse\x12'\n" +
	"\x04meta\x18\x01 \x01(\v2\x13.oppb.v1.IssuerMetaR\x04meta\x126\n" +
	"\tattribute\x18\x02 \x01(\v2\x18.oppb.v1.IssuerAttributeR\tattribute\"v\n" +
	"\x13IssuerUpdateRequest\x12'\n" +
	"\x04meta\x18\x01 \x01(\v2\x13.oppb.v1.IssuerMetaR\x04meta\x126\n" +
	"\tattribute\x18\x02 \x01(\v2\x18.oppb.v1.IssuerAttributeR\tattribute\"w\n" +
	"\x14IssuerUpdateResponse\x12'\n" +
	"\x04meta\x18\x01 \x01(\v2\x13.oppb.v1.IssuerMetaR\x04meta\x126\n" +
	"\tattribute\x18\x02 \x01(\v2\x18.oppb.v1.IssuerAttributeR\tattribute\"\xab\x01\n" +
	"\x13ClientCreateRequest\x123\n" +
	"\bidentity\x18\x01 \x01(\v2\x17.oppb.v1.ClientIdentityR\bidentity\x12'\n" +
	"\x04meta\x18\x02 \x01(\v2\x13.oppb.v1.ClientMetaR\x04mata\x126\n" +
	"\tattribute\x18\x03 \x01(\v2\x18.oppb.v1.ClientAttributeR\tattribute\"\xac\x01\n" +
	"\x14ClientCreateResponse\x123\n" +
	"\bidentity\x18\x01 \x01(\v2\x17.oppb.v1.ClientIdentityR\bidentity\x12'\n" +
	"\x04meta\x18\x02 \x01(\v2\x13.oppb.v1.ClientMetaR\x04mata\x126\n" +
	"\tattribute\x18\x03 \x01(\v2\x18.oppb.v1.ClientAttributeR\tattribute\"\x7f\n" +
	"\x19SessionGroupCreateRequest\x12$\n" +
	"\x03key\x18\x01 \x01(\v2\x12.oppb.v1.CommonKeyR\x03key\x12<\n" +
	"\tattribute\x18\x02 \x01(\v2\x1e.oppb.v1.SessionGroupAttributeR\tattribute\"Z\n" +
	"\x1aSessionGroupCreateResponse\x12<\n" +
	"\tattribute\x18\x01 \x01(\v2\x1e.oppb.v1.SessionGroupAttributeR\tattribute\".\n" +
	"\x10KeyRotateRequest\x12\x1a\n" +
	"\bkey_type\x18\x01 \x01(\tR\bkey_type\"\x13\n" +
	"\x11KeyRotateResponse2\x98\x04\n" +
	"\vRestService\x12c\n" +
	"\fIssuerCreate\x12\x1c.oppb.v1.IssuerCreateRequest\x1a\x1d.oppb.v1.IssuerCreateResponse\"\x16\x82\xd3\xe4\x93\x02\x10:\x01*\"\v/issuer/new\x12S\n" +
	"\tIssuerGet\x12\x19.oppb.v1.IssuerGetRequest\x1a\x1a.oppb.v1.IssuerGetResponse\"\x0f\x82\xd3\xe4\x93\x02\t\x12\a/issuer\x12_\n" +
	"\fIssuerUpdate\x12\x1c.oppb.v1.IssuerUpdateRequest\x1a\x1d.oppb.v1.IssuerUpdateResponse\"\x12\x82\xd3\xe4\x93\x02\f:\x01*\"\a/issuer\x12K\n" +
	"\fClientCreate\x12\x1c.oppb.v1.ClientCreateRequest\x1a\x1d.oppb.v1.ClientCreateResponse\x12]\n" +
	"\x12SessionGroupCreate\x12\".oppb.v1.SessionGroupCreateRequest\x1a#.oppb.v1.SessionGroupCreateResponse\x12B\n" +
	"\tKeyRotate\x12\x19.oppb.v1.KeyRotateRequest\x1a\x1a.oppb.v1.KeyRotateResponseB\x96\x01\n" +
	"\vcom.oppb.v1B\x10RestServiceProtoP\x01Z8github.com/Eigen438/opgo/pkg/auto-generated/oppb/v1;oppb\xa2\x02\x03OXX\xaa\x02\aOppb.V1\xca\x02\aOppb\\V1\xe2\x02\x13Oppb\\V1\\GPBMetadata\xea\x02\bOppb::V1b\x06proto3"

var (
	file_oppb_v1_rest_service_proto_rawDescOnce sync.Once
	file_oppb_v1_rest_service_proto_rawDescData []byte
)

func file_oppb_v1_rest_service_proto_rawDescGZIP() []byte {
	file_oppb_v1_rest_service_proto_rawDescOnce.Do(func() {
		file_oppb_v1_rest_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_oppb_v1_rest_service_proto_rawDesc), len(file_oppb_v1_rest_service_proto_rawDesc)))
	})
	return file_oppb_v1_rest_service_proto_rawDescData
}

var file_oppb_v1_rest_service_proto_msgTypes = make([]protoimpl.MessageInfo, 12)
var file_oppb_v1_rest_service_proto_goTypes = []any{
	(*IssuerCreateRequest)(nil),        // 0: oppb.v1.IssuerCreateRequest
	(*IssuerCreateResponse)(nil),       // 1: oppb.v1.IssuerCreateResponse
	(*IssuerGetRequest)(nil),           // 2: oppb.v1.IssuerGetRequest
	(*IssuerGetResponse)(nil),          // 3: oppb.v1.IssuerGetResponse
	(*IssuerUpdateRequest)(nil),        // 4: oppb.v1.IssuerUpdateRequest
	(*IssuerUpdateResponse)(nil),       // 5: oppb.v1.IssuerUpdateResponse
	(*ClientCreateRequest)(nil),        // 6: oppb.v1.ClientCreateRequest
	(*ClientCreateResponse)(nil),       // 7: oppb.v1.ClientCreateResponse
	(*SessionGroupCreateRequest)(nil),  // 8: oppb.v1.SessionGroupCreateRequest
	(*SessionGroupCreateResponse)(nil), // 9: oppb.v1.SessionGroupCreateResponse
	(*KeyRotateRequest)(nil),           // 10: oppb.v1.KeyRotateRequest
	(*KeyRotateResponse)(nil),          // 11: oppb.v1.KeyRotateResponse
	(*IssuerMeta)(nil),                 // 12: oppb.v1.IssuerMeta
	(*IssuerAttribute)(nil),            // 13: oppb.v1.IssuerAttribute
	(*CommonKey)(nil),                  // 14: oppb.v1.CommonKey
	(*IssuerSecret)(nil),               // 15: oppb.v1.IssuerSecret
	(*ClientIdentity)(nil),             // 16: oppb.v1.ClientIdentity
	(*ClientMeta)(nil),                 // 17: oppb.v1.ClientMeta
	(*ClientAttribute)(nil),            // 18: oppb.v1.ClientAttribute
	(*SessionGroupAttribute)(nil),      // 19: oppb.v1.SessionGroupAttribute
}
var file_oppb_v1_rest_service_proto_depIdxs = []int32{
	12, // 0: oppb.v1.IssuerCreateRequest.meta:type_name -> oppb.v1.IssuerMeta
	13, // 1: oppb.v1.IssuerCreateRequest.attribute:type_name -> oppb.v1.IssuerAttribute
	14, // 2: oppb.v1.IssuerCreateResponse.key:type_name -> oppb.v1.CommonKey
	12, // 3: oppb.v1.IssuerCreateResponse.meta:type_name -> oppb.v1.IssuerMeta
	15, // 4: oppb.v1.IssuerCreateResponse.secret:type_name -> oppb.v1.IssuerSecret
	13, // 5: oppb.v1.IssuerCreateResponse.attribute:type_name -> oppb.v1.IssuerAttribute
	12, // 6: oppb.v1.IssuerGetResponse.meta:type_name -> oppb.v1.IssuerMeta
	13, // 7: oppb.v1.IssuerGetResponse.attribute:type_name -> oppb.v1.IssuerAttribute
	12, // 8: oppb.v1.IssuerUpdateRequest.meta:type_name -> oppb.v1.IssuerMeta
	13, // 9: oppb.v1.IssuerUpdateRequest.attribute:type_name -> oppb.v1.IssuerAttribute
	12, // 10: oppb.v1.IssuerUpdateResponse.meta:type_name -> oppb.v1.IssuerMeta
	13, // 11: oppb.v1.IssuerUpdateResponse.attribute:type_name -> oppb.v1.IssuerAttribute
	16, // 12: oppb.v1.ClientCreateRequest.identity:type_name -> oppb.v1.ClientIdentity
	17, // 13: oppb.v1.ClientCreateRequest.meta:type_name -> oppb.v1.ClientMeta
	18, // 14: oppb.v1.ClientCreateRequest.attribute:type_name -> oppb.v1.ClientAttribute
	16, // 15: oppb.v1.ClientCreateResponse.identity:type_name -> oppb.v1.ClientIdentity
	17, // 16: oppb.v1.ClientCreateResponse.meta:type_name -> oppb.v1.ClientMeta
	18, // 17: oppb.v1.ClientCreateResponse.attribute:type_name -> oppb.v1.ClientAttribute
	14, // 18: oppb.v1.SessionGroupCreateRequest.key:type_name -> oppb.v1.CommonKey
	19, // 19: oppb.v1.SessionGroupCreateRequest.attribute:type_name -> oppb.v1.SessionGroupAttribute
	19, // 20: oppb.v1.SessionGroupCreateResponse.attribute:type_name -> oppb.v1.SessionGroupAttribute
	0,  // 21: oppb.v1.RestService.IssuerCreate:input_type -> oppb.v1.IssuerCreateRequest
	2,  // 22: oppb.v1.RestService.IssuerGet:input_type -> oppb.v1.IssuerGetRequest
	4,  // 23: oppb.v1.RestService.IssuerUpdate:input_type -> oppb.v1.IssuerUpdateRequest
	6,  // 24: oppb.v1.RestService.ClientCreate:input_type -> oppb.v1.ClientCreateRequest
	8,  // 25: oppb.v1.RestService.SessionGroupCreate:input_type -> oppb.v1.SessionGroupCreateRequest
	10, // 26: oppb.v1.RestService.KeyRotate:input_type -> oppb.v1.KeyRotateRequest
	1,  // 27: oppb.v1.RestService.IssuerCreate:output_type -> oppb.v1.IssuerCreateResponse
	3,  // 28: oppb.v1.RestService.IssuerGet:output_type -> oppb.v1.IssuerGetResponse
	5,  // 29: oppb.v1.RestService.IssuerUpdate:output_type -> oppb.v1.IssuerUpdateResponse
	7,  // 30: oppb.v1.RestService.ClientCreate:output_type -> oppb.v1.ClientCreateResponse
	9,  // 31: oppb.v1.RestService.SessionGroupCreate:output_type -> oppb.v1.SessionGroupCreateResponse
	11, // 32: oppb.v1.RestService.KeyRotate:output_type -> oppb.v1.KeyRotateResponse
	27, // [27:33] is the sub-list for method output_type
	21, // [21:27] is the sub-list for method input_type
	21, // [21:21] is the sub-list for extension type_name
	21, // [21:21] is the sub-list for extension extendee
	0,  // [0:21] is the sub-list for field type_name
}

func init() { file_oppb_v1_rest_service_proto_init() }
func file_oppb_v1_rest_service_proto_init() {
	if File_oppb_v1_rest_service_proto != nil {
		return
	}
	file_oppb_v1_client_proto_init()
	file_oppb_v1_client_meta_proto_init()
	file_oppb_v1_common_proto_init()
	file_oppb_v1_issuer_proto_init()
	file_oppb_v1_issuer_meta_proto_init()
	file_oppb_v1_session_group_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_oppb_v1_rest_service_proto_rawDesc), len(file_oppb_v1_rest_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   12,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_oppb_v1_rest_service_proto_goTypes,
		DependencyIndexes: file_oppb_v1_rest_service_proto_depIdxs,
		MessageInfos:      file_oppb_v1_rest_service_proto_msgTypes,
	}.Build()
	File_oppb_v1_rest_service_proto = out.File
	file_oppb_v1_rest_service_proto_goTypes = nil
	file_oppb_v1_rest_service_proto_depIdxs = nil
}
